// Code generated by xgen. DO NOT EDIT.

package irsform

// AccountingFeesSchedule is Common return document attributes
type AccountingFeesSchedule struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*AccountingFeesScheduleType
}

// AccountingFeesDetail is Disbursements for Charitable Purposes
type AccountingFeesDetail struct {
	CategoryTxt                    string `xml:"CategoryTxt,omitempty"`
	Amt                            int    `xml:"Amt,omitempty"`
	NetInvestmentIncomeAmt         int    `xml:"NetInvestmentIncomeAmt,omitempty"`
	AdjustedNetIncomeAmt           int    `xml:"AdjustedNetIncomeAmt,omitempty"`
	DisbursementsCharitablePrpsAmt int    `xml:"DisbursementsCharitablePrpsAmt,omitempty"`
}

// AccountingFeesScheduleType is Content model for Accounting Fees Schedule
type AccountingFeesScheduleType struct {
	AccountingFeesDetail []*AccountingFeesDetail `xml:"AccountingFeesDetail,omitempty"`
}
