// Code generated by xgen. DO NOT EDIT.

package irsform

// ActyNotPreviouslyRptExpln is Common return document attributes
type ActyNotPreviouslyRptExpln struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*ActyNotPreviouslyRptExplnType
}

// ActyNotPreviouslyRptExplnType is Content model for activities not previously reported explanation
type ActyNotPreviouslyRptExplnType struct {
	ExplanationTxt string `xml:"ExplanationTxt,omitempty"`
}
