// Code generated by xgen. DO NOT EDIT.

package irsform

// AffiliatedGroupSchedule is Common return document attributes
type AffiliatedGroupSchedule struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*AffiliatedGroupScheduleType
}

// AffiliatedScheduleGrp is Share Of Excess Lobbying Expenditures Amount
type AffiliatedScheduleGrp struct {
	BusinessName                  *BusinessNameType   `xml:"BusinessName,omitempty"`
	USAddress                     *USAddressType      `xml:"USAddress,omitempty"`
	ForeignAddress                *ForeignAddressType `xml:"ForeignAddress,omitempty"`
	EIN                           string              `xml:"EIN"`
	ElectingOrganizationInd       string              `xml:"ElectingOrganizationInd,omitempty"`
	TotalGrassrootsLobbyAmt       int                 `xml:"TotalGrassrootsLobbyAmt"`
	TotalDirectLobbyAmt           int                 `xml:"TotalDirectLobbyAmt"`
	TotalLobbyExpenditureAmt      int                 `xml:"TotalLobbyExpenditureAmt"`
	OtherExemptPurposeExpendAmt   int                 `xml:"OtherExemptPurposeExpendAmt"`
	TotalExemptPurposeExpendAmt   int                 `xml:"TotalExemptPurposeExpendAmt"`
	LobbyNontxAmt                 int                 `xml:"LobbyNontxAmt"`
	GrassrootsNontxAmt            int                 `xml:"GrassrootsNontxAmt"`
	TotalLobbyGrssrootMnsNontxAmt int                 `xml:"TotalLobbyGrssrootMnsNontxAmt"`
	TotLbbyExpendMnsLobbyNontxAmt int                 `xml:"TotLbbyExpendMnsLobbyNontxAmt"`
	ShareExcessLobbyExpendAmt     int                 `xml:"ShareExcessLobbyExpendAmt"`
}

// AffiliatedGroupScheduleType is Content model for Affiliated Group Schedule
type AffiliatedGroupScheduleType struct {
	AffiliatedScheduleGrp []*AffiliatedScheduleGrp `xml:"AffiliatedScheduleGrp,omitempty"`
}
