// Code generated by xgen. DO NOT EDIT.

package irsform

// AffiliatedGroupAttachment is Common return document attributes
type AffiliatedGroupAttachment struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*AffiliatedGroupAttachmentType
}

// AffiliatedGroupAttachmentType is Explanation
type AffiliatedGroupAttachmentType struct {
	MeduimExplanationTxt string `xml:"MeduimExplanationTxt,omitempty"`
}
