// Code generated by xgen. DO NOT EDIT.

package irsform

// AffiliateListing is Common return document attributes
type AffiliateListing struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*AffiliateListingType
}

// AffiliateListingType is Content model for affiliate listing
type AffiliateListingType struct {
	AffiliateListingGrp []*AffiliateListingGrpType `xml:"AffiliateListingGrp,omitempty"`
}

// AffiliateListingGrpType is Name control
type AffiliateListingGrpType struct {
	BusinessName           *BusinessNameType   `xml:"BusinessName,omitempty"`
	USAddress              *USAddressType      `xml:"USAddress"`
	ForeignAddress         *ForeignAddressType `xml:"ForeignAddress"`
	EIN                    string              `xml:"EIN"`
	BusinessNameControlTxt string              `xml:"BusinessNameControlTxt"`
}
