// Code generated by xgen. DO NOT EDIT.

package irsform

// AllOthProgRltdInvestmentsSch is Common return document attributes
type AllOthProgRltdInvestmentsSch struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*AllOthProgRltdInvestmentsSchType
}

// AllOtherProgramRelatedInvstGrp is Amount
type AllOtherProgramRelatedInvstGrp struct {
	Desc string `xml:"Desc,omitempty"`
	Amt  int    `xml:"Amt,omitempty"`
}

// AllOthProgRltdInvestmentsSchType is Content model for All Other Program Related Investments Schedule
type AllOthProgRltdInvestmentsSchType struct {
	AllOtherProgramRelatedInvstGrp []*AllOtherProgramRelatedInvstGrp `xml:"AllOtherProgramRelatedInvstGrp,omitempty"`
}
