// Code generated by xgen. DO NOT EDIT.

package irsform

// AmortizationSchedule is Common return document attributes
type AmortizationSchedule struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*AmortizationScheduleType
}

// AmortizationScheduleDetail is Total Amount of Amortization
type AmortizationScheduleDetail struct {
	AmortizedExpensesDesc         string  `xml:"AmortizedExpensesDesc,omitempty"`
	AcquiredCompletedOrExpendedDt string  `xml:"AcquiredCompletedOrExpendedDt,omitempty"`
	AmortizedAmt                  int     `xml:"AmortizedAmt,omitempty"`
	DeductionForPriorYearsAmt     int     `xml:"DeductionForPriorYearsAmt,omitempty"`
	AmortizationPeriodRt          float64 `xml:"AmortizationPeriodRt,omitempty"`
	CurrentYearAmortizationAmt    int     `xml:"CurrentYearAmortizationAmt,omitempty"`
	NetInvestmentIncomeAmt        int     `xml:"NetInvestmentIncomeAmt,omitempty"`
	AdjustedNetIncomeAmt          int     `xml:"AdjustedNetIncomeAmt,omitempty"`
	TotalAmortizationAmt          int     `xml:"TotalAmortizationAmt,omitempty"`
}

// AmortizationScheduleType is Content model for Amortization Schedule
type AmortizationScheduleType struct {
	AmortizationScheduleDetail []*AmortizationScheduleDetail `xml:"AmortizationScheduleDetail,omitempty"`
}
