// Code generated by xgen. DO NOT EDIT.

package irsform

// AppliedToPriorYearElection is Common return document attributes
type AppliedToPriorYearElection struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*AppliedToPriorYearElectionType
}

// AppliedToPriorYearElectionType is Content model for Applied to Prior Year Election
type AppliedToPriorYearElectionType struct {
	ElectionDesc string `xml:"ElectionDesc,omitempty"`
}
