// Code generated by xgen. DO NOT EDIT.

package irsform

// AveragingAttachment is Common return document attributes
type AveragingAttachment struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*AveragingAttachmentType
}

// AveragingAttachmentType is Explanation
type AveragingAttachmentType struct {
	ExplanationTxt string `xml:"ExplanationTxt,omitempty"`
}
