// Code generated by xgen. DO NOT EDIT.

package irsform

// BinaryAttachment is Common return document attributes
type BinaryAttachment struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*BinaryAttachmentType
}

// BinaryAttachmentType is Content model for Binary Attachment
type BinaryAttachmentType struct {
	DocumentTypeCd        interface{} `xml:"DocumentTypeCd"`
	Desc                  interface{} `xml:"Desc"`
	AttachmentLocationTxt interface{} `xml:"AttachmentLocationTxt"`
}
