// Code generated by xgen. DO NOT EDIT.

package irsform

// BorrowedFundsElection is Common return document attributes
type BorrowedFundsElection struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*BorrowedFundsElectionType
}

// BorrowedFundsGrp is Election Statement
type BorrowedFundsGrp struct {
	BusinessName          *BusinessNameType   `xml:"BusinessName"`
	PersonNm              string              `xml:"PersonNm"`
	USAddress             *USAddressType      `xml:"USAddress"`
	ForeignAddress        *ForeignAddressType `xml:"ForeignAddress"`
	BorrowedAmt           int                 `xml:"BorrowedAmt,omitempty"`
	UseOfBorrowedFundsTxt string              `xml:"UseOfBorrowedFundsTxt,omitempty"`
	ElectionStatementTxt  string              `xml:"ElectionStatementTxt,omitempty"`
}

// BorrowedFundsElectionType is Content model for Borrowed Funds Election
type BorrowedFundsElectionType struct {
	BorrowedFundsGrp []*BorrowedFundsGrp `xml:"BorrowedFundsGrp,omitempty"`
}
