// Code generated by xgen. DO NOT EDIT.

package irsform

// CashDistributionExplnStmt is Common return document attributes
type CashDistributionExplnStmt struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*CashDistributionExplnStmtType
}

// CashDistributionExplnStmtType is Content model for Cash Distribution Explanation Statement
type CashDistributionExplnStmtType struct {
	ExplanationTxt string `xml:"ExplanationTxt,omitempty"`
}
