// Code generated by xgen. DO NOT EDIT.

package irsform

// CashDeemedCharitableExplnStmt is Common return document attributes
type CashDeemedCharitableExplnStmt struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*CashDeemedCharitableExplnStmtType
}

// CashDeemedCharitableExplnStmtType is Content model for Cash Deemed Charitable Explanation Statement
type CashDeemedCharitableExplnStmtType struct {
	ShortExplanationTxt string `xml:"ShortExplanationTxt,omitempty"`
}
