// Code generated by xgen. DO NOT EDIT.

package irsform

// CompensationExplanation is Common return document attributes
type CompensationExplanation struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*CompensationExplanationType
}

// CompensationExplanationType is Content model for compensation explanation
type CompensationExplanationType struct {
	CompensationExplanationGrp []*CompensationExplanationGrpType `xml:"CompensationExplanationGrp,omitempty"`
}

// CompensationExplanationGrpType is Explanation
type CompensationExplanationGrpType struct {
	PersonNm            string            `xml:"PersonNm"`
	BusinessName        *BusinessNameType `xml:"BusinessName"`
	ShortExplanationTxt string            `xml:"ShortExplanationTxt,omitempty"`
}
