// Code generated by xgen. DO NOT EDIT.

package irsform

// ContractorCompensationExpln is Common return document attributes
type ContractorCompensationExpln struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*ContractorCompExplnType
}

// ContractorCompExplnGrp is Explanation
type ContractorCompExplnGrp struct {
	ContractorPersonNm     string            `xml:"ContractorPersonNm"`
	ContractorBusinessName *BusinessNameType `xml:"ContractorBusinessName"`
	ExplanationTxt         string            `xml:"ExplanationTxt,omitempty"`
}

// ContractorCompExplnType is Content model for contractor compensation explanation
type ContractorCompExplnType struct {
	ContractorCompExplnGrp []*ContractorCompExplnGrp `xml:"ContractorCompExplnGrp,omitempty"`
}
