// Code generated by xgen. DO NOT EDIT.

package irsform

// DepreciationSchedule is Common return document attributes
type DepreciationSchedule struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*DepreciationScheduleType
}

// DepreciationPropertyGrp is Cost of Goods Sold Not Included
type DepreciationPropertyGrp struct {
	PropertyDesc                  string  `xml:"PropertyDesc,omitempty"`
	AcquiredDt                    string  `xml:"AcquiredDt,omitempty"`
	CostOrOtherBasisAmt           int     `xml:"CostOrOtherBasisAmt,omitempty"`
	PriorYearDepreciationAmt      int     `xml:"PriorYearDepreciationAmt,omitempty"`
	ComputationMethodTxt          string  `xml:"ComputationMethodTxt,omitempty"`
	Rt                            float64 `xml:"Rt"`
	LifeRt                        float64 `xml:"LifeRt"`
	CurrentYearExpenseAmt         int     `xml:"CurrentYearExpenseAmt,omitempty"`
	NetInvestmentIncomeAmt        int     `xml:"NetInvestmentIncomeAmt,omitempty"`
	AdjustedNetIncomeAmt          int     `xml:"AdjustedNetIncomeAmt,omitempty"`
	CostOfGoodsSoldNotIncludedAmt int     `xml:"CostOfGoodsSoldNotIncludedAmt,omitempty"`
}

// DepreciationScheduleType is Content model for Depreciation Schedule
type DepreciationScheduleType struct {
	DepreciationPropertyGrp []*DepreciationPropertyGrp `xml:"DepreciationPropertyGrp,omitempty"`
}
