// Code generated by xgen. DO NOT EDIT.

package irsform

// DissolutionStmt is Common return document attributes
type DissolutionStmt struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*DissolutionStmtType
}

// DissolutionInformationGrp is Dissolution Amount
type DissolutionInformationGrp struct {
	BusinessName        *BusinessNameType   `xml:"BusinessName,omitempty"`
	PersonNm            string              `xml:"PersonNm,omitempty"`
	USAddress           *USAddressType      `xml:"USAddress,omitempty"`
	ForeignAddress      *ForeignAddressType `xml:"ForeignAddress,omitempty"`
	ShortExplanationTxt string              `xml:"ShortExplanationTxt"`
	DissolutionAmt      int                 `xml:"DissolutionAmt"`
}

// DissolutionStmtType is Content model for Dissolution Statement
type DissolutionStmtType struct {
	DissolutionInformationGrp []*DissolutionInformationGrp `xml:"DissolutionInformationGrp,omitempty"`
}
