// Code generated by xgen. DO NOT EDIT.

package irsform

// DistributionFromCorpusElection is Common return document attributes
type DistributionFromCorpusElection struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*DistributionFromCorpusElectionType
}

// DistributionFromCorpusElectionType is Content model for Distribution from Corpus Election
type DistributionFromCorpusElectionType struct {
	ElectionDesc string `xml:"ElectionDesc,omitempty"`
}
