// Code generated by xgen. DO NOT EDIT.

package irsform

// DonorAdvisedFundStmt is Common return document attributes
type DonorAdvisedFundStmt struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*DonorAdvisedFundStmtType
}

// DonorAdvisedFundGrp is How distribution will be used to accomplish section 170(c)(2)(B) purpose
type DonorAdvisedFundGrp struct {
	QualifyingDistributionTxt string `xml:"QualifyingDistributionTxt"`
	Sect170c2BPurposeExplnTxt string `xml:"Sect170c2BPurposeExplnTxt"`
}

// DonorAdvisedFundStmtType is Content model for Donor Advised Fund Statement
type DonorAdvisedFundStmtType struct {
	DonorAdvisedFundGrp []*DonorAdvisedFundGrp `xml:"DonorAdvisedFundGrp,omitempty"`
}
