// Code generated by xgen. DO NOT EDIT.

package irsform

// IFATransmissionHeader ...
type IFATransmissionHeader *IFATransmissionHeaderType

// TransmitterDetail is The ETIN of the transmitter
type TransmitterDetail struct {
	ETIN string `xml:"ETIN"`
}

// IFATransmissionHeaderType is The time stamp at the time of transmission.
type IFATransmissionHeaderType struct {
	MessageId         string             `xml:"MessageId"`
	TransmissionTs    string             `xml:"TransmissionTs,omitempty"`
	TransmitterDetail *TransmitterDetail `xml:"TransmitterDetail"`
}

// MessageIdType ...
type MessageIdType string
