// Code generated by xgen. DO NOT EDIT.

package irsform

// IRSSubmissionManifest ...
type IRSSubmissionManifest struct {
	CommonSubmissionAndAcknowledgementElements *CommonSubmissionAndAcknowledgementElements
	TaxYr                                      string      `xml:"TaxYr,omitempty"`
	GovernmentCd                               string      `xml:"GovernmentCd"`
	FederalSubmissionTypeCd                    interface{} `xml:"FederalSubmissionTypeCd"`
	TaxPeriodBeginDt                           string      `xml:"TaxPeriodBeginDt,omitempty"`
	TaxPeriodEndDt                             string      `xml:"TaxPeriodEndDt,omitempty"`
	TIN                                        string      `xml:"TIN"`
}

// StateSubmissionManifest ...
type StateSubmissionManifest struct {
	CommonSubmissionAndAcknowledgementElements *CommonSubmissionAndAcknowledgementElements
	TaxYr                                      string      `xml:"TaxYr"`
	GovernmentCd                               string      `xml:"GovernmentCd"`
	StateSubmissionTyp                         interface{} `xml:"StateSubmissionTyp"`
	SubmissionCategoryCd                       string      `xml:"SubmissionCategoryCd"`
	FederalEIN                                 interface{} `xml:"FederalEIN"`
	BusinessNameControlTxt                     string      `xml:"BusinessNameControlTxt"`
	PrimarySSN                                 string      `xml:"PrimarySSN"`
	PrimaryNameControlTxt                      string      `xml:"PrimaryNameControlTxt"`
	SpouseSSN                                  string      `xml:"SpouseSSN"`
	SpouseNameControlTxt                       string      `xml:"SpouseNameControlTxt"`
	TempId                                     string      `xml:"TempId"`
	IRSSubmissionId                            string      `xml:"IRSSubmissionId,omitempty"`
	StateSchemaVersionNum                      interface{} `xml:"StateSchemaVersionNum,omitempty"`
}

// SubmissionReceiptGrp ...
type SubmissionReceiptGrp struct {
	SubmissionId         string `xml:"SubmissionId"`
	SubmissionReceivedTs string `xml:"SubmissionReceivedTs"`
	ReceiptId            string `xml:"ReceiptId,omitempty"`
}

// SubmissionReceiptList ...
type SubmissionReceiptList struct {
	Cnt                  int                     `xml:"Cnt"`
	SubmissionReceiptGrp []*SubmissionReceiptGrp `xml:"SubmissionReceiptGrp,omitempty"`
}

// Acknowledgement ...
type Acknowledgement struct {
	SubmissionVersionNumAttr                   string `xml:"submissionVersionNum,attr,omitempty"`
	ValidatingSchemaVersionNumAttr             string `xml:"validatingSchemaVersionNum,attr,omitempty"`
	CommonSubmissionAndAcknowledgementElements *CommonSubmissionAndAcknowledgementElements
	TaxYr                                      string                         `xml:"TaxYr,omitempty"`
	ExtndGovernmentCd                          *ExtndGovernmentCdType         `xml:"ExtndGovernmentCd"`
	SubmissionTyp                              interface{}                    `xml:"SubmissionTyp"`
	ExtndSubmissionCategoryCd                  *ExtndSubmissionCategoryCdType `xml:"ExtndSubmissionCategoryCd"`
	ReceiptId                                  string                         `xml:"ReceiptId,omitempty"`
	ElectronicPostmarkTs                       string                         `xml:"ElectronicPostmarkTs,omitempty"`
	AcceptanceStatusTxt                        interface{}                    `xml:"AcceptanceStatusTxt"`
	ContainedAlertsInd                         bool                           `xml:"ContainedAlertsInd"`
	StatusDt                                   string                         `xml:"StatusDt"`
	IRSSubmissionId                            string                         `xml:"IRSSubmissionId,omitempty"`
	StateSubmissionCopyCnt                     int                            `xml:"StateSubmissionCopyCnt,omitempty"`
	TIN                                        string                         `xml:"TIN"`
	TempId                                     string                         `xml:"TempId"`
	IRSReceivedDt                              string                         `xml:"IRSReceivedDt,omitempty"`
	ExtensionFilingTypeDesc                    interface{}                    `xml:"ExtensionFilingTypeDesc,omitempty"`
	TaxPeriodEndDt                             string                         `xml:"TaxPeriodEndDt,omitempty"`
	PaymentRequestRcvdCd                       interface{}                    `xml:"PaymentRequestRcvdCd,omitempty"`
	SubmissionValidationCompInd                bool                           `xml:"SubmissionValidationCompInd,omitempty"`
	EmbeddedCRC32Num                           interface{}                    `xml:"EmbeddedCRC32Num,omitempty"`
	ComputedCRC32Num                           interface{}                    `xml:"ComputedCRC32Num,omitempty"`
	TaxableIncomeAmt                           int                            `xml:"TaxableIncomeAmt,omitempty"`
	TotalTaxAmt                                int                            `xml:"TotalTaxAmt,omitempty"`
	NetIncomeLossAmt                           int                            `xml:"NetIncomeLossAmt,omitempty"`
	ReservedIPAddressCd                        interface{}                    `xml:"ReservedIPAddressCd,omitempty"`
	ExpectedRefundAmt                          int                            `xml:"ExpectedRefundAmt"`
	BalanceDueAmt                              int                            `xml:"BalanceDueAmt"`
	BirthDtValidityCd                          interface{}                    `xml:"BirthDtValidityCd,omitempty"`
	PINPresenceCd                              interface{}                    `xml:"PINPresenceCd,omitempty"`
	ITINMismatchCd                             interface{}                    `xml:"ITINMismatchCd,omitempty"`
	ValidationErrorList                        *ValidationErrorListType       `xml:"ValidationErrorList,omitempty"`
	ValidationAlertList                        *ValidationAlertListType       `xml:"ValidationAlertList,omitempty"`
}

// AcknowledgementList ...
type AcknowledgementList struct {
	Cnt             int                `xml:"Cnt"`
	Acknowledgement []*Acknowledgement `xml:"Acknowledgement,omitempty"`
}

// StatusRecordGrp ...
type StatusRecordGrp struct {
	SubmissionId                  string `xml:"SubmissionId"`
	SubmissionStatusTxt           string `xml:"SubmissionStatusTxt"`
	SubmsnStatusAcknowledgementDt string `xml:"SubmsnStatusAcknowledgementDt"`
	DisclaimerTxt                 string `xml:"DisclaimerTxt,omitempty"`
}

// StatusRecordList ...
type StatusRecordList struct {
	Cnt             int                `xml:"Cnt"`
	StatusRecordGrp []*StatusRecordGrp `xml:"StatusRecordGrp,omitempty"`
}

// AckNotification ...
type AckNotification struct {
	SubmissionId string `xml:"SubmissionId"`
	Ts           string `xml:"Ts"`
}

// AckNotificationList ...
type AckNotificationList struct {
	Cnt             int                `xml:"Cnt"`
	AckNotification []*AckNotification `xml:"AckNotification,omitempty"`
}

// CommonSubmissionAndAcknowledgementElements ...
type CommonSubmissionAndAcknowledgementElements struct {
	SubmissionId string
	EFIN         string
}

// ValidationErrorGrp ...
type ValidationErrorGrp struct {
	ErrorIdAttr     int    `xml:"errorId,attr"`
	DocumentId      string `xml:"DocumentId"`
	XpathContentTxt string `xml:"XpathContentTxt,omitempty"`
	ErrorCategoryCd string `xml:"ErrorCategoryCd"`
	ErrorMessageTxt string `xml:"ErrorMessageTxt"`
	RuleNum         string `xml:"RuleNum"`
	SeverityCd      string `xml:"SeverityCd"`
	FieldValueTxt   string `xml:"FieldValueTxt,omitempty"`
}

// ValidationErrorListType ...
type ValidationErrorListType struct {
	ErrorCntAttr       int                   `xml:"errorCnt,attr"`
	ValidationErrorGrp []*ValidationErrorGrp `xml:"ValidationErrorGrp"`
}

// ValidationAlertGrp ...
type ValidationAlertGrp struct {
	AlertIdAttr     int    `xml:"alertId,attr"`
	DocumentId      string `xml:"DocumentId"`
	XpathContentTxt string `xml:"XpathContentTxt,omitempty"`
	AlertCategoryCd string `xml:"AlertCategoryCd"`
	AlertMessageTxt string `xml:"AlertMessageTxt"`
	RuleNum         string `xml:"RuleNum"`
	SeverityCd      string `xml:"SeverityCd"`
	FieldValueTxt   string `xml:"FieldValueTxt,omitempty"`
}

// ValidationAlertListType ...
type ValidationAlertListType struct {
	AlertCntAttr       int                   `xml:"alertCnt,attr"`
	ValidationAlertGrp []*ValidationAlertGrp `xml:"ValidationAlertGrp"`
}

// ReceiptIdType ...
type ReceiptIdType string

// TempIdType ...
type TempIdType string

// SubmissionCategoryType ...
type SubmissionCategoryType string

// UnknownCodeType ...
type UnknownCodeType string

// ExtndSubmissionCategoryCdType ...
type ExtndSubmissionCategoryCdType struct {
	UnknownCodeType        string
	SubmissionCategoryType string
}

// ExtndGovernmentCdType ...
type ExtndGovernmentCdType struct {
	UnknownCodeType    string
	GovernmentCodeType string
}
