// Code generated by xgen. DO NOT EDIT.

package irsform

// SubmissionDataType ...
type SubmissionDataType struct {
	SubmissionId         string `xml:"SubmissionId"`
	ElectronicPostmarkTs string `xml:"ElectronicPostmarkTs"`
}

// SubmissionDataListType ...
type SubmissionDataListType struct {
	Cnt            int                   `xml:"Cnt"`
	SubmissionData []*SubmissionDataType `xml:"SubmissionData"`
}

// TransmissionManifest ...
type TransmissionManifest struct {
	SubmissionDataList *SubmissionDataListType `xml:"SubmissionDataList"`
}
