// Code generated by xgen. DO NOT EDIT.

package irsform

// EmployeeCompensationExpln is Common return document attributes
type EmployeeCompensationExpln struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*EmployeeCompensationExplnType
}

// EmployeeCompExplanationGrp is Explanation
type EmployeeCompExplanationGrp struct {
	EmployeeNm     string `xml:"EmployeeNm,omitempty"`
	ExplanationTxt string `xml:"ExplanationTxt,omitempty"`
}

// EmployeeCompensationExplnType is Content model for employee compensation explanation
type EmployeeCompensationExplnType struct {
	EmployeeCompExplanationGrp []*EmployeeCompExplanationGrp `xml:"EmployeeCompExplanationGrp,omitempty"`
}
