// Code generated by xgen. DO NOT EDIT.

package irsform

// ExpenditureResponsibilityStmt is Common return document attributes
type ExpenditureResponsibilityStmt struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*ExpenditureResponsibilityStmtType
}

// ExpenditureResponsibilityGrp is Results of Verification
type ExpenditureResponsibilityGrp struct {
	BusinessName               *BusinessNameType   `xml:"BusinessName"`
	PersonNm                   string              `xml:"PersonNm"`
	USAddress                  *USAddressType      `xml:"USAddress"`
	ForeignAddress             *ForeignAddressType `xml:"ForeignAddress"`
	GrantDt                    string              `xml:"GrantDt,omitempty"`
	GrantAmt                   int                 `xml:"GrantAmt,omitempty"`
	PurposeOfGrantTxt          string              `xml:"PurposeOfGrantTxt,omitempty"`
	ExpendedByGranteeAmt       int                 `xml:"ExpendedByGranteeAmt,omitempty"`
	AnyDiversionByGranteeTxt   string              `xml:"AnyDiversionByGranteeTxt,omitempty"`
	DatesOfReportsByGranteeTxt string              `xml:"DatesOfReportsByGranteeTxt,omitempty"`
	VerificationDt             string              `xml:"VerificationDt,omitempty"`
	ResultsOfVerificationTxt   string              `xml:"ResultsOfVerificationTxt,omitempty"`
}

// ExpenditureResponsibilityStmtType is Content model for Expenditure Responsibility Statement
type ExpenditureResponsibilityStmtType struct {
	ExpenditureResponsibilityGrp []*ExpenditureResponsibilityGrp `xml:"ExpenditureResponsibilityGrp,omitempty"`
}
