// Code generated by xgen. DO NOT EDIT.

package irsform

// ExplnOfNonFilingWithAGStmt is Common return document attributes
type ExplnOfNonFilingWithAGStmt struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*ExplnOfNonFilingWithAGStmtType
}

// ExplnOfNonFilingWithAGStmtType is Content model for Explanation of Non-Filing with Attorney General Statement
type ExplnOfNonFilingWithAGStmtType struct {
	ExplanationTxt string `xml:"ExplanationTxt,omitempty"`
}
