// Code generated by xgen. DO NOT EDIT.

package irsform

// ExplanOfLegisPoliticalActvts is Common return document attributes
type ExplanOfLegisPoliticalActvts struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*ExplanationOfLegisPoliticalActivitiesType
}

// ExplanationOfLegisPoliticalActivitiesType is Content model for Explanation of Legislative Political Activities Attachment
type ExplanationOfLegisPoliticalActivitiesType struct {
	MediumExplanationTxt string `xml:"MediumExplanationTxt,omitempty"`
}
