// Code generated by xgen. DO NOT EDIT.

package irsform

// GainLossSaleOtherAssetsSch is Common return document attributes
type GainLossSaleOtherAssetsSch struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*GainLossSaleOtherAssetsSchType
}

// GainLossSaleOtherAssetsSchType is Content model for gain/loss from sale of other assets schedule
type GainLossSaleOtherAssetsSchType struct {
	GainLossSaleOtherAssetGrp []*GainLossSaleOtherAssetGrpType `xml:"GainLossSaleOtherAssetGrp,omitempty"`
}

// PurchaserNameGrp is Purchaser Name
type PurchaserNameGrp struct {
	PersonNm     string            `xml:"PersonNm"`
	BusinessName *BusinessNameType `xml:"BusinessName"`
}

// GainLossSaleOtherAssetGrpType is DateSold
type GainLossSaleOtherAssetGrpType struct {
	AssetDesc                  string            `xml:"AssetDesc,omitempty"`
	AcquiredDt                 string            `xml:"AcquiredDt,omitempty"`
	HowAcquiredTxt             string            `xml:"HowAcquiredTxt,omitempty"`
	SoldDt                     string            `xml:"SoldDt,omitempty"`
	PurchaserNameGrp           *PurchaserNameGrp `xml:"PurchaserNameGrp,omitempty"`
	GrossSalesPriceAmt         int               `xml:"GrossSalesPriceAmt,omitempty"`
	BasisAmt                   int               `xml:"BasisAmt,omitempty"`
	BasisMethodTxt             string            `xml:"BasisMethodTxt,omitempty"`
	SalesExpenseAmt            int               `xml:"SalesExpenseAmt,omitempty"`
	TotalNetAmt                int               `xml:"TotalNetAmt,omitempty"`
	AccumulatedDepreciationAmt int               `xml:"AccumulatedDepreciationAmt,omitempty"`
}
