// Code generated by xgen. DO NOT EDIT.

package irsform

// GeneralExplanationAttachment is Common return document attributes
type GeneralExplanationAttachment struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*GenExplanationAttachmentType
}

// GenExplanationAttachmentType is Content model for general explanation attachment
type GenExplanationAttachmentType struct {
	GeneralExplanationGrp []*GeneralExplanationGrpType `xml:"GeneralExplanationGrp,omitempty"`
}

// GeneralExplanationGrpType is Explanation
type GeneralExplanationGrpType struct {
	IdentifierTxt            string `xml:"IdentifierTxt,omitempty"`
	FormAndLineReferenceDesc string `xml:"FormAndLineReferenceDesc,omitempty"`
	MediumExplanationTxt     string `xml:"MediumExplanationTxt,omitempty"`
}
