// Code generated by xgen. DO NOT EDIT.

package irsform

// InvestmentsLandSchedule2 is Common return document attributes
type InvestmentsLandSchedule2 struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*InvestmentsLandSchedule2Type
}

// InvestmentLandGrp is End of Year Fair Market Value
type InvestmentLandGrp struct {
	CategoryOrItemTxt          string `xml:"CategoryOrItemTxt,omitempty"`
	CostOrOtherBasisAmt        int    `xml:"CostOrOtherBasisAmt,omitempty"`
	AccumulatedDepreciationAmt int    `xml:"AccumulatedDepreciationAmt,omitempty"`
	BookValueAmt               int    `xml:"BookValueAmt,omitempty"`
	EOYFMVAmt                  int    `xml:"EOYFMVAmt,omitempty"`
}

// InvestmentsLandSchedule2Type is Content model for investments - land schedule
type InvestmentsLandSchedule2Type struct {
	InvestmentLandGrp []*InvestmentLandGrp `xml:"InvestmentLandGrp,omitempty"`
}
