// Code generated by xgen. DO NOT EDIT.

package irsform

// InvestmentsCorpBondsSchedule is Common return document attributes
type InvestmentsCorpBondsSchedule struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*InvestmentsCorpBondsScheduleType
}

// InvestmentsCorporateBondsGrp is End of Year Fair Market Value
type InvestmentsCorporateBondsGrp struct {
	BondNm          string `xml:"BondNm,omitempty"`
	EOYBookValueAmt int    `xml:"EOYBookValueAmt,omitempty"`
	EOYFMVAmt       int    `xml:"EOYFMVAmt,omitempty"`
}

// InvestmentsCorpBondsScheduleType is Content model for Investments Corporate Bonds Schedule
type InvestmentsCorpBondsScheduleType struct {
	InvestmentsCorporateBondsGrp []*InvestmentsCorporateBondsGrp `xml:"InvestmentsCorporateBondsGrp,omitempty"`
}
