// Code generated by xgen. DO NOT EDIT.

package irsform

// InvestmentsOtherSchedule2 is Common return document attributes
type InvestmentsOtherSchedule2 struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*InvestmentsOtherSchedule2Type
}

// InvestmentsOtherGrp is Category/ Item
type InvestmentsOtherGrp struct {
	CategoryOrItemTxt   string      `xml:"CategoryOrItemTxt,omitempty"`
	ListedAtCostOrFMVCd interface{} `xml:"ListedAtCostOrFMVCd,omitempty"`
	BookValueAmt        int         `xml:"BookValueAmt,omitempty"`
	EOYFMVAmt           int         `xml:"EOYFMVAmt,omitempty"`
}

// InvestmentsOtherSchedule2Type is Content model for investments - other schedule
type InvestmentsOtherSchedule2Type struct {
	InvestmentsOtherGrp []*InvestmentsOtherGrp `xml:"InvestmentsOtherGrp,omitempty"`
}
