// Code generated by xgen. DO NOT EDIT.

package irsform

// InvestmentsGovtObligationsSch is Common return document attributes
type InvestmentsGovtObligationsSch struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*InvestmentsGovtObligationsSchType
}

// InvestmentsGovtObligationsSchType is State & Local Government Securities - End of Year Fair Market Value
type InvestmentsGovtObligationsSchType struct {
	USGovtObligationsBookVlEOYAmt int `xml:"USGovtObligationsBookVlEOYAmt,omitempty"`
	USGovtObligationsEOYFMVAmt    int `xml:"USGovtObligationsEOYFMVAmt,omitempty"`
	StateLocalSecBookVlEOYAmt     int `xml:"StateLocalSecBookVlEOYAmt,omitempty"`
	StateLocalSecEOYFMVAmt        int `xml:"StateLocalSecEOYFMVAmt,omitempty"`
}
