// Code generated by xgen. DO NOT EDIT.

package irsform

// InvestmentsCorpStockSchedule is Common return document attributes
type InvestmentsCorpStockSchedule struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*InvestmentsCorpStockScheduleType
}

// InvestmentsCorporateStockGrp is End of Year Fair Market Value
type InvestmentsCorporateStockGrp struct {
	StockNm         string `xml:"StockNm,omitempty"`
	EOYBookValueAmt int    `xml:"EOYBookValueAmt,omitempty"`
	EOYFMVAmt       int    `xml:"EOYFMVAmt,omitempty"`
}

// InvestmentsCorpStockScheduleType is Content model for Investments Corporate Stock Schedule
type InvestmentsCorpStockScheduleType struct {
	InvestmentsCorporateStockGrp []*InvestmentsCorporateStockGrp `xml:"InvestmentsCorporateStockGrp,omitempty"`
}
