// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990EZ is Common return document attributes
type IRS990EZ struct {
	DocumentAttributes                *DocumentAttributes
	DocumentNameAttr                  string      `xml:"documentName,attr,omitempty"`
	ReferenceDocumentIdAttr           *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr         string      `xml:"referenceDocumentName,attr,omitempty"`
	AccountingPeriodChangeCdAttr      string      `xml:"accountingPeriodChangeCd,attr,omitempty"`
	AccountingPeriodChangeApprvCdAttr string      `xml:"accountingPeriodChangeApprvCd,attr,omitempty"`
	*IRS990EZType
}

// Organization501c3Ind is J
type Organization501c3Ind struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     string      `xml:",chardata"`
}


// Organization4947a1NotPFInd is J
type Organization4947a1NotPFInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     string      `xml:",chardata"`
}

// GamingGrossIncomeAmt is Part I Line 6a
type GamingGrossIncomeAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// FundraisingGrossIncomeAmt is Part I Line 6b
type FundraisingGrossIncomeAmt struct {
	FndrsngEventContriPrevRptAmtAttr int         `xml:"fndrsngEventContriPrevRptAmt,attr,omitempty"`
	ReferenceDocumentIdAttr          *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr        string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                            int         `xml:",chardata"`
}

// NetAssetsOrFundBalancesGrp is Part II Line 27
type NetAssetsOrFundBalancesGrp struct {
	BOYAmt int `xml:"BOYAmt"`
	EOYAmt int `xml:"EOYAmt"`
}



// LoansToFromOfficersAmt is Part V Line 38b
type LoansToFromOfficersAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}



// NECTFilingForm990Ind is Part V Line 43
type NECTFilingForm990Ind struct {
	InterestAmtAttr int    `xml:"interestAmt,attr,omitempty"`
	Value           string `xml:",chardata"`
}




// IRS990EZType is Content model for Form 990-EZ
type IRS990EZType struct {
	SpecialConditionDesc           []interface{}                         `xml:"SpecialConditionDesc,omitempty"`
	AddressChangeInd               string                                `xml:"AddressChangeInd,omitempty"`
	NameChangeInd                  string                                `xml:"NameChangeInd,omitempty"`
	InitialReturnInd               string                                `xml:"InitialReturnInd,omitempty"`
	FinalReturnInd                 string                                `xml:"FinalReturnInd,omitempty"`
	AmendedReturnInd               string                                `xml:"AmendedReturnInd,omitempty"`
	ApplicationPendingInd          string                                `xml:"ApplicationPendingInd,omitempty"`
	GroupExemptionNum              interface{}                           `xml:"GroupExemptionNum,omitempty"`
	MethodOfAccountingCashInd      string                                `xml:"MethodOfAccountingCashInd,omitempty"`
	MethodOfAccountingAccrualInd   string                                `xml:"MethodOfAccountingAccrualInd,omitempty"`
	MethodOfAccountingOtherDesc    string                                `xml:"MethodOfAccountingOtherDesc,omitempty"`
	ScheduleBNotRequiredInd        string                                `xml:"ScheduleBNotRequiredInd,omitempty"`
	WebsiteAddressTxt              string                                `xml:"WebsiteAddressTxt,omitempty"`
	Organization501c3Ind           *Organization501c3Ind                 `xml:"Organization501c3Ind"`
	Organization501cInd            *Organization501cInd                  `xml:"Organization501cInd"`
	Organization4947a1NotPFInd     *Organization4947a1NotPFInd           `xml:"Organization4947a1NotPFInd"`
	Organization527Ind             string                                `xml:"Organization527Ind"`
	TypeOfOrganizationCorpInd      string                                `xml:"TypeOfOrganizationCorpInd,omitempty"`
	TypeOfOrganizationTrustInd     string                                `xml:"TypeOfOrganizationTrustInd,omitempty"`
	TypeOfOrganizationAssocInd     string                                `xml:"TypeOfOrganizationAssocInd,omitempty"`
	TypeOfOrganizationOtherInd     string                                `xml:"TypeOfOrganizationOtherInd,omitempty"`
	TypeOfOrganizationOtherDesc    string                                `xml:"TypeOfOrganizationOtherDesc,omitempty"`
	GrossReceiptsAmt               int                                   `xml:"GrossReceiptsAmt,omitempty"`
	InfoInScheduleOPartIInd        string                                `xml:"InfoInScheduleOPartIInd,omitempty"`
	ContributionsGiftsGrantsEtcAmt int                                   `xml:"ContributionsGiftsGrantsEtcAmt,omitempty"`
	ProgramServiceRevenueAmt       int                                   `xml:"ProgramServiceRevenueAmt,omitempty"`
	MembershipDuesAmt              int                                   `xml:"MembershipDuesAmt,omitempty"`
	InvestmentIncomeAmt            int                                   `xml:"InvestmentIncomeAmt,omitempty"`
	SaleOfAssetsGrossAmt           int                                   `xml:"SaleOfAssetsGrossAmt,omitempty"`
	CostOrOtherBasisExpenseSaleAmt int                                   `xml:"CostOrOtherBasisExpenseSaleAmt,omitempty"`
	GainOrLossFromSaleOfAssetsAmt  int                                   `xml:"GainOrLossFromSaleOfAssetsAmt,omitempty"`
	GamingGrossIncomeAmt           *GamingGrossIncomeAmt                 `xml:"GamingGrossIncomeAmt,omitempty"`
	FundraisingGrossIncomeAmt      *FundraisingGrossIncomeAmt            `xml:"FundraisingGrossIncomeAmt,omitempty"`
	SpecialEventsDirectExpensesAmt int                                   `xml:"SpecialEventsDirectExpensesAmt,omitempty"`
	SpecialEventsNetIncomeLossAmt  int                                   `xml:"SpecialEventsNetIncomeLossAmt,omitempty"`
	GrossSalesOfInventoryAmt       int                                   `xml:"GrossSalesOfInventoryAmt,omitempty"`
	CostOfGoodsSoldAmt             int                                   `xml:"CostOfGoodsSoldAmt,omitempty"`
	GrossProfitLossSlsOfInvntryAmt int                                   `xml:"GrossProfitLossSlsOfInvntryAmt,omitempty"`
	OtherRevenueTotalAmt           int                                   `xml:"OtherRevenueTotalAmt,omitempty"`
	TotalRevenueAmt                int                                   `xml:"TotalRevenueAmt,omitempty"`
	GrantsAndSimilarAmountsPaidAmt int                                   `xml:"GrantsAndSimilarAmountsPaidAmt,omitempty"`
	BenefitsPaidToOrForMembersAmt  int                                   `xml:"BenefitsPaidToOrForMembersAmt,omitempty"`
	SalariesOtherCompEmplBnftAmt   int                                   `xml:"SalariesOtherCompEmplBnftAmt,omitempty"`
	FeesAndOtherPymtToIndCntrctAmt int                                   `xml:"FeesAndOtherPymtToIndCntrctAmt,omitempty"`
	OccupancyRentUtltsAndMaintAmt  int                                   `xml:"OccupancyRentUtltsAndMaintAmt,omitempty"`
	PrintingPublicationsPostageAmt int                                   `xml:"PrintingPublicationsPostageAmt,omitempty"`
	OtherExpensesTotalAmt          int                                   `xml:"OtherExpensesTotalAmt,omitempty"`
	TotalExpensesAmt               int                                   `xml:"TotalExpensesAmt,omitempty"`
	ExcessOrDeficitForYearAmt      int                                   `xml:"ExcessOrDeficitForYearAmt,omitempty"`
	NetAssetsOrFundBalancesBOYAmt  int                                   `xml:"NetAssetsOrFundBalancesBOYAmt,omitempty"`
	OtherChangesInNetAssetsAmt     int                                   `xml:"OtherChangesInNetAssetsAmt,omitempty"`
	NetAssetsOrFundBalancesEOYAmt  int                                   `xml:"NetAssetsOrFundBalancesEOYAmt,omitempty"`
	InfoInScheduleOPartIIInd       string                                `xml:"InfoInScheduleOPartIIInd,omitempty"`
	CashSavingsAndInvestmentsGrp   *Form990EZPartIIType                  `xml:"CashSavingsAndInvestmentsGrp,omitempty"`
	LandAndBuildingsGrp            *Form990EZPartIIType                  `xml:"LandAndBuildingsGrp,omitempty"`
	OtherAssetsTotalDetail         *Form990EZPartIIType                  `xml:"OtherAssetsTotalDetail,omitempty"`
	Form990TotalAssetsGrp          *Form990EZPartIIGroup2Type            `xml:"Form990TotalAssetsGrp"`
	SumOfTotalLiabilitiesGrp       *Form990EZPartIIType                  `xml:"SumOfTotalLiabilitiesGrp,omitempty"`
	NetAssetsOrFundBalancesGrp     *NetAssetsOrFundBalancesGrp           `xml:"NetAssetsOrFundBalancesGrp"`
	InfoInScheduleOPartIIIInd      string                                `xml:"InfoInScheduleOPartIIIInd,omitempty"`
	PrimaryExemptPurposeTxt        string                                `xml:"PrimaryExemptPurposeTxt"`
	ProgramSrvcAccomplishmentGrp   []*Form990EZPartIIIType               `xml:"ProgramSrvcAccomplishmentGrp"`
	TotalProgramServiceExpensesAmt int                                   `xml:"TotalProgramServiceExpensesAmt,omitempty"`
	InfoInScheduleOPartIVInd       string                                `xml:"InfoInScheduleOPartIVInd,omitempty"`
	OfficerDirectorTrusteeEmplGrp  []*Form990EZPartIVType                `xml:"OfficerDirectorTrusteeEmplGrp"`
	InfoInScheduleOPartVInd        string                                `xml:"InfoInScheduleOPartVInd,omitempty"`
	ActivitiesNotPreviouslyRptInd  bool                                  `xml:"ActivitiesNotPreviouslyRptInd"`
	ChgMadeToOrgnzngDocNotRptInd   bool                                  `xml:"ChgMadeToOrgnzngDocNotRptInd"`
	OrganizationHadUBIInd          bool                                  `xml:"OrganizationHadUBIInd,omitempty"`
	OrganizationFiled990TInd       bool                                  `xml:"OrganizationFiled990TInd,omitempty"`
	SubjectToProxyTaxInd           *SubjectToProxyTaxInd                 `xml:"SubjectToProxyTaxInd"`
	OrganizationDissolvedEtcInd    *OrganizationDissolvedEtcInd          `xml:"OrganizationDissolvedEtcInd"`
	DirectIndirectPltclExpendAmt   int                                   `xml:"DirectIndirectPltclExpendAmt,omitempty"`
	Form1120PolFiledInd            bool                                  `xml:"Form1120PolFiledInd,omitempty"`
	MadeLoansToFromOfficersInd     bool                                  `xml:"MadeLoansToFromOfficersInd"`
	LoansToFromOfficersAmt         *LoansToFromOfficersAmt               `xml:"LoansToFromOfficersAmt,omitempty"`
	InitiationFeesAndCapContriAmt  int                                   `xml:"InitiationFeesAndCapContriAmt,omitempty"`
	GrossReceiptsForPublicUseAmt   int                                   `xml:"GrossReceiptsForPublicUseAmt,omitempty"`
	TaxImposedUnderIRC4911Amt      int                                   `xml:"TaxImposedUnderIRC4911Amt,omitempty"`
	TaxImposedUnderIRC4912Amt      int                                   `xml:"TaxImposedUnderIRC4912Amt,omitempty"`
	TaxImposedUnderIRC4955Amt      int                                   `xml:"TaxImposedUnderIRC4955Amt,omitempty"`
	EngagedInExcessBenefitTransInd *EngagedInExcessBenefitTransInd       `xml:"EngagedInExcessBenefitTransInd,omitempty"`
	TaxImposedOnOrganizationMgrAmt int                                   `xml:"TaxImposedOnOrganizationMgrAmt,omitempty"`
	TaxReimbursedByOrganizationAmt int                                   `xml:"TaxReimbursedByOrganizationAmt,omitempty"`
	ProhibitedTaxShelterTransInd   bool                                  `xml:"ProhibitedTaxShelterTransInd,omitempty"`
	StatesWhereCopyOfReturnIsFldCd []string                              `xml:"StatesWhereCopyOfReturnIsFldCd,omitempty"`
	BooksInCareOfDetail            *BooksInCareOfDetail                  `xml:"BooksInCareOfDetail"`
	ForeignFinancialAccountInd     bool                                  `xml:"ForeignFinancialAccountInd,omitempty"`
	ForeignFinancialAccountCntryCd []string                              `xml:"ForeignFinancialAccountCntryCd,omitempty"`
	ForeignOfficeInd               bool                                  `xml:"ForeignOfficeInd,omitempty"`
	ForeignOfficeCountryCd         []string                              `xml:"ForeignOfficeCountryCd,omitempty"`
	NECTFilingForm990Ind           *NECTFilingForm990Ind                 `xml:"NECTFilingForm990Ind,omitempty"`
	DonorAdvisedFndsInd            bool                                  `xml:"DonorAdvisedFndsInd"`
	OperateHospitalInd             bool                                  `xml:"OperateHospitalInd"`
	TanningServicesProvidedInd     bool                                  `xml:"TanningServicesProvidedInd"`
	Form720FiledInd                bool                                  `xml:"Form720FiledInd,omitempty"`
	RelatedOrganizationCtrlEntInd  bool                                  `xml:"RelatedOrganizationCtrlEntInd"`
	TransactionWithControlEntInd   bool                                  `xml:"TransactionWithControlEntInd,omitempty"`
	PoliticalCampaignActyInd       *PoliticalCampaignActyInd             `xml:"PoliticalCampaignActyInd,omitempty"`
	InfoInScheduleOPartVIInd       string                                `xml:"InfoInScheduleOPartVIInd,omitempty"`
	LobbyingActivitiesInd          *LobbyingActivitiesInd                `xml:"LobbyingActivitiesInd,omitempty"`
	SchoolOperatingInd             *SchoolOperatingInd                   `xml:"SchoolOperatingInd,omitempty"`
	TrnsfrExmptNonChrtblRltdOrgInd bool                                  `xml:"TrnsfrExmptNonChrtblRltdOrgInd,omitempty"`
	RelatedOrgSect527OrgInd        bool                                  `xml:"RelatedOrgSect527OrgInd,omitempty"`
	CompensationHighestPaidEmplGrp []*CompensationHighestPaidEmplGrpType `xml:"CompensationHighestPaidEmplGrp,omitempty"`
	PartVIOfCompOfHghstPdEmplTxt   interface{}                           `xml:"PartVIOfCompOfHghstPdEmplTxt"`
	OtherEmployeePaidOver100kCnt   interface{}                           `xml:"OtherEmployeePaidOver100kCnt,omitempty"`
	CompensationOfHghstPdCntrctGrp []*CompensationOfHghstPdCntrctGrpType `xml:"CompensationOfHghstPdCntrctGrp,omitempty"`
	PartVIHghstPdCntrctProfSrvcTxt interface{}                           `xml:"PartVIHghstPdCntrctProfSrvcTxt"`
	CntrctRcvdGreaterThan100KCnt   interface{}                           `xml:"CntrctRcvdGreaterThan100KCnt,omitempty"`
	FiledScheduleAInd              bool                                  `xml:"FiledScheduleAInd,omitempty"`
}

// Form990EZPartIIType is Part II - Column (B)
type Form990EZPartIIType struct {
	BOYAmt int `xml:"BOYAmt,omitempty"`
	EOYAmt int `xml:"EOYAmt,omitempty"`
}

// Form990EZPartIIGroup2Type is Part II - Column (B)
type Form990EZPartIIGroup2Type struct {
	BOYAmt int `xml:"BOYAmt"`
	EOYAmt int `xml:"EOYAmt"`
}

// Form990EZPartIIIType is Part III
type Form990EZPartIIIType struct {
	DescriptionProgramSrvcAccomTxt string `xml:"DescriptionProgramSrvcAccomTxt"`
	GrantsAndAllocationsAmt        int    `xml:"GrantsAndAllocationsAmt,omitempty"`
	ForeignGrantsInd               string `xml:"ForeignGrantsInd,omitempty"`
	ProgramServiceExpensesAmt      int    `xml:"ProgramServiceExpensesAmt,omitempty"`
}



// Form990EZPartIVType ...
type Form990EZPartIVType struct {
	PersonNm                      *PersonNm     `xml:"PersonNm"`
	BusinessName                  *BusinessName `xml:"BusinessName"`
	TitleTxt                      string        `xml:"TitleTxt"`
	AverageHrsPerWkDevotedToPosRt interface{}   `xml:"AverageHrsPerWkDevotedToPosRt"`
	CompensationAmt               int           `xml:"CompensationAmt,omitempty"`
	EmployeeBenefitProgramAmt     int           `xml:"EmployeeBenefitProgramAmt,omitempty"`
	ExpenseAccountOtherAllwncAmt  int           `xml:"ExpenseAccountOtherAllwncAmt,omitempty"`
}

// CompensationHighestPaidEmplGrpType ...
type CompensationHighestPaidEmplGrpType struct {
	PersonNm              *PersonNm   `xml:"PersonNm"`
	TitleTxt              string      `xml:"TitleTxt"`
	AverageHoursPerWeekRt interface{} `xml:"AverageHoursPerWeekRt"`
	CompensationAmt       int         `xml:"CompensationAmt"`
	EmployeeBenefitsAmt   int         `xml:"EmployeeBenefitsAmt,omitempty"`
	ExpenseAccountAmt     int         `xml:"ExpenseAccountAmt,omitempty"`
}

// CompensationOfHghstPdCntrctGrpType ...
type CompensationOfHghstPdCntrctGrpType struct {
	BusinessName    *BusinessName       `xml:"BusinessName"`
	PersonNm        *PersonNm           `xml:"PersonNm"`
	USAddress       *USAddressType      `xml:"USAddress"`
	ForeignAddress  *ForeignAddressType `xml:"ForeignAddress"`
	ServiceTypeTxt  string              `xml:"ServiceTypeTxt"`
	CompensationAmt int                 `xml:"CompensationAmt"`
}
