// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990ScheduleA is Common return document attributes
type IRS990ScheduleA struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*IRS990ScheduleAType
}

// Form990SchASupportingOrgGrp is Part IV Section A Line 11c
type Form990SchASupportingOrgGrp struct {
	ListedByNameGoverningDocInd    bool `xml:"ListedByNameGoverningDocInd"`
	SuprtOrgNoIRSDeterminationInd  bool `xml:"SuprtOrgNoIRSDeterminationInd"`
	SupportedOrgSectionC456Ind     bool `xml:"SupportedOrgSectionC456Ind"`
	SupportedOrgQualifiedInd       bool `xml:"SupportedOrgQualifiedInd,omitempty"`
	SuprtExclusivelySec170c2BInd   bool `xml:"SuprtExclusivelySec170c2BInd,omitempty"`
	SupportedOrgNotOrganizedUSInd  bool `xml:"SupportedOrgNotOrganizedUSInd"`
	ControlDecidingGrntFrgnOrgInd  bool `xml:"ControlDecidingGrntFrgnOrgInd,omitempty"`
	SupportForeignOrgNoDetermInd   bool `xml:"SupportForeignOrgNoDetermInd,omitempty"`
	OrganizationChangeSuprtOrgInd  bool `xml:"OrganizationChangeSuprtOrgInd"`
	SupportedOrgClassDesignatedInd bool `xml:"SupportedOrgClassDesignatedInd,omitempty"`
	SubstitutionBeyondOrgCntlInd   bool `xml:"SubstitutionBeyondOrgCntlInd,omitempty"`
	SupportNonSupportedOrgInd      bool `xml:"SupportNonSupportedOrgInd"`
	PaymentSubstantialContribtrInd bool `xml:"PaymentSubstantialContribtrInd"`
	LoanDisqualifiedPersonInd      bool `xml:"LoanDisqualifiedPersonInd"`
	ControlledDisqualifiedPrsnInd  bool `xml:"ControlledDisqualifiedPrsnInd"`
	DisqualifiedPrsnControllIntInd bool `xml:"DisqualifiedPrsnControllIntInd"`
	DisqualifiedPrsnOwnrIntInd     bool `xml:"DisqualifiedPrsnOwnrIntInd"`
	ExcessBusinessHoldingsRulesInd bool `xml:"ExcessBusinessHoldingsRulesInd"`
	ExcessBusinessHoldingsInd      bool `xml:"ExcessBusinessHoldingsInd,omitempty"`
	ContributionControllerInd      bool `xml:"ContributionControllerInd"`
	ContributionFamilyInd          bool `xml:"ContributionFamilyInd"`
	Contribution35ControlledInd    bool `xml:"Contribution35ControlledInd"`
}

// Form990SchAType1SuprtOrgGrp is Part IV Section B Group
type Form990SchAType1SuprtOrgGrp struct {
	PowerAppointMajorityDirTrstInd bool `xml:"PowerAppointMajorityDirTrstInd"`
	OperateBenefitNonSuprtOrgInd   bool `xml:"OperateBenefitNonSuprtOrgInd"`
}

// Form990SchAType3SprtOrgAllGrp is Part IV Section D Group
type Form990SchAType3SprtOrgAllGrp struct {
	TimelyProvidedDocumentsInd     bool `xml:"TimelyProvidedDocumentsInd"`
	OfficersCloseRelationshipInd   bool `xml:"OfficersCloseRelationshipInd"`
	SupportedOrgVoiceInvestmentInd bool `xml:"SupportedOrgVoiceInvestmentInd"`
}

// Form990SchAType3FuncIntGrp is Part IV Section E Group
type Form990SchAType3FuncIntGrp struct {
	ActivitiesTestInd              string `xml:"ActivitiesTestInd,omitempty"`
	ParentSupportedOrgInd          string `xml:"ParentSupportedOrgInd,omitempty"`
	GovernmentalEntityInd          string `xml:"GovernmentalEntityInd,omitempty"`
	ActivitiesFurtherExemptPrpsInd bool   `xml:"ActivitiesFurtherExemptPrpsInd,omitempty"`
	ActivitiesEngagedOrgInvlmntInd bool   `xml:"ActivitiesEngagedOrgInvlmntInd,omitempty"`
	AppointElectMajorityOfficerInd bool   `xml:"AppointElectMajorityOfficerInd,omitempty"`
	ExerciseDirectionPoliciesInd   bool   `xml:"ExerciseDirectionPoliciesInd,omitempty"`
}

// AdjustedNetIncomeGrp is Part V Section A Group
type AdjustedNetIncomeGrp struct {
	NetSTCapitalGainAdjNetIncmGrp *Form990SchAPartVGroup1Type `xml:"NetSTCapitalGainAdjNetIncmGrp"`
	RecoveriesPYDistributionsGrp  *Form990SchAPartVGroup1Type `xml:"RecoveriesPYDistributionsGrp"`
	OtherGrossIncomeGrp           *Form990SchAPartVGroup1Type `xml:"OtherGrossIncomeGrp"`
	AdjustedGrossIncomeGrp        *Form990SchAPartVGroup1Type `xml:"AdjustedGrossIncomeGrp"`
	DepreciationDepletionGrp      *Form990SchAPartVGroup1Type `xml:"DepreciationDepletionGrp"`
	ProductionIncomeGrp           *Form990SchAPartVGroup1Type `xml:"ProductionIncomeGrp"`
	OtherExpensesGrp              *Form990SchAPartVGroup1Type `xml:"OtherExpensesGrp"`
	TotalAdjustedNetIncomeGrp     *Form990SchAPartVGroup2Type `xml:"TotalAdjustedNetIncomeGrp"`
}

// MinimumAssetAmountGrp is Part V Section B Group
type MinimumAssetAmountGrp struct {
	AverageMonthlyFMVOfSecGrp      *Form990SchAPartVGroup2Type `xml:"AverageMonthlyFMVOfSecGrp"`
	AverageMonthlyCashBalancesGrp  *Form990SchAPartVGroup2Type `xml:"AverageMonthlyCashBalancesGrp"`
	FMVOtherNonExemptUseAssetGrp   *Form990SchAPartVGroup2Type `xml:"FMVOtherNonExemptUseAssetGrp"`
	TotalFMVOfNonExemptUseAssetGrp *Form990SchAPartVGroup2Type `xml:"TotalFMVOfNonExemptUseAssetGrp"`
	DiscountClaimedAmt             int                         `xml:"DiscountClaimedAmt"`
	AcquisitionIndebtednessGrp     *Form990SchAPartVGroup1Type `xml:"AcquisitionIndebtednessGrp"`
	AdjustedFMVLessIndebtednessGrp *Form990SchAPartVGroup1Type `xml:"AdjustedFMVLessIndebtednessGrp"`
	CashDeemedCharitableGrp        *Form990SchAPartVGroup1Type `xml:"CashDeemedCharitableGrp"`
	NetVlNonExemptUseAssetsGrp     *Form990SchAPartVGroup1Type `xml:"NetVlNonExemptUseAssetsGrp"`
	PctOfNetVlNonExemptUseAstGrp   *Form990SchAPartVGroup1Type `xml:"PctOfNetVlNonExemptUseAstGrp"`
	RecoveriesPYDistriMinAssetGrp  *Form990SchAPartVGroup1Type `xml:"RecoveriesPYDistriMinAssetGrp"`
	TotalMinimumAssetGrp           *Form990SchAPartVGroup1Type `xml:"TotalMinimumAssetGrp"`
}

// DistributionsGrp is Part V Section D Group
type DistributionsGrp struct {
	CYPaidAccomplishExemptPrpsAmt  int         `xml:"CYPaidAccomplishExemptPrpsAmt"`
	CYPdInExcessIncomeActivityAmt  int         `xml:"CYPdInExcessIncomeActivityAmt"`
	CYAdministrativeExpensePaidAmt int         `xml:"CYAdministrativeExpensePaidAmt"`
	ExemptUseAssetsAcquisPaidAmt   int         `xml:"ExemptUseAssetsAcquisPaidAmt"`
	QualifiedSetAsideAmt           int         `xml:"QualifiedSetAsideAmt"`
	CYOtherDistributionsAmt        int         `xml:"CYOtherDistributionsAmt"`
	CYTotalAnnualDistributionsAmt  int         `xml:"CYTotalAnnualDistributionsAmt"`
	CYDistriAttentiveSuprtOrgAmt   int         `xml:"CYDistriAttentiveSuprtOrgAmt"`
	CYDistributableAsAdjustedAmt   int         `xml:"CYDistributableAsAdjustedAmt"`
	CYDistributionYrRt             interface{} `xml:"CYDistributionYrRt"`
}

// DistributionAllocationsGrp is Part V Section E Group
type DistributionAllocationsGrp struct {
	CYDistributableAsAdjustedAmt   int `xml:"CYDistributableAsAdjustedAmt"`
	UnderdistributionsAmt          int `xml:"UnderdistributionsAmt"`
	ExcessDistributionCyovYr5Amt   int `xml:"ExcessDistributionCyovYr5Amt"`
	ExcessDistributionCyovYr4Amt   int `xml:"ExcessDistributionCyovYr4Amt"`
	ExcessDistributionCyovYr3Amt   int `xml:"ExcessDistributionCyovYr3Amt"`
	ExcessDistributionCyovYr2Amt   int `xml:"ExcessDistributionCyovYr2Amt"`
	ExcessDistributionCyovYr1Amt   int `xml:"ExcessDistributionCyovYr1Amt"`
	TotalExcessDistributionCyovAmt int `xml:"TotalExcessDistributionCyovAmt"`
	CyovAppliedUnderdistriPYAmt    int `xml:"CyovAppliedUnderdistriPYAmt"`
	CyovAppliedUnderdistrCPYAmt    int `xml:"CyovAppliedUnderdistrCPYAmt"`
	CarryoverPYNotAppliedAmt       int `xml:"CarryoverPYNotAppliedAmt"`
	ExcessDistributionCyovAmt      int `xml:"ExcessDistributionCyovAmt"`
	CYTotalAnnualDistributionsAmt  int `xml:"CYTotalAnnualDistributionsAmt"`
	CYDistribAppUnderdistriPYAmt   int `xml:"CYDistribAppUnderdistriPYAmt"`
	CYDistriAppDistributableAmt    int `xml:"CYDistriAppDistributableAmt,omitempty"`
	ExcessDistributionAmt          int `xml:"ExcessDistributionAmt"`
	RemainingUnderdistriPYAmt      int `xml:"RemainingUnderdistriPYAmt"`
	RemainingUnderdistriCYAmt      int `xml:"RemainingUnderdistriCYAmt"`
	ExcessDistriCyovToNextYrAmt    int `xml:"ExcessDistriCyovToNextYrAmt"`
	ExcessFromYear5Amt             int `xml:"ExcessFromYear5Amt"`
	ExcessFromYear4Amt             int `xml:"ExcessFromYear4Amt"`
	ExcessFromYear3Amt             int `xml:"ExcessFromYear3Amt"`
	ExcessFromYear2Amt             int `xml:"ExcessFromYear2Amt"`
	ExcessFromYear1Amt             int `xml:"ExcessFromYear1Amt"`
}

// Form990ScheduleAPartVIGrp is Schedule A, Part VI
type Form990ScheduleAPartVIGrp struct {
	FormAndLineReferenceDesc string `xml:"FormAndLineReferenceDesc,omitempty"`
	ExplanationTxt           string `xml:"ExplanationTxt,omitempty"`
}

// IRS990ScheduleAType is Part III Line 20
type IRS990ScheduleAType struct {
	ChurchInd                      string                            `xml:"ChurchInd"`
	SchoolInd                      string                            `xml:"SchoolInd"`
	HospitalInd                    string                            `xml:"HospitalInd"`
	MedicalResearchOrganizationInd string                            `xml:"MedicalResearchOrganizationInd"`
	HospitalNameAndAddressGrp      []*HospitalNameAndAddressGrpType  `xml:"HospitalNameAndAddressGrp"`
	CollegeOrganizationInd         string                            `xml:"CollegeOrganizationInd"`
	GovernmentalUnitInd            string                            `xml:"GovernmentalUnitInd"`
	PublicOrganization170Ind       string                            `xml:"PublicOrganization170Ind"`
	CommunityTrustInd              string                            `xml:"CommunityTrustInd"`
	AgriculturalResearchOrgInd     string                            `xml:"AgriculturalResearchOrgInd"`
	AgriculturalNameAndAddressGrp  []*AgricNameAndAddressGrpType     `xml:"AgriculturalNameAndAddressGrp"`
	PubliclySupportedOrg509a2Ind   string                            `xml:"PubliclySupportedOrg509a2Ind"`
	TestPublicSafetyInd            string                            `xml:"TestPublicSafetyInd"`
	SupportingOrganization509a3Ind string                            `xml:"SupportingOrganization509a3Ind"`
	SupportingOrgType1Ind          string                            `xml:"SupportingOrgType1Ind"`
	SupportingOrgType2Ind          string                            `xml:"SupportingOrgType2Ind"`
	SupportingOrgType3FuncIntInd   string                            `xml:"SupportingOrgType3FuncIntInd"`
	SupportingOrgType3NonFuncInd   string                            `xml:"SupportingOrgType3NonFuncInd"`
	IRSWrittenDeterminationInd     string                            `xml:"IRSWrittenDeterminationInd,omitempty"`
	SupportedOrganizationsCnt      int                               `xml:"SupportedOrganizationsCnt,omitempty"`
	SupportedOrgInformationGrp     []*SupportedOrgInformationGrpType `xml:"SupportedOrgInformationGrp,omitempty"`
	SupportedOrganizationsTotalCnt int                               `xml:"SupportedOrganizationsTotalCnt,omitempty"`
	SupportSumAmt                  int                               `xml:"SupportSumAmt,omitempty"`
	OtherSupportSumAmt             int                               `xml:"OtherSupportSumAmt,omitempty"`
	GiftsGrantsContriRcvd170Grp    *Form990SchAPartIIGroup1Type      `xml:"GiftsGrantsContriRcvd170Grp,omitempty"`
	TaxRevLeviedOrgnztnlBnft170Grp *Form990SchAPartIIGroup1Type      `xml:"TaxRevLeviedOrgnztnlBnft170Grp,omitempty"`
	GovtFurnSrvcFcltsVl170Grp      *Form990SchAPartIIGroup1Type      `xml:"GovtFurnSrvcFcltsVl170Grp,omitempty"`
	TotalCalendarYear170Grp        *Form990SchAPartIIGroup1Type      `xml:"TotalCalendarYear170Grp,omitempty"`
	SubstantialContributorsTotAmt  int                               `xml:"SubstantialContributorsTotAmt,omitempty"`
	PublicSupportTotal170Amt       int                               `xml:"PublicSupportTotal170Amt,omitempty"`
	GrossInvestmentIncome170Grp    *Form990SchAPartIIGroup1Type      `xml:"GrossInvestmentIncome170Grp,omitempty"`
	UnrelatedBusinessNetIncm170Grp *Form990SchAPartIIGroup1Type      `xml:"UnrelatedBusinessNetIncm170Grp,omitempty"`
	OtherIncome170Grp              *Form990SchAPartIIGroup1Type      `xml:"OtherIncome170Grp,omitempty"`
	TotalSupportAmt                int                               `xml:"TotalSupportAmt,omitempty"`
	GrossReceiptsRltdActivitiesAmt int                               `xml:"GrossReceiptsRltdActivitiesAmt,omitempty"`
	First5Years170Ind              string                            `xml:"First5Years170Ind,omitempty"`
	PublicSupportCY170Pct          float64                           `xml:"PublicSupportCY170Pct,omitempty"`
	PublicSupportPY170Pct          float64                           `xml:"PublicSupportPY170Pct,omitempty"`
	ThirtyThrPctSuprtTestsCY170Ind string                            `xml:"ThirtyThrPctSuprtTestsCY170Ind,omitempty"`
	ThirtyThrPctSuprtTestsPY170Ind string                            `xml:"ThirtyThrPctSuprtTestsPY170Ind,omitempty"`
	TenPctFactsCrcmstncsTestCYInd  string                            `xml:"TenPctFactsCrcmstncsTestCYInd,omitempty"`
	TenPctFactsCrcmstncsTestPYInd  string                            `xml:"TenPctFactsCrcmstncsTestPYInd,omitempty"`
	PrivateFoundation170Ind        string                            `xml:"PrivateFoundation170Ind,omitempty"`
	GiftsGrantsContrisRcvd509Grp   *Form990SchAPartIIGroup1Type      `xml:"GiftsGrantsContrisRcvd509Grp,omitempty"`
	GrossReceiptsAdmissionsGrp     *Form990SchAPartIIGroup1Type      `xml:"GrossReceiptsAdmissionsGrp,omitempty"`
	GrossReceiptsNonUnrltBusGrp    *Form990SchAPartIIGroup1Type      `xml:"GrossReceiptsNonUnrltBusGrp,omitempty"`
	TaxRevLeviedOrgnztnlBnft509Grp *Form990SchAPartIIGroup1Type      `xml:"TaxRevLeviedOrgnztnlBnft509Grp,omitempty"`
	GovtFurnSrvcFcltsVl509Grp      *Form990SchAPartIIGroup1Type      `xml:"GovtFurnSrvcFcltsVl509Grp,omitempty"`
	Total509Grp                    *Form990SchAPartIIGroup1Type      `xml:"Total509Grp,omitempty"`
	AmountsRcvdDsqlfyPersonGrp     *Form990SchAPartIIGroup1Type      `xml:"AmountsRcvdDsqlfyPersonGrp,omitempty"`
	SubstantialContributorsAmtGrp  *Form990SchAPartIIGroup1Type      `xml:"SubstantialContributorsAmtGrp,omitempty"`
	SubstAndDsqlfyPrsnsTotGrp      *Form990SchAPartIIGroup1Type      `xml:"SubstAndDsqlfyPrsnsTotGrp,omitempty"`
	PublicSupportTotal509Amt       int                               `xml:"PublicSupportTotal509Amt,omitempty"`
	GrossInvestmentIncome509Grp    *Form990SchAPartIIGroup1Type      `xml:"GrossInvestmentIncome509Grp,omitempty"`
	Post1975UBTIGrp                *Form990SchAPartIIGroup1Type      `xml:"Post1975UBTIGrp,omitempty"`
	InvestmentIncomeAndUBTIGrp     *Form990SchAPartIIGroup1Type      `xml:"InvestmentIncomeAndUBTIGrp,omitempty"`
	NetIncomeFromOtherUBIGrp       *Form990SchAPartIIGroup1Type      `xml:"NetIncomeFromOtherUBIGrp,omitempty"`
	OtherIncome509Grp              *Form990SchAPartIIGroup1Type      `xml:"OtherIncome509Grp,omitempty"`
	TotalSupportCalendarYearGrp    *Form990SchAPartIIGroup1Type      `xml:"TotalSupportCalendarYearGrp,omitempty"`
	First5Years509Ind              string                            `xml:"First5Years509Ind,omitempty"`
	PublicSupportCY509Pct          float64                           `xml:"PublicSupportCY509Pct,omitempty"`
	PublicSupportPY509Pct          float64                           `xml:"PublicSupportPY509Pct,omitempty"`
	InvestmentIncomeCYPct          float64                           `xml:"InvestmentIncomeCYPct,omitempty"`
	InvestmentIncomePYPct          float64                           `xml:"InvestmentIncomePYPct,omitempty"`
	ThirtyThrPctSuprtTestsCY509Ind string                            `xml:"ThirtyThrPctSuprtTestsCY509Ind,omitempty"`
	ThirtyThrPctSuprtTestsPY509Ind string                            `xml:"ThirtyThrPctSuprtTestsPY509Ind,omitempty"`
	PrivateFoundation509Ind        string                            `xml:"PrivateFoundation509Ind,omitempty"`
	Form990SchASupportingOrgGrp    *Form990SchASupportingOrgGrp      `xml:"Form990SchASupportingOrgGrp,omitempty"`
	Form990SchAType1SuprtOrgGrp    *Form990SchAType1SuprtOrgGrp      `xml:"Form990SchAType1SuprtOrgGrp,omitempty"`
	MajorityDirTrstSupportedOrgInd bool                              `xml:"MajorityDirTrstSupportedOrgInd,omitempty"`
	Form990SchAType3SprtOrgAllGrp  *Form990SchAType3SprtOrgAllGrp    `xml:"Form990SchAType3SprtOrgAllGrp,omitempty"`
	Form990SchAType3FuncIntGrp     *Form990SchAType3FuncIntGrp       `xml:"Form990SchAType3FuncIntGrp,omitempty"`
	TrustIntegralPartTestInd       string                            `xml:"TrustIntegralPartTestInd,omitempty"`
	AdjustedNetIncomeGrp           *AdjustedNetIncomeGrp             `xml:"AdjustedNetIncomeGrp,omitempty"`
	MinimumAssetAmountGrp          *MinimumAssetAmountGrp            `xml:"MinimumAssetAmountGrp,omitempty"`
	DistributableAmountGrp         *DistributableAmountGrp           `xml:"DistributableAmountGrp,omitempty"`
	DistributionsGrp               *DistributionsGrp                 `xml:"DistributionsGrp,omitempty"`
	DistributionAllocationsGrp     *DistributionAllocationsGrp       `xml:"DistributionAllocationsGrp,omitempty"`
	FactsAndCircumstancesTestTxt   string                            `xml:"FactsAndCircumstancesTestTxt,omitempty"`
	Form990ScheduleAPartVIGrp      []*Form990ScheduleAPartVIGrp      `xml:"Form990ScheduleAPartVIGrp,omitempty"`
}

// HospitalNameAndAddressGrpType is Part I Line 4
type HospitalNameAndAddressGrpType struct {
	SupportedOrganizationName *BusinessNameType `xml:"SupportedOrganizationName,omitempty"`
	CityNm                    string            `xml:"CityNm"`
	StateAbbreviationCd       string            `xml:"StateAbbreviationCd"`
	CountryCd                 string            `xml:"CountryCd"`
}

// AgricNameAndAddressGrpType is Part I Line 9
type AgricNameAndAddressGrpType struct {
	CollegeUniversityName *BusinessNameType `xml:"CollegeUniversityName,omitempty"`
	CityNm                string            `xml:"CityNm"`
	StateAbbreviationCd   string            `xml:"StateAbbreviationCd"`
	CountryCd             string            `xml:"CountryCd"`
}

// SupportedOrgInformationGrpType is Part I Line 12g Column (ii)
type SupportedOrgInformationGrpType struct {
	SupportedOrganizationName  *BusinessNameType `xml:"SupportedOrganizationName"`
	EIN                        string            `xml:"EIN"`
	OrganizationTypeCd         interface{}       `xml:"OrganizationTypeCd"`
	GoverningDocumentListedInd bool              `xml:"GoverningDocumentListedInd"`
	SupportAmt                 int               `xml:"SupportAmt"`
	OtherSupportAmt            int               `xml:"OtherSupportAmt"`
}

// Form990SchAPartIIGroup1Type is Part II and III Column (f)
type Form990SchAPartIIGroup1Type struct {
	CurrentTaxYearMinus4YearsAmt int `xml:"CurrentTaxYearMinus4YearsAmt,omitempty"`
	CurrentTaxYearMinus3YearsAmt int `xml:"CurrentTaxYearMinus3YearsAmt,omitempty"`
	CurrentTaxYearMinus2YearsAmt int `xml:"CurrentTaxYearMinus2YearsAmt,omitempty"`
	CurrentTaxYearMinus1YearAmt  int `xml:"CurrentTaxYearMinus1YearAmt,omitempty"`
	CurrentTaxYearAmt            int `xml:"CurrentTaxYearAmt,omitempty"`
	TotalAmt                     int `xml:"TotalAmt,omitempty"`
}

// Form990SchAPartVGroup1Type is Part V Column B
type Form990SchAPartVGroup1Type struct {
	PriorYearAmt   int `xml:"PriorYearAmt"`
	CurrentYearAmt int `xml:"CurrentYearAmt,omitempty"`
}

// Form990SchAPartVGroup2Type is Part V Column B
type Form990SchAPartVGroup2Type struct {
	PriorYearAmt   int `xml:"PriorYearAmt"`
	CurrentYearAmt int `xml:"CurrentYearAmt,omitempty"`
}
