// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990ScheduleM is Common return document attributes
type IRS990ScheduleM struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*IRS990ScheduleMType
}


// IRS990ScheduleMType is Part I Line 32a
type IRS990ScheduleMType struct {
	WorksOfArtGrp                  *Form990SchMGroup1Type           `xml:"WorksOfArtGrp,omitempty"`
	ArtHistoricalTreasuresGrp      *Form990SchMGroup1Type           `xml:"ArtHistoricalTreasuresGrp,omitempty"`
	ArtFractionalInterestGrp       *Form990SchMGroup1Type           `xml:"ArtFractionalInterestGrp,omitempty"`
	BooksAndPublicationsGrp        *Form990SchMGroup2Type           `xml:"BooksAndPublicationsGrp,omitempty"`
	ClothingAndHouseholdGoodsGrp   *Form990SchMGroup2Type           `xml:"ClothingAndHouseholdGoodsGrp,omitempty"`
	CarsAndOtherVehiclesGrp        *Form990SchMGroup1Type           `xml:"CarsAndOtherVehiclesGrp,omitempty"`
	BoatsAndPlanesGrp              *Form990SchMGroup1Type           `xml:"BoatsAndPlanesGrp,omitempty"`
	IntellectualPropertyGrp        *Form990SchMGroup1Type           `xml:"IntellectualPropertyGrp,omitempty"`
	SecuritiesPubliclyTradedGrp    *Form990SchMGroup1Type           `xml:"SecuritiesPubliclyTradedGrp,omitempty"`
	SecuritiesCloselyHeldStockGrp  *Form990SchMGroup1Type           `xml:"SecuritiesCloselyHeldStockGrp,omitempty"`
	SecurPrtnrshpTrustIntrstsGrp   *Form990SchMGroup1Type           `xml:"SecurPrtnrshpTrustIntrstsGrp,omitempty"`
	SecuritiesMiscellaneousGrp     *Form990SchMGroup1Type           `xml:"SecuritiesMiscellaneousGrp,omitempty"`
	QualifiedContribHistStructGrp  *Form990SchMGroup1Type           `xml:"QualifiedContribHistStructGrp,omitempty"`
	QualifiedContribOtherGrp       *Form990SchMGroup1Type           `xml:"QualifiedContribOtherGrp,omitempty"`
	RealEstateResidentialGrp       *Form990SchMGroup1Type           `xml:"RealEstateResidentialGrp,omitempty"`
	RealEstateCommercialGrp        *Form990SchMGroup1Type           `xml:"RealEstateCommercialGrp,omitempty"`
	RealEstateOtherGrp             *Form990SchMGroup1Type           `xml:"RealEstateOtherGrp,omitempty"`
	CollectiblesGrp                *Form990SchMGroup1Type           `xml:"CollectiblesGrp,omitempty"`
	FoodInventoryGrp               *Form990SchMGroup1Type           `xml:"FoodInventoryGrp,omitempty"`
	DrugsAndMedicalSuppliesGrp     *Form990SchMGroup1Type           `xml:"DrugsAndMedicalSuppliesGrp,omitempty"`
	TaxidermyGrp                   *Form990SchMGroup1Type           `xml:"TaxidermyGrp,omitempty"`
	HistoricalArtifactsGrp         *Form990SchMGroup1Type           `xml:"HistoricalArtifactsGrp,omitempty"`
	ScientificSpecimensGrp         *Form990SchMGroup1Type           `xml:"ScientificSpecimensGrp,omitempty"`
	ArchaeologicalArtifactsGrp     *Form990SchMGroup1Type           `xml:"ArchaeologicalArtifactsGrp,omitempty"`
	OtherNonCashContriTableGrp     []*Form990SchMGroup3Type         `xml:"OtherNonCashContriTableGrp,omitempty"`
	Form8283ReceivedCnt            int                              `xml:"Form8283ReceivedCnt,omitempty"`
	AnyPropertyThatMustBeHeldInd   bool                             `xml:"AnyPropertyThatMustBeHeldInd,omitempty"`
	ReviewProcessUnusualNCGiftsInd bool                             `xml:"ReviewProcessUnusualNCGiftsInd,omitempty"`
	ThirdPartiesUsedInd            bool                             `xml:"ThirdPartiesUsedInd,omitempty"`
	SupplementalInformationDetail  []*SupplementalInformationDetail `xml:"SupplementalInformationDetail,omitempty"`
}

// Form990SchMGroup1 ...
type Form990SchMGroup1 struct {
	NonCashCheckboxInd string
}

// Form990SchMGroup2 ...
type Form990SchMGroup2 struct {
	ContributionCnt int
}

// Form990SchMGroup3 ...
type Form990SchMGroup3 struct {
	NoncashContributionsRptF990Amt int
	MethodOfDeterminingRevenuesTxt string
}

// Form990SchMGroup1Type ...
type Form990SchMGroup1Type struct {
	Form990SchMGroup1 *Form990SchMGroup1
	Form990SchMGroup2 *Form990SchMGroup2
	Form990SchMGroup3 *Form990SchMGroup3
}

// Form990SchMGroup2Type ...
type Form990SchMGroup2Type struct {
	Form990SchMGroup1 *Form990SchMGroup1
	Form990SchMGroup3 *Form990SchMGroup3
}

// Form990SchMGroup3Type is Lines 25 - 28
type Form990SchMGroup3Type struct {
	Form990SchMGroup1 *Form990SchMGroup1
	Form990SchMGroup2 *Form990SchMGroup2
	Form990SchMGroup3 *Form990SchMGroup3
	Desc              string `xml:"Desc,omitempty"`
}
