// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990ScheduleF is Common return document attributes
type IRS990ScheduleF struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*IRS990ScheduleFType
}


// IRS990ScheduleFType is Part IV Line 6
type IRS990ScheduleFType struct {
	GrantRecordsMaintainedInd     bool                                 `xml:"GrantRecordsMaintainedInd,omitempty"`
	AccountActivitiesOutsideUSGrp []*AccountActivitiesOutsideUSGrpType `xml:"AccountActivitiesOutsideUSGrp,omitempty"`
	SubtotalOfficesCnt            int                                  `xml:"SubtotalOfficesCnt,omitempty"`
	SubtotalEmployeesCnt          int                                  `xml:"SubtotalEmployeesCnt,omitempty"`
	ContinuationTotalOfficeCnt    int                                  `xml:"ContinuationTotalOfficeCnt,omitempty"`
	ContinuationTotalEmployeeCnt  int                                  `xml:"ContinuationTotalEmployeeCnt,omitempty"`
	TotalOfficeCnt                int                                  `xml:"TotalOfficeCnt,omitempty"`
	TotalEmployeeCnt              int                                  `xml:"TotalEmployeeCnt,omitempty"`
	SubtotalSpentAmt              int                                  `xml:"SubtotalSpentAmt,omitempty"`
	ContinuationSpentAmt          int                                  `xml:"ContinuationSpentAmt,omitempty"`
	TotalSpentAmt                 int                                  `xml:"TotalSpentAmt,omitempty"`
	GrantsToOrgOutsideUSGrp       []*GrantsToOrgOutsideUSGrpType       `xml:"GrantsToOrgOutsideUSGrp,omitempty"`
	Total501c3OrgCnt              int                                  `xml:"Total501c3OrgCnt,omitempty"`
	TotalOtherOrgCnt              int                                  `xml:"TotalOtherOrgCnt,omitempty"`
	ForeignIndividualsGrantsGrp   []*ForeignIndividualsGrantsGrpType   `xml:"ForeignIndividualsGrantsGrp,omitempty"`
	TransferToForeignCorpInd      bool                                 `xml:"TransferToForeignCorpInd,omitempty"`
	InterestInForeignTrustInd     bool                                 `xml:"InterestInForeignTrustInd,omitempty"`
	ForeignCorpOwnershipInd       bool                                 `xml:"ForeignCorpOwnershipInd,omitempty"`
	PassiveForeignInvestmestCoInd bool                                 `xml:"PassiveForeignInvestmestCoInd,omitempty"`
	ForeignPartnershipInd         bool                                 `xml:"ForeignPartnershipInd,omitempty"`
	BoycottCountriesInd           bool                                 `xml:"BoycottCountriesInd,omitempty"`
	SupplementalInformationDetail []*SupplementalInformationDetail     `xml:"SupplementalInformationDetail,omitempty"`
}

// AccountActivitiesOutsideUSGrpType is Part I Line 3 Column (f)
type AccountActivitiesOutsideUSGrpType struct {
	RegionTxt                    string `xml:"RegionTxt,omitempty"`
	OfficesCnt                   int    `xml:"OfficesCnt,omitempty"`
	EmployeeCnt                  int    `xml:"EmployeeCnt,omitempty"`
	TypeOfActivitiesConductedTxt string `xml:"TypeOfActivitiesConductedTxt,omitempty"`
	SpecificServicesProvidedTxt  string `xml:"SpecificServicesProvidedTxt,omitempty"`
	RegionTotalExpendituresAmt   int    `xml:"RegionTotalExpendituresAmt,omitempty"`
}

// GrantsToOrgOutsideUSGrpType is Column (i)
type GrantsToOrgOutsideUSGrpType struct {
	RegionTxt                   string `xml:"RegionTxt,omitempty"`
	PurposeOfGrantTxt           string `xml:"PurposeOfGrantTxt,omitempty"`
	CashGrantAmt                int    `xml:"CashGrantAmt,omitempty"`
	MannerOfCashDisbursementTxt string `xml:"MannerOfCashDisbursementTxt,omitempty"`
	NonCashAssistanceAmt        int    `xml:"NonCashAssistanceAmt,omitempty"`
	DescriptionOfNonCashAsstTxt string `xml:"DescriptionOfNonCashAsstTxt,omitempty"`
	ValuationMethodUsedDesc     string `xml:"ValuationMethodUsedDesc,omitempty"`
}

// ForeignIndividualsGrantsGrpType is Column (h)
type ForeignIndividualsGrantsGrpType struct {
	TypeOfAssistanceTxt         string `xml:"TypeOfAssistanceTxt,omitempty"`
	RegionTxt                   string `xml:"RegionTxt,omitempty"`
	RecipientCnt                int    `xml:"RecipientCnt,omitempty"`
	CashGrantAmt                int    `xml:"CashGrantAmt,omitempty"`
	MannerOfCashDisbursementTxt string `xml:"MannerOfCashDisbursementTxt,omitempty"`
	NonCashAssistanceAmt        int    `xml:"NonCashAssistanceAmt,omitempty"`
	DescriptionOfNonCashAsstTxt string `xml:"DescriptionOfNonCashAsstTxt,omitempty"`
	ValuationMethodUsedDesc     string `xml:"ValuationMethodUsedDesc,omitempty"`
}
