// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990ScheduleC is Common return document attributes
type IRS990ScheduleC struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*IRS990ScheduleCType
}

// Section527PoliticalOrgGrp is Part I-C Line 5(e)
type Section527PoliticalOrgGrp struct {
	OrganizationBusinessName *BusinessNameType   `xml:"OrganizationBusinessName,omitempty"`
	USAddress                *USAddressType      `xml:"USAddress"`
	ForeignAddress           *ForeignAddressType `xml:"ForeignAddress"`
	EIN                      string              `xml:"EIN,omitempty"`
	PaidInternalFundsAmt     int                 `xml:"PaidInternalFundsAmt,omitempty"`
	ContributionsRcvdDlvrAmt int                 `xml:"ContributionsRcvdDlvrAmt,omitempty"`
}

// OrganizationBelongsAffltGrpInd is Part II-A Line A
type OrganizationBelongsAffltGrpInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     string      `xml:",chardata"`
}


// IRS990ScheduleCType is Part I-C Line 4
type IRS990ScheduleCType struct {
	PoliticalExpendituresAmt       int                              `xml:"PoliticalExpendituresAmt,omitempty"`
	VolunteerHoursCnt              int                              `xml:"VolunteerHoursCnt,omitempty"`
	Section4955OrganizationTaxAmt  int                              `xml:"Section4955OrganizationTaxAmt,omitempty"`
	Section4955ManagersTaxAmt      int                              `xml:"Section4955ManagersTaxAmt,omitempty"`
	Form4720FiledSection4955TaxInd bool                             `xml:"Form4720FiledSection4955TaxInd,omitempty"`
	CorrectionMadeInd              bool                             `xml:"CorrectionMadeInd,omitempty"`
	Expended527ActivitiesAmt       int                              `xml:"Expended527ActivitiesAmt,omitempty"`
	InternalFundsContributedAmt    int                              `xml:"InternalFundsContributedAmt,omitempty"`
	TotalExemptFunctionExpendAmt   int                              `xml:"TotalExemptFunctionExpendAmt,omitempty"`
	Form1120POLFiledInd            bool                             `xml:"Form1120POLFiledInd,omitempty"`
	Section527PoliticalOrgGrp      []*Section527PoliticalOrgGrp     `xml:"Section527PoliticalOrgGrp,omitempty"`
	OrganizationBelongsAffltGrpInd *OrganizationBelongsAffltGrpInd  `xml:"OrganizationBelongsAffltGrpInd,omitempty"`
	LimitedControlProvisionsAppInd string                           `xml:"LimitedControlProvisionsAppInd,omitempty"`
	TotalGrassrootsLobbyingGrp     *Form990SchCPartIIAGroup1Type    `xml:"TotalGrassrootsLobbyingGrp,omitempty"`
	TotalDirectLobbyingGrp         *Form990SchCPartIIAGroup1Type    `xml:"TotalDirectLobbyingGrp,omitempty"`
	TotalLobbyingExpendGrp         *Form990SchCPartIIAGroup1Type    `xml:"TotalLobbyingExpendGrp,omitempty"`
	OtherExemptPurposeExpendGrp    *Form990SchCPartIIAGroup1Type    `xml:"OtherExemptPurposeExpendGrp,omitempty"`
	TotalExemptPurposeExpendGrp    *Form990SchCPartIIAGroup1Type    `xml:"TotalExemptPurposeExpendGrp,omitempty"`
	LobbyingNontaxableAmountGrp    *Form990SchCPartIIAGroup1Type    `xml:"LobbyingNontaxableAmountGrp,omitempty"`
	GrassrootsNontaxableGrp        *Form990SchCPartIIAGroup1Type    `xml:"GrassrootsNontaxableGrp,omitempty"`
	TotLbbyngGrassrootMnsNonTxGrp  *Form990SchCPartIIAGroup1Type    `xml:"TotLbbyngGrassrootMnsNonTxGrp,omitempty"`
	TotLbbyExpendMnsLbbyngNonTxGrp *Form990SchCPartIIAGroup1Type    `xml:"TotLbbyExpendMnsLbbyngNonTxGrp,omitempty"`
	Form4720FiledInd               bool                             `xml:"Form4720FiledInd,omitempty"`
	AvgLobbyingNontaxableAmountGrp *Form990SchCPartIIAGroup2Type    `xml:"AvgLobbyingNontaxableAmountGrp,omitempty"`
	LobbyingCeilingAmt             int                              `xml:"LobbyingCeilingAmt,omitempty"`
	AvgTotalLobbyingExpendGrp      *Form990SchCPartIIAGroup2Type    `xml:"AvgTotalLobbyingExpendGrp,omitempty"`
	AvgGrassrootsNontaxableGrp     *Form990SchCPartIIAGroup2Type    `xml:"AvgGrassrootsNontaxableGrp,omitempty"`
	GrassrootsCeilingAmt           int                              `xml:"GrassrootsCeilingAmt,omitempty"`
	AvgGrassrootsLobbyingExpendGrp *Form990SchCPartIIAGroup2Type    `xml:"AvgGrassrootsLobbyingExpendGrp,omitempty"`
	VolunteersInd                  bool                             `xml:"VolunteersInd,omitempty"`
	PaidStaffOrManagementInd       bool                             `xml:"PaidStaffOrManagementInd,omitempty"`
	MediaAdvertisementsInd         bool                             `xml:"MediaAdvertisementsInd,omitempty"`
	MediaAdvertisementsAmt         int                              `xml:"MediaAdvertisementsAmt,omitempty"`
	MailingsMembersInd             bool                             `xml:"MailingsMembersInd,omitempty"`
	MailingsMembersAmt             int                              `xml:"MailingsMembersAmt,omitempty"`
	PublicationsOrBroadcastInd     bool                             `xml:"PublicationsOrBroadcastInd,omitempty"`
	PublicationsOrBroadcastAmt     int                              `xml:"PublicationsOrBroadcastAmt,omitempty"`
	GrantsOtherOrganizationsInd    bool                             `xml:"GrantsOtherOrganizationsInd,omitempty"`
	GrantsOtherOrganizationsAmt    int                              `xml:"GrantsOtherOrganizationsAmt,omitempty"`
	DirectContactLegislatorsInd    bool                             `xml:"DirectContactLegislatorsInd,omitempty"`
	DirectContactLegislatorsAmt    int                              `xml:"DirectContactLegislatorsAmt,omitempty"`
	RalliesDemonstrationsInd       bool                             `xml:"RalliesDemonstrationsInd,omitempty"`
	RalliesDemonstrationsAmt       int                              `xml:"RalliesDemonstrationsAmt,omitempty"`
	OtherActivitiesInd             bool                             `xml:"OtherActivitiesInd,omitempty"`
	OtherActivitiesAmt             int                              `xml:"OtherActivitiesAmt,omitempty"`
	TotalLobbyingExpendituresAmt   int                              `xml:"TotalLobbyingExpendituresAmt,omitempty"`
	NotDescribedSection501c3Ind    bool                             `xml:"NotDescribedSection501c3Ind,omitempty"`
	Tax4912Amt                     int                              `xml:"Tax4912Amt,omitempty"`
	Managers4912TaxAmt             int                              `xml:"Managers4912TaxAmt,omitempty"`
	Form4720Filed4912TaxInd        bool                             `xml:"Form4720Filed4912TaxInd,omitempty"`
	SubstantiallyAllDuesNondedInd  bool                             `xml:"SubstantiallyAllDuesNondedInd,omitempty"`
	OnlyInHouseLobbyingInd         bool                             `xml:"OnlyInHouseLobbyingInd,omitempty"`
	AgreeCarryoverPriorYearInd     bool                             `xml:"AgreeCarryoverPriorYearInd,omitempty"`
	DuesAssessmentsAmt             int                              `xml:"DuesAssessmentsAmt,omitempty"`
	NonDeductibleLbbyngPltclCYAmt  int                              `xml:"NonDeductibleLbbyngPltclCYAmt,omitempty"`
	NonDedLbbyngPltclCyovAmt       int                              `xml:"NonDedLbbyngPltclCyovAmt,omitempty"`
	NonDeductibleLbbyngPltclTotAmt int                              `xml:"NonDeductibleLbbyngPltclTotAmt,omitempty"`
	AggregateReportedDuesNtcAmt    int                              `xml:"AggregateReportedDuesNtcAmt,omitempty"`
	CarriedOverAmt                 int                              `xml:"CarriedOverAmt,omitempty"`
	TaxableAmt                     int                              `xml:"TaxableAmt,omitempty"`
	SupplementalInformationDetail  []*SupplementalInformationDetail `xml:"SupplementalInformationDetail,omitempty"`
}

// Form990SchCPartIIAGroup1Type is Part II-A Column (b)
type Form990SchCPartIIAGroup1Type struct {
	FilingOrganizationsTotalAmt int `xml:"FilingOrganizationsTotalAmt,omitempty"`
	AffiliatedGroupTotalAmt     int `xml:"AffiliatedGroupTotalAmt,omitempty"`
}

// Form990SchCPartIIAGroup2Type is Part II-A Column (e)
type Form990SchCPartIIAGroup2Type struct {
	CurrentYearMinus3Amt int `xml:"CurrentYearMinus3Amt,omitempty"`
	CurrentYearMinus2Amt int `xml:"CurrentYearMinus2Amt,omitempty"`
	CurrentYearMinus1Amt int `xml:"CurrentYearMinus1Amt,omitempty"`
	CurrentYearAmt       int `xml:"CurrentYearAmt,omitempty"`
	TotalAmt             int `xml:"TotalAmt,omitempty"`
}
