// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990ScheduleN is Common return document attributes
type IRS990ScheduleN struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*IRS990ScheduleNType
}

// LiquidationOfAssetsTableGrp is Part I Line 1
type LiquidationOfAssetsTableGrp struct {
	ReferenceDocumentIdAttr   *IdListType              `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string                   `xml:"referenceDocumentName,attr,omitempty"`
	LiquidationOfAssetsDetail []*Form990SchNGroup1Type `xml:"LiquidationOfAssetsDetail,omitempty"`
}


// IRS990ScheduleNType is Content model for Form 990 Schedule N
type IRS990ScheduleNType struct {
	LiquidationOfAssetsTableGrp   *LiquidationOfAssetsTableGrp     `xml:"LiquidationOfAssetsTableGrp,omitempty"`
	DirectorOfSuccessorInd        bool                             `xml:"DirectorOfSuccessorInd,omitempty"`
	EmployeeOfSuccessorInd        bool                             `xml:"EmployeeOfSuccessorInd,omitempty"`
	OwnerOfSuccessorInd           bool                             `xml:"OwnerOfSuccessorInd,omitempty"`
	ReceiveCompensationInd        bool                             `xml:"ReceiveCompensationInd,omitempty"`
	AssetsDistributedInd          bool                             `xml:"AssetsDistributedInd,omitempty"`
	RequiredToNotifyAGInd         bool                             `xml:"RequiredToNotifyAGInd,omitempty"`
	AttorneyGeneralNotifiedInd    bool                             `xml:"AttorneyGeneralNotifiedInd,omitempty"`
	LiabilitiesPaidInd            bool                             `xml:"LiabilitiesPaidInd,omitempty"`
	BondsOutstandingInd           bool                             `xml:"BondsOutstandingInd,omitempty"`
	BondLiabilitiesDischargedInd  bool                             `xml:"BondLiabilitiesDischargedInd,omitempty"`
	DispositionOfAssetsDetail     []*Form990SchNGroup1Type         `xml:"DispositionOfAssetsDetail,omitempty"`
	DirectorOfSuccessor2Ind       bool                             `xml:"DirectorOfSuccessor2Ind,omitempty"`
	EmployeeOfSuccessor2Ind       bool                             `xml:"EmployeeOfSuccessor2Ind,omitempty"`
	OwnerOfSuccessor2Ind          bool                             `xml:"OwnerOfSuccessor2Ind,omitempty"`
	ReceiveCompensation2Ind       bool                             `xml:"ReceiveCompensation2Ind,omitempty"`
	SupplementalInformationDetail []*SupplementalInformationDetail `xml:"SupplementalInformationDetail,omitempty"`
}

// Form990SchNGroup1Type is Column (g)
type Form990SchNGroup1Type struct {
	AssetsDistriOrExpnssPaidDesc string              `xml:"AssetsDistriOrExpnssPaidDesc,omitempty"`
	DistributionDt               string              `xml:"DistributionDt,omitempty"`
	FairMarketValueOfAssetAmt    int                 `xml:"FairMarketValueOfAssetAmt,omitempty"`
	MethodOfFMVDeterminationTxt  string              `xml:"MethodOfFMVDeterminationTxt,omitempty"`
	EIN                          string              `xml:"EIN,omitempty"`
	PersonNm                     string              `xml:"PersonNm"`
	BusinessName                 *BusinessNameType   `xml:"BusinessName"`
	USAddress                    *USAddressType      `xml:"USAddress"`
	ForeignAddress               *ForeignAddressType `xml:"ForeignAddress"`
	IRCSectionTxt                string              `xml:"IRCSectionTxt,omitempty"`
}
