// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990ScheduleE is Common return document attributes
type IRS990ScheduleE struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*IRS990ScheduleEType
}


// IRS990ScheduleEType is Line 7
type IRS990ScheduleEType struct {
	NondiscriminatoryPolicyStmtInd bool                             `xml:"NondiscriminatoryPolicyStmtInd,omitempty"`
	PolicyStmtInBrochuresEtcInd    bool                             `xml:"PolicyStmtInBrochuresEtcInd,omitempty"`
	PlcyPblczdViaBroadcastMediaInd bool                             `xml:"PlcyPblczdViaBroadcastMediaInd,omitempty"`
	MaintainRacialCompRecsInd      bool                             `xml:"MaintainRacialCompRecsInd,omitempty"`
	MaintainScholarshipsRecsInd    bool                             `xml:"MaintainScholarshipsRecsInd,omitempty"`
	MaintainCpyOfBrochuresEtcInd   bool                             `xml:"MaintainCpyOfBrochuresEtcInd,omitempty"`
	MaintainCpyOfAllSolInd         bool                             `xml:"MaintainCpyOfAllSolInd,omitempty"`
	DiscriminateRaceStdntsRghtsInd bool                             `xml:"DiscriminateRaceStdntsRghtsInd,omitempty"`
	DiscriminateRaceAdmissPlcyInd  bool                             `xml:"DiscriminateRaceAdmissPlcyInd,omitempty"`
	DiscriminateRaceEmplmFcultyInd bool                             `xml:"DiscriminateRaceEmplmFcultyInd,omitempty"`
	DiscriminateRaceSchsInd        bool                             `xml:"DiscriminateRaceSchsInd,omitempty"`
	DiscriminateRaceEducPlcyInd    bool                             `xml:"DiscriminateRaceEducPlcyInd,omitempty"`
	DiscriminateRaceUseOfFcltsInd  bool                             `xml:"DiscriminateRaceUseOfFcltsInd,omitempty"`
	DiscriminateRaceAthltProgInd   bool                             `xml:"DiscriminateRaceAthltProgInd,omitempty"`
	DiscriminateRaceOtherActyInd   bool                             `xml:"DiscriminateRaceOtherActyInd,omitempty"`
	GovernmentFinancialAidRcvdInd  bool                             `xml:"GovernmentFinancialAidRcvdInd,omitempty"`
	GovernmentFinancialAidRvkdInd  bool                             `xml:"GovernmentFinancialAidRvkdInd,omitempty"`
	ComplianceWithRevProc7550Ind   bool                             `xml:"ComplianceWithRevProc7550Ind,omitempty"`
	SupplementalInformationDetail  []*SupplementalInformationDetail `xml:"SupplementalInformationDetail,omitempty"`
}
