// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990ScheduleI is Common return document attributes
type IRS990ScheduleI struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*IRS990ScheduleIType
}

// RecipientTable is Part II Line  1 Column (h)
type RecipientTable struct {
	RecipientBusinessName   *BusinessNameType   `xml:"RecipientBusinessName,omitempty"`
	USAddress               *USAddressType      `xml:"USAddress"`
	ForeignAddress          *ForeignAddressType `xml:"ForeignAddress"`
	RecipientEIN            string              `xml:"RecipientEIN,omitempty"`
	IRCSectionDesc          string              `xml:"IRCSectionDesc,omitempty"`
	CashGrantAmt            int                 `xml:"CashGrantAmt,omitempty"`
	NonCashAssistanceAmt    int                 `xml:"NonCashAssistanceAmt,omitempty"`
	ValuationMethodUsedDesc string              `xml:"ValuationMethodUsedDesc,omitempty"`
	NonCashAssistanceDesc   string              `xml:"NonCashAssistanceDesc,omitempty"`
	PurposeOfGrantTxt       string              `xml:"PurposeOfGrantTxt,omitempty"`
}

// GrantsOtherAsstToIndivInUSGrp is Part III content
type GrantsOtherAsstToIndivInUSGrp struct {
	GrantTypeTxt            string `xml:"GrantTypeTxt,omitempty"`
	RecipientCnt            int    `xml:"RecipientCnt,omitempty"`
	CashGrantAmt            int    `xml:"CashGrantAmt,omitempty"`
	NonCashAssistanceAmt    int    `xml:"NonCashAssistanceAmt,omitempty"`
	ValuationMethodUsedDesc string `xml:"ValuationMethodUsedDesc,omitempty"`
	NonCashAssistanceDesc   string `xml:"NonCashAssistanceDesc,omitempty"`
}


// IRS990ScheduleIType is Part I Line 1
type IRS990ScheduleIType struct {
	GrantRecordsMaintainedInd     bool                             `xml:"GrantRecordsMaintainedInd,omitempty"`
	RecipientTable                []*RecipientTable                `xml:"RecipientTable,omitempty"`
	Total501c3OrgCnt              int                              `xml:"Total501c3OrgCnt,omitempty"`
	TotalOtherOrgCnt              int                              `xml:"TotalOtherOrgCnt,omitempty"`
	GrantsOtherAsstToIndivInUSGrp []*GrantsOtherAsstToIndivInUSGrp `xml:"GrantsOtherAsstToIndivInUSGrp,omitempty"`
	SupplementalInformationDetail []*SupplementalInformationDetail `xml:"SupplementalInformationDetail,omitempty"`
}
