// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990ScheduleD is Common return document attributes
type IRS990ScheduleD struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*IRS990ScheduleDType
}

// CollectionUsedOtherPurposesGrp is Part III Line 3e
type CollectionUsedOtherPurposesGrp struct {
	CollectionUsedOtherPurposesInd string `xml:"CollectionUsedOtherPurposesInd"`
	OtherPurposesDesc              string `xml:"OtherPurposesDesc"`
}


// IRS990ScheduleDType is Part III Line 3d
type IRS990ScheduleDType struct {
	DonorAdvisedFundsHeldCnt       int                              `xml:"DonorAdvisedFundsHeldCnt,omitempty"`
	FundsAndOtherAccountsHeldCnt   int                              `xml:"FundsAndOtherAccountsHeldCnt,omitempty"`
	DonorAdvisedFundsContriAmt     int                              `xml:"DonorAdvisedFundsContriAmt,omitempty"`
	FundsAndOtherAccountsContriAmt int                              `xml:"FundsAndOtherAccountsContriAmt,omitempty"`
	DonorAdvisedFundsGrantsAmt     int                              `xml:"DonorAdvisedFundsGrantsAmt,omitempty"`
	FundsAndOtherAccountsGrantsAmt int                              `xml:"FundsAndOtherAccountsGrantsAmt,omitempty"`
	DonorAdvisedFundsVlEOYAmt      int                              `xml:"DonorAdvisedFundsVlEOYAmt,omitempty"`
	FundsAndOtherAccountsVlEOYAmt  int                              `xml:"FundsAndOtherAccountsVlEOYAmt,omitempty"`
	DisclosedOrgLegCtrlInd         bool                             `xml:"DisclosedOrgLegCtrlInd,omitempty"`
	DisclosedForCharitablePrpsInd  bool                             `xml:"DisclosedForCharitablePrpsInd,omitempty"`
	PreservationPublicUseInd       string                           `xml:"PreservationPublicUseInd,omitempty"`
	ProtectionNaturalHabitatInd    string                           `xml:"ProtectionNaturalHabitatInd,omitempty"`
	PreservationOpenSpaceInd       string                           `xml:"PreservationOpenSpaceInd,omitempty"`
	HistoricLandAreaInd            string                           `xml:"HistoricLandAreaInd,omitempty"`
	HistoricStructureInd           string                           `xml:"HistoricStructureInd,omitempty"`
	TotalEasementsCnt              int                              `xml:"TotalEasementsCnt,omitempty"`
	TotalAcreageCnt                float64                          `xml:"TotalAcreageCnt,omitempty"`
	HistoricStructureEasementsCnt  int                              `xml:"HistoricStructureEasementsCnt,omitempty"`
	HistoricStrctrEasementsAftrCnt int                              `xml:"HistoricStrctrEasementsAftrCnt,omitempty"`
	ModifiedEasementsCnt           int                              `xml:"ModifiedEasementsCnt,omitempty"`
	StatesEasementsHeldCnt         int                              `xml:"StatesEasementsHeldCnt,omitempty"`
	WrittenPolicyMonitoringInd     bool                             `xml:"WrittenPolicyMonitoringInd,omitempty"`
	StaffHoursSpentEnforcementCnt  float64                          `xml:"StaffHoursSpentEnforcementCnt,omitempty"`
	ExpensesIncurredEnforcementAmt int                              `xml:"ExpensesIncurredEnforcementAmt,omitempty"`
	Section170hRqrStsfdInd         bool                             `xml:"Section170hRqrStsfdInd,omitempty"`
	ArtPublicExhibitionAmountsGrp  *Form990SchDPartIIIGroup1Type    `xml:"ArtPublicExhibitionAmountsGrp,omitempty"`
	HeldWorksArtGrp                *Form990SchDPartIIIGroup1Type    `xml:"HeldWorksArtGrp,omitempty"`
	CollectionUsedPubExhibitionInd string                           `xml:"CollectionUsedPubExhibitionInd,omitempty"`
	CollUsedScholarlyRsrchInd      string                           `xml:"CollUsedScholarlyRsrchInd,omitempty"`
	CollectionUsedPreservationInd  string                           `xml:"CollectionUsedPreservationInd,omitempty"`
	CollUsedLoanOrExchProgInd      string                           `xml:"CollUsedLoanOrExchProgInd,omitempty"`
	CollectionUsedOtherPurposesGrp *CollectionUsedOtherPurposesGrp  `xml:"CollectionUsedOtherPurposesGrp,omitempty"`
	SolicitedAssetsSaleInd         bool                             `xml:"SolicitedAssetsSaleInd,omitempty"`
	AgentTrusteeEtcInd             bool                             `xml:"AgentTrusteeEtcInd,omitempty"`
	BeginningBalanceAmt            int                              `xml:"BeginningBalanceAmt,omitempty"`
	AdditionsDuringYearAmt         int                              `xml:"AdditionsDuringYearAmt,omitempty"`
	DistributionsDuringYearAmt     int                              `xml:"DistributionsDuringYearAmt,omitempty"`
	EndingBalanceAmt               int                              `xml:"EndingBalanceAmt,omitempty"`
	InclEscrowCustodialAcctLiabInd bool                             `xml:"InclEscrowCustodialAcctLiabInd,omitempty"`
	ExplanationProvidedInd         string                           `xml:"ExplanationProvidedInd,omitempty"`
	CYEndwmtFundGrp                *Form990SchDPartVGroup1Type      `xml:"CYEndwmtFundGrp,omitempty"`
	CYMinus1YrEndwmtFundGrp        *Form990SchDPartVGroup1Type      `xml:"CYMinus1YrEndwmtFundGrp,omitempty"`
	CYMinus2YrEndwmtFundGrp        *Form990SchDPartVGroup1Type      `xml:"CYMinus2YrEndwmtFundGrp,omitempty"`
	CYMinus3YrEndwmtFundGrp        *Form990SchDPartVGroup1Type      `xml:"CYMinus3YrEndwmtFundGrp,omitempty"`
	CYMinus4YrEndwmtFundGrp        *Form990SchDPartVGroup1Type      `xml:"CYMinus4YrEndwmtFundGrp,omitempty"`
	BoardDesignatedBalanceEOYPct   float64                          `xml:"BoardDesignatedBalanceEOYPct,omitempty"`
	PrmnntEndowmentBalanceEOYPct   float64                          `xml:"PrmnntEndowmentBalanceEOYPct,omitempty"`
	TermEndowmentBalanceEOYPct     float64                          `xml:"TermEndowmentBalanceEOYPct,omitempty"`
	EndowmentsHeldUnrelatedOrgInd  bool                             `xml:"EndowmentsHeldUnrelatedOrgInd,omitempty"`
	EndowmentsHeldRelatedOrgInd    bool                             `xml:"EndowmentsHeldRelatedOrgInd,omitempty"`
	RelatedOrgListSchRInd          bool                             `xml:"RelatedOrgListSchRInd,omitempty"`
	LandGrp                        *Form990SchDPartVIGroup2Type     `xml:"LandGrp,omitempty"`
	BuildingsGrp                   *Form990SchDPartVIGroup1Type     `xml:"BuildingsGrp,omitempty"`
	LeaseholdImprovementsGrp       *Form990SchDPartVIGroup1Type     `xml:"LeaseholdImprovementsGrp,omitempty"`
	EquipmentGrp                   *Form990SchDPartVIGroup1Type     `xml:"EquipmentGrp,omitempty"`
	OtherLandBuildingsGrp          *Form990SchDPartVIGroup1Type     `xml:"OtherLandBuildingsGrp,omitempty"`
	TotalBookValueLandBuildingsAmt int                              `xml:"TotalBookValueLandBuildingsAmt,omitempty"`
	FinancialDerivativesGrp        *Form990SchDPartVIIGroup1Type    `xml:"FinancialDerivativesGrp,omitempty"`
	CloselyHeldEquityInterestsGrp  *Form990SchDPartVIIGroup1Type    `xml:"CloselyHeldEquityInterestsGrp,omitempty"`
	OtherSecuritiesGrp             []*Form990SchDPartVIIGroup2Type  `xml:"OtherSecuritiesGrp,omitempty"`
	TotalBookValueSecuritiesAmt    int                              `xml:"TotalBookValueSecuritiesAmt,omitempty"`
	InvstProgramRelatedOrgGrp      []*Form990SchDPartVIIIGroup1Type `xml:"InvstProgramRelatedOrgGrp,omitempty"`
	TotalBookValueProgramRltdAmt   int                              `xml:"TotalBookValueProgramRltdAmt,omitempty"`
	OtherAssetsOrgGrp              []*Form990SchDPartIXGroup1Type   `xml:"OtherAssetsOrgGrp,omitempty"`
	TotalBookValueOtherAssetsAmt   int                              `xml:"TotalBookValueOtherAssetsAmt,omitempty"`
	FederalIncomeTaxLiabilityAmt   int                              `xml:"FederalIncomeTaxLiabilityAmt,omitempty"`
	OtherLiabilitiesOrgGrp         []*Form990SchDPartXGroup1Type    `xml:"OtherLiabilitiesOrgGrp,omitempty"`
	TotalLiabilityAmt              int                              `xml:"TotalLiabilityAmt,omitempty"`
	FootnoteTextInd                string                           `xml:"FootnoteTextInd,omitempty"`
	TotalRevEtcAuditedFinclStmtAmt int                              `xml:"TotalRevEtcAuditedFinclStmtAmt,omitempty"`
	NetUnrealizedGainsInvstAmt     int                              `xml:"NetUnrealizedGainsInvstAmt,omitempty"`
	DonatedServicesAndUseFcltsAmt  int                              `xml:"DonatedServicesAndUseFcltsAmt,omitempty"`
	RecoveriesPriorYearGrantsAmt   int                              `xml:"RecoveriesPriorYearGrantsAmt,omitempty"`
	OtherRevenueAmt                int                              `xml:"OtherRevenueAmt,omitempty"`
	RevenueNotReportedAmt          int                              `xml:"RevenueNotReportedAmt,omitempty"`
	RevenueSubtotalAmt             int                              `xml:"RevenueSubtotalAmt,omitempty"`
	InvestmentExpensesNotIncldAmt  int                              `xml:"InvestmentExpensesNotIncldAmt,omitempty"`
	OtherRevenuesNotIncludedAmt    int                              `xml:"OtherRevenuesNotIncludedAmt,omitempty"`
	RevenueNotReportedFinclStmtAmt int                              `xml:"RevenueNotReportedFinclStmtAmt,omitempty"`
	TotalRevenuePerForm990Amt      int                              `xml:"TotalRevenuePerForm990Amt,omitempty"`
	TotExpnsEtcAuditedFinclStmtAmt int                              `xml:"TotExpnsEtcAuditedFinclStmtAmt,omitempty"`
	DonatedServicesUseFcltsAmt     int                              `xml:"DonatedServicesUseFcltsAmt,omitempty"`
	PriorYearAdjustmentsAmt        int                              `xml:"PriorYearAdjustmentsAmt,omitempty"`
	LossesReportedAmt              int                              `xml:"LossesReportedAmt,omitempty"`
	OtherExpensesIncludedAmt       int                              `xml:"OtherExpensesIncludedAmt,omitempty"`
	ExpensesNotReportedAmt         int                              `xml:"ExpensesNotReportedAmt,omitempty"`
	ExpensesSubtotalAmt            int                              `xml:"ExpensesSubtotalAmt,omitempty"`
	InvestmentExpensesNotIncld2Amt int                              `xml:"InvestmentExpensesNotIncld2Amt,omitempty"`
	OtherExpensesNotIncludedAmt    int                              `xml:"OtherExpensesNotIncludedAmt,omitempty"`
	ExpensesNotRptFinclStmtAmt     int                              `xml:"ExpensesNotRptFinclStmtAmt,omitempty"`
	TotalExpensesPerForm990Amt     int                              `xml:"TotalExpensesPerForm990Amt,omitempty"`
	SupplementalInformationDetail  []*SupplementalInformationDetail `xml:"SupplementalInformationDetail,omitempty"`
}

// Form990SchDPartIIIGroup1Type is Part III Line 1b(ii) OR Line 2b
type Form990SchDPartIIIGroup1Type struct {
	RevenuesIncludedAmt int `xml:"RevenuesIncludedAmt,omitempty"`
	AssetsIncludedAmt   int `xml:"AssetsIncludedAmt,omitempty"`
}

// Form990SchDPartVGroup1Type is Part V Line 1g
type Form990SchDPartVGroup1Type struct {
	BeginningYearBalanceAmt       int `xml:"BeginningYearBalanceAmt,omitempty"`
	ContributionsAmt              int `xml:"ContributionsAmt,omitempty"`
	InvestmentEarningsOrLossesAmt int `xml:"InvestmentEarningsOrLossesAmt,omitempty"`
	GrantsOrScholarshipsAmt       int `xml:"GrantsOrScholarshipsAmt,omitempty"`
	OtherExpendituresAmt          int `xml:"OtherExpendituresAmt,omitempty"`
	AdministrativeExpensesAmt     int `xml:"AdministrativeExpensesAmt,omitempty"`
	EndYearBalanceAmt             int `xml:"EndYearBalanceAmt,omitempty"`
}

// Form990PartVIGroup1 ...
type Form990PartVIGroup1 struct {
	InvestmentCostOrOtherBasisAmt int
	OtherCostOrOtherBasisAmt      int
}

// Form990PartVIGroup2 ...
type Form990PartVIGroup2 struct {
	BookValueAmt int
}

// Form990SchDPartVIGroup1Type is Part VI Column (c)
type Form990SchDPartVIGroup1Type struct {
	Form990PartVIGroup1 *Form990PartVIGroup1
	Form990PartVIGroup2 *Form990PartVIGroup2
	DepreciationAmt     int `xml:"DepreciationAmt,omitempty"`
}

// Form990SchDPartVIGroup2Type ...
type Form990SchDPartVIGroup2Type struct {
	Form990PartVIGroup1 *Form990PartVIGroup1
	Form990PartVIGroup2 *Form990PartVIGroup2
}

// MethodValuationCd is Column (c)
type MethodValuationCd interface{}

// Form990SchDPartVIIGroup1Type ...
type Form990SchDPartVIIGroup1Type struct {
}

// Form990SchDPartVIIGroup2Type is Column (a)
type Form990SchDPartVIIGroup2Type struct {
	Desc                       string `xml:"Desc,omitempty"`
}

// Form990SchDPartVIIIGroup1Type is Column (a)
type Form990SchDPartVIIIGroup1Type struct {
	Desc                       string `xml:"Desc,omitempty"`
}

// Form990SchDPartIXGroup1Type is Column (b)
type Form990SchDPartIXGroup1Type struct {
	Desc         string `xml:"Desc,omitempty"`
	BookValueAmt int    `xml:"BookValueAmt,omitempty"`
}

// Form990SchDPartXGroup1Type is Column (b)
type Form990SchDPartXGroup1Type struct {
	Desc string `xml:"Desc,omitempty"`
	Amt  int    `xml:"Amt,omitempty"`
}
