// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990ScheduleO is Common return document attributes
type IRS990ScheduleO struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*IRS990ScheduleOType
}

// IRS990ScheduleOType is Content model for IRS Form 990 Schedule O
type IRS990ScheduleOType struct {
	SupplementalInformationDetail []*SupplementalInformationDetailType `xml:"SupplementalInformationDetail"`
}

// SupplementalInformationDetailType is Form, part and line number reference explanation
type SupplementalInformationDetailType struct {
	FormAndLineReferenceDesc string `xml:"FormAndLineReferenceDesc,omitempty"`
	ExplanationTxt           string `xml:"ExplanationTxt"`
}
