// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990ScheduleR is Common return document attributes
type IRS990ScheduleR struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*IRS990ScheduleRType
}

// IdDisregardedEntitiesGrp is Part I Column (f)
type IdDisregardedEntitiesGrp struct {
	DisregardedEntityName         *BusinessNameType   `xml:"DisregardedEntityName,omitempty"`
	USAddress                     *USAddressType      `xml:"USAddress"`
	ForeignAddress                *ForeignAddressType `xml:"ForeignAddress"`
	EIN                           string              `xml:"EIN,omitempty"`
	PrimaryActivitiesTxt          string              `xml:"PrimaryActivitiesTxt,omitempty"`
	LegalDomicileStateCd          string              `xml:"LegalDomicileStateCd"`
	LegalDomicileForeignCountryCd string              `xml:"LegalDomicileForeignCountryCd"`
	TotalIncomeAmt                int                 `xml:"TotalIncomeAmt,omitempty"`
	EndOfYearAssetsAmt            int                 `xml:"EndOfYearAssetsAmt,omitempty"`
	DirectControllingEntityName   *BusinessNameType   `xml:"DirectControllingEntityName"`
	DirectControllingNACd         interface{}         `xml:"DirectControllingNACd"`
}

// IdRelatedTaxExemptOrgGrp is Part II content - Identification of related tax-exempt organizations
type IdRelatedTaxExemptOrgGrp struct {
	DisregardedEntityName         *BusinessNameType   `xml:"DisregardedEntityName,omitempty"`
	USAddress                     *USAddressType      `xml:"USAddress"`
	ForeignAddress                *ForeignAddressType `xml:"ForeignAddress"`
	EIN                           string              `xml:"EIN,omitempty"`
	PrimaryActivitiesTxt          string              `xml:"PrimaryActivitiesTxt,omitempty"`
	LegalDomicileStateCd          string              `xml:"LegalDomicileStateCd"`
	LegalDomicileForeignCountryCd string              `xml:"LegalDomicileForeignCountryCd"`
	ExemptCodeSectionTxt          string              `xml:"ExemptCodeSectionTxt,omitempty"`
	PublicCharityStatusTxt        string              `xml:"PublicCharityStatusTxt,omitempty"`
	DirectControllingEntityName   *BusinessNameType   `xml:"DirectControllingEntityName"`
	DirectControllingNACd         interface{}         `xml:"DirectControllingNACd"`
	ControlledOrganizationInd     bool                `xml:"ControlledOrganizationInd,omitempty"`
}

// IdRelatedOrgTxblPartnershipGrp is Part III content - Identification of related organizations taxable as a partnership
type IdRelatedOrgTxblPartnershipGrp struct {
	RelatedOrganizationName        *BusinessNameType   `xml:"RelatedOrganizationName,omitempty"`
	USAddress                      *USAddressType      `xml:"USAddress"`
	ForeignAddress                 *ForeignAddressType `xml:"ForeignAddress"`
	EIN                            string              `xml:"EIN,omitempty"`
	PrimaryActivitiesTxt           string              `xml:"PrimaryActivitiesTxt,omitempty"`
	LegalDomicileStateCd           string              `xml:"LegalDomicileStateCd"`
	LegalDomicileForeignCountryCd  string              `xml:"LegalDomicileForeignCountryCd"`
	DirectControllingEntityName    *BusinessNameType   `xml:"DirectControllingEntityName"`
	DirectControllingNACd          interface{}         `xml:"DirectControllingNACd"`
	PredominantIncomeTypeTxt       string              `xml:"PredominantIncomeTypeTxt,omitempty"`
	ShareOfTotalIncomeAmt          int                 `xml:"ShareOfTotalIncomeAmt,omitempty"`
	ShareOfEOYAssetsAmt            int                 `xml:"ShareOfEOYAssetsAmt,omitempty"`
	DisproportionateAllocationsInd bool                `xml:"DisproportionateAllocationsInd,omitempty"`
	UBICodeVAmt                    int                 `xml:"UBICodeVAmt,omitempty"`
	GeneralOrManagingPartnerInd    bool                `xml:"GeneralOrManagingPartnerInd,omitempty"`
	OwnershipPct                   float64             `xml:"OwnershipPct,omitempty"`
}

// IdRelatedOrgTxblCorpTrGrp is Part IV content - Identification of related organizations taxable as a corporation or trust
type IdRelatedOrgTxblCorpTrGrp struct {
	RelatedOrganizationName       *BusinessNameType   `xml:"RelatedOrganizationName,omitempty"`
	USAddress                     *USAddressType      `xml:"USAddress"`
	ForeignAddress                *ForeignAddressType `xml:"ForeignAddress"`
	EIN                           string              `xml:"EIN,omitempty"`
	PrimaryActivitiesTxt          string              `xml:"PrimaryActivitiesTxt,omitempty"`
	LegalDomicileStateCd          string              `xml:"LegalDomicileStateCd"`
	LegalDomicileForeignCountryCd string              `xml:"LegalDomicileForeignCountryCd"`
	DirectControllingEntityName   *BusinessNameType   `xml:"DirectControllingEntityName"`
	DirectControllingNACd         interface{}         `xml:"DirectControllingNACd"`
	EntityTypeTxt                 string              `xml:"EntityTypeTxt,omitempty"`
	ShareOfTotalIncomeAmt         int                 `xml:"ShareOfTotalIncomeAmt,omitempty"`
	ShareOfEOYAssetsAmt           int                 `xml:"ShareOfEOYAssetsAmt,omitempty"`
	OwnershipPct                  float64             `xml:"OwnershipPct,omitempty"`
	ControlledOrganizationInd     bool                `xml:"ControlledOrganizationInd,omitempty"`
}

// UnrelatedOrgTxblPartnershipGrp is Part VI content
type UnrelatedOrgTxblPartnershipGrp struct {
	BusinessName                   *BusinessNameType   `xml:"BusinessName,omitempty"`
	USAddress                      *USAddressType      `xml:"USAddress"`
	ForeignAddress                 *ForeignAddressType `xml:"ForeignAddress"`
	EIN                            string              `xml:"EIN,omitempty"`
	PrimaryActivitiesTxt           string              `xml:"PrimaryActivitiesTxt,omitempty"`
	LegalDomicileStateCd           string              `xml:"LegalDomicileStateCd"`
	LegalDomicileForeignCountryCd  string              `xml:"LegalDomicileForeignCountryCd"`
	PredominateIncomeDesc          string              `xml:"PredominateIncomeDesc,omitempty"`
	AllPartnersC3SInd              bool                `xml:"AllPartnersC3SInd,omitempty"`
	ShareOfTotalIncomeAmt          int                 `xml:"ShareOfTotalIncomeAmt,omitempty"`
	ShareOfEOYAssetsAmt            int                 `xml:"ShareOfEOYAssetsAmt,omitempty"`
	DisproportionateAllocationsInd bool                `xml:"DisproportionateAllocationsInd,omitempty"`
	UBICodeVAmt                    int                 `xml:"UBICodeVAmt,omitempty"`
	GeneralOrManagingPartnerInd    bool                `xml:"GeneralOrManagingPartnerInd,omitempty"`
	OwnershipPct                   float64             `xml:"OwnershipPct,omitempty"`
}


// IRS990ScheduleRType is Content model for Form 990 Schedule R
type IRS990ScheduleRType struct {
	IdDisregardedEntitiesGrp       []*IdDisregardedEntitiesGrp       `xml:"IdDisregardedEntitiesGrp,omitempty"`
	IdRelatedTaxExemptOrgGrp       []*IdRelatedTaxExemptOrgGrp       `xml:"IdRelatedTaxExemptOrgGrp,omitempty"`
	IdRelatedOrgTxblPartnershipGrp []*IdRelatedOrgTxblPartnershipGrp `xml:"IdRelatedOrgTxblPartnershipGrp,omitempty"`
	IdRelatedOrgTxblCorpTrGrp      []*IdRelatedOrgTxblCorpTrGrp      `xml:"IdRelatedOrgTxblCorpTrGrp,omitempty"`
	ReceiptOfIntAnntsRntsRyltsInd  bool                              `xml:"ReceiptOfIntAnntsRntsRyltsInd,omitempty"`
	GiftGrntOrCapContriToOthOrgInd bool                              `xml:"GiftGrntOrCapContriToOthOrgInd,omitempty"`
	GiftGrntCapContriFromOthOrgInd bool                              `xml:"GiftGrntCapContriFromOthOrgInd,omitempty"`
	LoansOrGuaranteesToOtherOrgInd bool                              `xml:"LoansOrGuaranteesToOtherOrgInd,omitempty"`
	LoansOrGuaranteesFromOthOrgInd bool                              `xml:"LoansOrGuaranteesFromOthOrgInd,omitempty"`
	DivRelatedOrganizationInd      bool                              `xml:"DivRelatedOrganizationInd,omitempty"`
	AssetSaleToOtherOrgInd         bool                              `xml:"AssetSaleToOtherOrgInd,omitempty"`
	AssetPurchaseFromOtherOrgInd   bool                              `xml:"AssetPurchaseFromOtherOrgInd,omitempty"`
	AssetExchangeInd               bool                              `xml:"AssetExchangeInd,omitempty"`
	RentalOfFacilitiesToOthOrgInd  bool                              `xml:"RentalOfFacilitiesToOthOrgInd,omitempty"`
	RentalOfFcltsFromOthOrgInd     bool                              `xml:"RentalOfFcltsFromOthOrgInd,omitempty"`
	PerformOfServicesForOthOrgInd  bool                              `xml:"PerformOfServicesForOthOrgInd,omitempty"`
	PerformOfServicesByOtherOrgInd bool                              `xml:"PerformOfServicesByOtherOrgInd,omitempty"`
	SharingOfFacilitiesInd         bool                              `xml:"SharingOfFacilitiesInd,omitempty"`
	PaidEmployeesSharingInd        bool                              `xml:"PaidEmployeesSharingInd,omitempty"`
	ReimbursementPaidToOtherOrgInd bool                              `xml:"ReimbursementPaidToOtherOrgInd,omitempty"`
	ReimbursementPaidByOtherOrgInd bool                              `xml:"ReimbursementPaidByOtherOrgInd,omitempty"`
	TransferToOtherOrgInd          bool                              `xml:"TransferToOtherOrgInd,omitempty"`
	TransferFromOtherOrgInd        bool                              `xml:"TransferFromOtherOrgInd,omitempty"`
	TransactionsRelatedOrgGrp      []*TransactionsRelatedOrgGrpType  `xml:"TransactionsRelatedOrgGrp,omitempty"`
	UnrelatedOrgTxblPartnershipGrp []*UnrelatedOrgTxblPartnershipGrp `xml:"UnrelatedOrgTxblPartnershipGrp,omitempty"`
	SupplementalInformationDetail  []*SupplementalInformationDetail  `xml:"SupplementalInformationDetail,omitempty"`
}

// TransactionsRelatedOrgGrpType is Part V Line 2 Column (a)
type TransactionsRelatedOrgGrpType struct {
	OtherOrganizationName          *BusinessNameType `xml:"OtherOrganizationName,omitempty"`
	TransactionTypeTxt             interface{}       `xml:"TransactionTypeTxt,omitempty"`
	InvolvedAmt                    int               `xml:"InvolvedAmt,omitempty"`
	MethodOfAmountDeterminationTxt string            `xml:"MethodOfAmountDeterminationTxt,omitempty"`
}
