// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990 is Common return document attributes
type IRS990 struct {
	DocumentAttributes                *DocumentAttributes
	DocumentNameAttr                  string      `xml:"documentName,attr,omitempty"`
	ReferenceDocumentIdAttr           *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr         string      `xml:"referenceDocumentName,attr,omitempty"`
	AccountingPeriodChangeCdAttr      string      `xml:"accountingPeriodChangeCd,attr,omitempty"`
	AccountingPeriodChangeApprvCdAttr string      `xml:"accountingPeriodChangeApprvCd,attr,omitempty"`
	*IRS990Type
}

// AllAffiliatesIncludedInd is H(b)
type AllAffiliatesIncludedInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}


// DescribedInSection501c3Ind is Part IV Line 1
type DescribedInSection501c3Ind struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// ScheduleBRequiredInd is Part IV Line 2
type ScheduleBRequiredInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}





// ConservationEasementsInd is Part IV Line 7
type ConservationEasementsInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// CollectionsOfArtInd is Part IV Line 8
type CollectionsOfArtInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// CreditCounselingInd is Part IV Line 9
type CreditCounselingInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// DonorRstrOrQuasiEndowmentsInd is Part IV Line 10
type DonorRstrOrQuasiEndowmentsInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// ReportLandBuildingEquipmentInd is Part IV Line 11a
type ReportLandBuildingEquipmentInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// ReportInvestmentsOtherSecInd is Part IV Line 11b
type ReportInvestmentsOtherSecInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// ReportProgramRelatedInvstInd is Part IV Line 11c
type ReportProgramRelatedInvstInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// ReportOtherAssetsInd is Part IV Line 11d
type ReportOtherAssetsInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// ReportOtherLiabilitiesInd is Part IV Line 11e
type ReportOtherLiabilitiesInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// IncludeFIN48FootnoteInd is Part IV Line 11f
type IncludeFIN48FootnoteInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// IndependentAuditFinclStmtInd is Part IV Line 12a
type IndependentAuditFinclStmtInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// ConsolidatedAuditFinclStmtInd is Part IV Line 12b
type ConsolidatedAuditFinclStmtInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}


// ForeignActivitiesInd is Part IV Line 14b
type ForeignActivitiesInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// MoreThan5000KToOrgInd is Part IV Line 15
type MoreThan5000KToOrgInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// MoreThan5000KToIndividualsInd is Part IV Line 16
type MoreThan5000KToIndividualsInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// ProfessionalFundraisingInd is Part IV Line 17
type ProfessionalFundraisingInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// FundraisingActivitiesInd is Part IV Line 18
type FundraisingActivitiesInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// GamingActivitiesInd is Part IV Line 19
type GamingActivitiesInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// OperateHospitalInd is Part IV Line 20a
type OperateHospitalInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// AuditedFinancialStmtAttInd is Part IV Line 20b
type AuditedFinancialStmtAttInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// GrantsToOrganizationsInd is Part IV Line 21
type GrantsToOrganizationsInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// GrantsToIndividualsInd is Part IV Line 22
type GrantsToIndividualsInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// ScheduleJRequiredInd is Part IV Line 23
type ScheduleJRequiredInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// TaxExemptBondsInd is Part IV Line 24a
type TaxExemptBondsInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}


// PYExcessBenefitTransInd is Part IV Line 25b
type PYExcessBenefitTransInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// LoanOutstandingInd is Part IV Line 26
type LoanOutstandingInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// GrantToRelatedPersonInd is Part IV Line 27
type GrantToRelatedPersonInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// BusinessRlnWithOrgMemInd is Part IV Line 28a
type BusinessRlnWithOrgMemInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// BusinessRlnWithFamMemInd is Part IV Line 28b
type BusinessRlnWithFamMemInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// BusinessRlnWith35CtrlEntInd is Part IV Line 28c
type BusinessRlnWith35CtrlEntInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// DeductibleNonCashContriInd is Part IV Line 29
type DeductibleNonCashContriInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// DeductibleArtContributionInd is Part IV Line 30
type DeductibleArtContributionInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// TerminateOperationsInd is Part IV Line 31
type TerminateOperationsInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// PartialLiquidationInd is Part IV Line 32
type PartialLiquidationInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// DisregardedEntityInd is Part IV Line 33
type DisregardedEntityInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// RelatedEntityInd is Part IV Line 34
type RelatedEntityInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// TransactionWithControlEntInd is Part IV Line 35b
type TransactionWithControlEntInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// TrnsfrExmptNonChrtblRltdOrgInd is Part IV Line 36
type TrnsfrExmptNonChrtblRltdOrgInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// ActivitiesConductedPrtshpInd is Part IV Line 37
type ActivitiesConductedPrtshpInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}


// Form990PartVIISectionAGrp is Section A, at least name required
type Form990PartVIISectionAGrp struct {
	PersonNm                       string            `xml:"PersonNm"`
	BusinessName                   *BusinessNameType `xml:"BusinessName"`
	TitleTxt                       string            `xml:"TitleTxt,omitempty"`
	AverageHoursPerWeekRt          interface{}       `xml:"AverageHoursPerWeekRt,omitempty"`
	AverageHoursPerWeekRltdOrgRt   interface{}       `xml:"AverageHoursPerWeekRltdOrgRt,omitempty"`
	IndividualTrusteeOrDirectorInd string            `xml:"IndividualTrusteeOrDirectorInd,omitempty"`
	InstitutionalTrusteeInd        string            `xml:"InstitutionalTrusteeInd,omitempty"`
	OfficerInd                     string            `xml:"OfficerInd,omitempty"`
	KeyEmployeeInd                 string            `xml:"KeyEmployeeInd,omitempty"`
	HighestCompensatedEmployeeInd  string            `xml:"HighestCompensatedEmployeeInd,omitempty"`
	FormerOfcrDirectorTrusteeInd   string            `xml:"FormerOfcrDirectorTrusteeInd,omitempty"`
	ReportableCompFromOrgAmt       int               `xml:"ReportableCompFromOrgAmt,omitempty"`
	ReportableCompFromRltdOrgAmt   int               `xml:"ReportableCompFromRltdOrgAmt,omitempty"`
	OtherCompensationAmt           int               `xml:"OtherCompensationAmt,omitempty"`
}

// FeesForServicesProfFundraising is Part IX Line 11e
type FeesForServicesProfFundraising struct {
	TotalAmt       int `xml:"TotalAmt,omitempty"`
	FundraisingAmt int `xml:"FundraisingAmt,omitempty"`
}


// IRS990Type is Content model for Form 990
type IRS990Type struct {
	SpecialConditionDesc           []interface{}                        `xml:"SpecialConditionDesc,omitempty"`
	AddressChangeInd               string                               `xml:"AddressChangeInd,omitempty"`
	NameChangeInd                  string                               `xml:"NameChangeInd,omitempty"`
	InitialReturnInd               string                               `xml:"InitialReturnInd,omitempty"`
	FinalReturnInd                 string                               `xml:"FinalReturnInd,omitempty"`
	AmendedReturnInd               string                               `xml:"AmendedReturnInd,omitempty"`
	ApplicationPendingInd          string                               `xml:"ApplicationPendingInd,omitempty"`
	DoingBusinessAsName            *BusinessNameType                    `xml:"DoingBusinessAsName,omitempty"`
	PrincipalOfficerNm             string                               `xml:"PrincipalOfficerNm"`
	PrincipalOfcrBusinessName      *BusinessNameType                    `xml:"PrincipalOfcrBusinessName"`
	USAddress                      *USAddressType                       `xml:"USAddress"`
	ForeignAddress                 *ForeignAddressType                  `xml:"ForeignAddress"`
	GrossReceiptsAmt               int                                  `xml:"GrossReceiptsAmt"`
	GroupReturnForAffiliatesInd    bool                                 `xml:"GroupReturnForAffiliatesInd"`
	AllAffiliatesIncludedInd       *AllAffiliatesIncludedInd            `xml:"AllAffiliatesIncludedInd,omitempty"`
	GroupExemptionNum              interface{}                          `xml:"GroupExemptionNum,omitempty"`
	Organization501c3Ind           string                               `xml:"Organization501c3Ind"`
	Organization501cInd            *Organization501cInd                 `xml:"Organization501cInd"`
	Organization4947a1NotPFInd     string                               `xml:"Organization4947a1NotPFInd"`
	Organization527Ind             string                               `xml:"Organization527Ind"`
	WebsiteAddressTxt              string                               `xml:"WebsiteAddressTxt,omitempty"`
	TypeOfOrganizationCorpInd      string                               `xml:"TypeOfOrganizationCorpInd,omitempty"`
	TypeOfOrganizationTrustInd     string                               `xml:"TypeOfOrganizationTrustInd,omitempty"`
	TypeOfOrganizationAssocInd     string                               `xml:"TypeOfOrganizationAssocInd,omitempty"`
	TypeOfOrganizationOtherInd     string                               `xml:"TypeOfOrganizationOtherInd,omitempty"`
	OtherOrganizationDsc           string                               `xml:"OtherOrganizationDsc,omitempty"`
	FormationYr                    string                               `xml:"FormationYr,omitempty"`
	LegalDomicileStateCd           string                               `xml:"LegalDomicileStateCd"`
	LegalDomicileCountryCd         string                               `xml:"LegalDomicileCountryCd"`
	ActivityOrMissionDesc          string                               `xml:"ActivityOrMissionDesc"`
	ContractTerminationInd         string                               `xml:"ContractTerminationInd,omitempty"`
	VotingMembersGoverningBodyCnt  int                                  `xml:"VotingMembersGoverningBodyCnt"`
	VotingMembersIndependentCnt    int                                  `xml:"VotingMembersIndependentCnt"`
	TotalEmployeeCnt               int                                  `xml:"TotalEmployeeCnt"`
	TotalVolunteersCnt             int                                  `xml:"TotalVolunteersCnt,omitempty"`
	TotalGrossUBIAmt               int                                  `xml:"TotalGrossUBIAmt"`
	NetUnrelatedBusTxblIncmAmt     int                                  `xml:"NetUnrelatedBusTxblIncmAmt,omitempty"`
	PYContributionsGrantsAmt       int                                  `xml:"PYContributionsGrantsAmt,omitempty"`
	CYContributionsGrantsAmt       int                                  `xml:"CYContributionsGrantsAmt"`
	PYProgramServiceRevenueAmt     int                                  `xml:"PYProgramServiceRevenueAmt,omitempty"`
	CYProgramServiceRevenueAmt     int                                  `xml:"CYProgramServiceRevenueAmt"`
	PYInvestmentIncomeAmt          int                                  `xml:"PYInvestmentIncomeAmt,omitempty"`
	CYInvestmentIncomeAmt          int                                  `xml:"CYInvestmentIncomeAmt"`
	PYOtherRevenueAmt              int                                  `xml:"PYOtherRevenueAmt,omitempty"`
	CYOtherRevenueAmt              int                                  `xml:"CYOtherRevenueAmt"`
	PYTotalRevenueAmt              int                                  `xml:"PYTotalRevenueAmt,omitempty"`
	CYTotalRevenueAmt              int                                  `xml:"CYTotalRevenueAmt"`
	PYGrantsAndSimilarPaidAmt      int                                  `xml:"PYGrantsAndSimilarPaidAmt,omitempty"`
	CYGrantsAndSimilarPaidAmt      int                                  `xml:"CYGrantsAndSimilarPaidAmt"`
	PYBenefitsPaidToMembersAmt     int                                  `xml:"PYBenefitsPaidToMembersAmt,omitempty"`
	CYBenefitsPaidToMembersAmt     int                                  `xml:"CYBenefitsPaidToMembersAmt"`
	PYSalariesCompEmpBnftPaidAmt   int                                  `xml:"PYSalariesCompEmpBnftPaidAmt,omitempty"`
	CYSalariesCompEmpBnftPaidAmt   int                                  `xml:"CYSalariesCompEmpBnftPaidAmt"`
	PYTotalProfFndrsngExpnsAmt     int                                  `xml:"PYTotalProfFndrsngExpnsAmt,omitempty"`
	CYTotalProfFndrsngExpnsAmt     int                                  `xml:"CYTotalProfFndrsngExpnsAmt"`
	CYTotalFundraisingExpenseAmt   int                                  `xml:"CYTotalFundraisingExpenseAmt"`
	PYOtherExpensesAmt             int                                  `xml:"PYOtherExpensesAmt,omitempty"`
	CYOtherExpensesAmt             int                                  `xml:"CYOtherExpensesAmt"`
	PYTotalExpensesAmt             int                                  `xml:"PYTotalExpensesAmt,omitempty"`
	CYTotalExpensesAmt             int                                  `xml:"CYTotalExpensesAmt"`
	PYRevenuesLessExpensesAmt      int                                  `xml:"PYRevenuesLessExpensesAmt,omitempty"`
	CYRevenuesLessExpensesAmt      int                                  `xml:"CYRevenuesLessExpensesAmt"`
	TotalAssetsBOYAmt              int                                  `xml:"TotalAssetsBOYAmt,omitempty"`
	TotalAssetsEOYAmt              int                                  `xml:"TotalAssetsEOYAmt"`
	TotalLiabilitiesBOYAmt         int                                  `xml:"TotalLiabilitiesBOYAmt,omitempty"`
	TotalLiabilitiesEOYAmt         int                                  `xml:"TotalLiabilitiesEOYAmt"`
	NetAssetsOrFundBalancesBOYAmt  int                                  `xml:"NetAssetsOrFundBalancesBOYAmt,omitempty"`
	NetAssetsOrFundBalancesEOYAmt  int                                  `xml:"NetAssetsOrFundBalancesEOYAmt"`
	InfoInScheduleOPartIIIInd      string                               `xml:"InfoInScheduleOPartIIIInd,omitempty"`
	MissionDesc                    string                               `xml:"MissionDesc,omitempty"`
	SignificantNewProgramSrvcInd   bool                                 `xml:"SignificantNewProgramSrvcInd,omitempty"`
	SignificantChangeInd           bool                                 `xml:"SignificantChangeInd,omitempty"`
	ActivityCd                     int                                  `xml:"ActivityCd,omitempty"`
	ExpenseAmt                     int                                  `xml:"ExpenseAmt,omitempty"`
	GrantAmt                       int                                  `xml:"GrantAmt,omitempty"`
	RevenueAmt                     int                                  `xml:"RevenueAmt,omitempty"`
	Desc                           string                               `xml:"Desc"`
	ProgSrvcAccomActy2Grp          *ProgSrvcAccomplishmentActyGrpType   `xml:"ProgSrvcAccomActy2Grp,omitempty"`
	ProgSrvcAccomActy3Grp          *ProgSrvcAccomplishmentActyGrpType   `xml:"ProgSrvcAccomActy3Grp,omitempty"`
	ProgSrvcAccomActyOtherGrp      []*ProgSrvcAccomplishmentActyGrpType `xml:"ProgSrvcAccomActyOtherGrp,omitempty"`
	TotalOtherProgSrvcExpenseAmt   int                                  `xml:"TotalOtherProgSrvcExpenseAmt,omitempty"`
	TotalOtherProgSrvcGrantAmt     int                                  `xml:"TotalOtherProgSrvcGrantAmt,omitempty"`
	TotalOtherProgSrvcRevenueAmt   int                                  `xml:"TotalOtherProgSrvcRevenueAmt,omitempty"`
	TotalProgramServiceExpensesAmt int                                  `xml:"TotalProgramServiceExpensesAmt,omitempty"`
	DescribedInSection501c3Ind     *DescribedInSection501c3Ind          `xml:"DescribedInSection501c3Ind"`
	ScheduleBRequiredInd           *ScheduleBRequiredInd                `xml:"ScheduleBRequiredInd"`
	PoliticalCampaignActyInd       *PoliticalCampaignActyInd            `xml:"PoliticalCampaignActyInd"`
	LobbyingActivitiesInd          *LobbyingActivitiesInd               `xml:"LobbyingActivitiesInd,omitempty"`
	SubjectToProxyTaxInd           *SubjectToProxyTaxInd                `xml:"SubjectToProxyTaxInd,omitempty"`
	DonorAdvisedFundInd            *DonorAdvisedFundInd                 `xml:"DonorAdvisedFundInd"`
	ConservationEasementsInd       *ConservationEasementsInd            `xml:"ConservationEasementsInd"`
	CollectionsOfArtInd            *CollectionsOfArtInd                 `xml:"CollectionsOfArtInd"`
	CreditCounselingInd            *CreditCounselingInd                 `xml:"CreditCounselingInd"`
	DonorRstrOrQuasiEndowmentsInd  *DonorRstrOrQuasiEndowmentsInd       `xml:"DonorRstrOrQuasiEndowmentsInd"`
	ReportLandBuildingEquipmentInd *ReportLandBuildingEquipmentInd      `xml:"ReportLandBuildingEquipmentInd"`
	ReportInvestmentsOtherSecInd   *ReportInvestmentsOtherSecInd        `xml:"ReportInvestmentsOtherSecInd"`
	ReportProgramRelatedInvstInd   *ReportProgramRelatedInvstInd        `xml:"ReportProgramRelatedInvstInd"`
	ReportOtherAssetsInd           *ReportOtherAssetsInd                `xml:"ReportOtherAssetsInd"`
	ReportOtherLiabilitiesInd      *ReportOtherLiabilitiesInd           `xml:"ReportOtherLiabilitiesInd"`
	IncludeFIN48FootnoteInd        *IncludeFIN48FootnoteInd             `xml:"IncludeFIN48FootnoteInd"`
	IndependentAuditFinclStmtInd   *IndependentAuditFinclStmtInd        `xml:"IndependentAuditFinclStmtInd"`
	ConsolidatedAuditFinclStmtInd  *ConsolidatedAuditFinclStmtInd       `xml:"ConsolidatedAuditFinclStmtInd"`
	SchoolOperatingInd             *SchoolOperatingInd                  `xml:"SchoolOperatingInd"`
	ForeignOfficeInd               bool                                 `xml:"ForeignOfficeInd"`
	ForeignActivitiesInd           *ForeignActivitiesInd                `xml:"ForeignActivitiesInd"`
	MoreThan5000KToOrgInd          *MoreThan5000KToOrgInd               `xml:"MoreThan5000KToOrgInd"`
	MoreThan5000KToIndividualsInd  *MoreThan5000KToIndividualsInd       `xml:"MoreThan5000KToIndividualsInd"`
	ProfessionalFundraisingInd     *ProfessionalFundraisingInd          `xml:"ProfessionalFundraisingInd"`
	FundraisingActivitiesInd       *FundraisingActivitiesInd            `xml:"FundraisingActivitiesInd"`
	GamingActivitiesInd            *GamingActivitiesInd                 `xml:"GamingActivitiesInd"`
	OperateHospitalInd             *OperateHospitalInd                  `xml:"OperateHospitalInd"`
	AuditedFinancialStmtAttInd     *AuditedFinancialStmtAttInd          `xml:"AuditedFinancialStmtAttInd,omitempty"`
	GrantsToOrganizationsInd       *GrantsToOrganizationsInd            `xml:"GrantsToOrganizationsInd"`
	GrantsToIndividualsInd         *GrantsToIndividualsInd              `xml:"GrantsToIndividualsInd"`
	ScheduleJRequiredInd           *ScheduleJRequiredInd                `xml:"ScheduleJRequiredInd"`
	TaxExemptBondsInd              *TaxExemptBondsInd                   `xml:"TaxExemptBondsInd"`
	InvestTaxExemptBondsInd        bool                                 `xml:"InvestTaxExemptBondsInd,omitempty"`
	EscrowAccountInd               bool                                 `xml:"EscrowAccountInd,omitempty"`
	OnBehalfOfIssuerInd            bool                                 `xml:"OnBehalfOfIssuerInd,omitempty"`
	EngagedInExcessBenefitTransInd *EngagedInExcessBenefitTransInd      `xml:"EngagedInExcessBenefitTransInd,omitempty"`
	PYExcessBenefitTransInd        *PYExcessBenefitTransInd             `xml:"PYExcessBenefitTransInd,omitempty"`
	LoanOutstandingInd             *LoanOutstandingInd                  `xml:"LoanOutstandingInd"`
	GrantToRelatedPersonInd        *GrantToRelatedPersonInd             `xml:"GrantToRelatedPersonInd"`
	BusinessRlnWithOrgMemInd       *BusinessRlnWithOrgMemInd            `xml:"BusinessRlnWithOrgMemInd"`
	BusinessRlnWithFamMemInd       *BusinessRlnWithFamMemInd            `xml:"BusinessRlnWithFamMemInd"`
	BusinessRlnWith35CtrlEntInd    *BusinessRlnWith35CtrlEntInd         `xml:"BusinessRlnWith35CtrlEntInd"`
	DeductibleNonCashContriInd     *DeductibleNonCashContriInd          `xml:"DeductibleNonCashContriInd"`
	DeductibleArtContributionInd   *DeductibleArtContributionInd        `xml:"DeductibleArtContributionInd"`
	TerminateOperationsInd         *TerminateOperationsInd              `xml:"TerminateOperationsInd"`
	PartialLiquidationInd          *PartialLiquidationInd               `xml:"PartialLiquidationInd"`
	DisregardedEntityInd           *DisregardedEntityInd                `xml:"DisregardedEntityInd"`
	RelatedEntityInd               *RelatedEntityInd                    `xml:"RelatedEntityInd"`
	RelatedOrganizationCtrlEntInd  bool                                 `xml:"RelatedOrganizationCtrlEntInd"`
	TransactionWithControlEntInd   *TransactionWithControlEntInd        `xml:"TransactionWithControlEntInd,omitempty"`
	TrnsfrExmptNonChrtblRltdOrgInd *TrnsfrExmptNonChrtblRltdOrgInd      `xml:"TrnsfrExmptNonChrtblRltdOrgInd,omitempty"`
	ActivitiesConductedPrtshpInd   *ActivitiesConductedPrtshpInd        `xml:"ActivitiesConductedPrtshpInd"`
	ScheduleORequiredInd           bool                                 `xml:"ScheduleORequiredInd"`
	InfoInScheduleOPartVInd        string                               `xml:"InfoInScheduleOPartVInd,omitempty"`
	IRPDocumentCnt                 int                                  `xml:"IRPDocumentCnt"`
	IRPDocumentW2GCnt              int                                  `xml:"IRPDocumentW2GCnt"`
	BackupWthldComplianceInd       bool                                 `xml:"BackupWthldComplianceInd,omitempty"`
	EmployeeCnt                    int                                  `xml:"EmployeeCnt"`
	EmploymentTaxReturnsFiledInd   bool                                 `xml:"EmploymentTaxReturnsFiledInd,omitempty"`
	UnrelatedBusIncmOverLimitInd   bool                                 `xml:"UnrelatedBusIncmOverLimitInd"`
	Form990TFiledInd               bool                                 `xml:"Form990TFiledInd,omitempty"`
	ForeignFinancialAccountInd     bool                                 `xml:"ForeignFinancialAccountInd"`
	ForeignCountryCd               []string                             `xml:"ForeignCountryCd,omitempty"`
	ProhibitedTaxShelterTransInd   bool                                 `xml:"ProhibitedTaxShelterTransInd"`
	TaxablePartyNotificationInd    bool                                 `xml:"TaxablePartyNotificationInd"`
	Form8886TFiledInd              bool                                 `xml:"Form8886TFiledInd,omitempty"`
	NondeductibleContributionsInd  bool                                 `xml:"NondeductibleContributionsInd"`
	NondeductibleContriDisclInd    bool                                 `xml:"NondeductibleContriDisclInd,omitempty"`
	QuidProQuoContributionsInd     bool                                 `xml:"QuidProQuoContributionsInd,omitempty"`
	QuidProQuoContriDisclInd       bool                                 `xml:"QuidProQuoContriDisclInd,omitempty"`
	Form8282PropertyDisposedOfInd  bool                                 `xml:"Form8282PropertyDisposedOfInd,omitempty"`
	Form8282FiledCnt               int                                  `xml:"Form8282FiledCnt,omitempty"`
	RcvFndsToPayPrsnlBnftCntrctInd bool                                 `xml:"RcvFndsToPayPrsnlBnftCntrctInd,omitempty"`
	PayPremiumsPrsnlBnftCntrctInd  bool                                 `xml:"PayPremiumsPrsnlBnftCntrctInd,omitempty"`
	Form8899Filedind               bool                                 `xml:"Form8899Filedind,omitempty"`
	Form1098CFiledInd              bool                                 `xml:"Form1098CFiledInd,omitempty"`
	DAFExcessBusinessHoldingsInd   bool                                 `xml:"DAFExcessBusinessHoldingsInd,omitempty"`
	TaxableDistributionsInd        bool                                 `xml:"TaxableDistributionsInd,omitempty"`
	DistributionToDonorInd         bool                                 `xml:"DistributionToDonorInd,omitempty"`
	InitiationFeesAndCapContriAmt  int                                  `xml:"InitiationFeesAndCapContriAmt,omitempty"`
	GrossReceiptsForPublicUseAmt   int                                  `xml:"GrossReceiptsForPublicUseAmt,omitempty"`
	MembersAndShrGrossIncomeAmt    int                                  `xml:"MembersAndShrGrossIncomeAmt,omitempty"`
	OtherSourcesGrossIncomeAmt     int                                  `xml:"OtherSourcesGrossIncomeAmt,omitempty"`
	OrgFiledInLieuOfForm1041Ind    bool                                 `xml:"OrgFiledInLieuOfForm1041Ind,omitempty"`
	TaxExemptInterestAmt           int                                  `xml:"TaxExemptInterestAmt,omitempty"`
	LicensedMoreThanOneStateInd    bool                                 `xml:"LicensedMoreThanOneStateInd,omitempty"`
	StateRequiredReservesAmt       int                                  `xml:"StateRequiredReservesAmt,omitempty"`
	ReservesMaintainedAmt          int                                  `xml:"ReservesMaintainedAmt,omitempty"`
	IndoorTanningServicesInd       bool                                 `xml:"IndoorTanningServicesInd"`
	Form720FiledInd                bool                                 `xml:"Form720FiledInd,omitempty"`
	SubjToTaxRmnrtnExPrchtPymtInd  bool                                 `xml:"SubjToTaxRmnrtnExPrchtPymtInd,omitempty"`
	SubjectToExcsTaxNetInvstIncInd bool                                 `xml:"SubjectToExcsTaxNetInvstIncInd,omitempty"`
	ExcsTaxSect4951Or4952Or4953Ind bool                                 `xml:"ExcsTaxSect4951Or4952Or4953Ind,omitempty"`
	InfoInScheduleOPartVIInd       string                               `xml:"InfoInScheduleOPartVIInd,omitempty"`
	GoverningBodyVotingMembersCnt  int                                  `xml:"GoverningBodyVotingMembersCnt"`
	IndependentVotingMemberCnt     int                                  `xml:"IndependentVotingMemberCnt"`
	FamilyOrBusinessRlnInd         bool                                 `xml:"FamilyOrBusinessRlnInd"`
	DelegationOfMgmtDutiesInd      bool                                 `xml:"DelegationOfMgmtDutiesInd"`
	ChangeToOrgDocumentsInd        bool                                 `xml:"ChangeToOrgDocumentsInd"`
	MaterialDiversionOrMisuseInd   bool                                 `xml:"MaterialDiversionOrMisuseInd"`
	MembersOrStockholdersInd       bool                                 `xml:"MembersOrStockholdersInd"`
	ElectionOfBoardMembersInd      bool                                 `xml:"ElectionOfBoardMembersInd"`
	DecisionsSubjectToApprovaInd   bool                                 `xml:"DecisionsSubjectToApprovaInd"`
	MinutesOfGoverningBodyInd      bool                                 `xml:"MinutesOfGoverningBodyInd"`
	MinutesOfCommitteesInd         bool                                 `xml:"MinutesOfCommitteesInd,omitempty"`
	OfficerMailingAddressInd       bool                                 `xml:"OfficerMailingAddressInd"`
	LocalChaptersInd               bool                                 `xml:"LocalChaptersInd"`
	PoliciesReferenceChaptersInd   bool                                 `xml:"PoliciesReferenceChaptersInd,omitempty"`
	Form990ProvidedToGvrnBodyInd   bool                                 `xml:"Form990ProvidedToGvrnBodyInd"`
	ConflictOfInterestPolicyInd    bool                                 `xml:"ConflictOfInterestPolicyInd"`
	AnnualDisclosureCoveredPrsnInd bool                                 `xml:"AnnualDisclosureCoveredPrsnInd,omitempty"`
	RegularMonitoringEnfrcInd      bool                                 `xml:"RegularMonitoringEnfrcInd,omitempty"`
	WhistleblowerPolicyInd         bool                                 `xml:"WhistleblowerPolicyInd"`
	DocumentRetentionPolicyInd     bool                                 `xml:"DocumentRetentionPolicyInd"`
	CompensationProcessCEOInd      bool                                 `xml:"CompensationProcessCEOInd,omitempty"`
	CompensationProcessOtherInd    bool                                 `xml:"CompensationProcessOtherInd,omitempty"`
	InvestmentInJointVentureInd    bool                                 `xml:"InvestmentInJointVentureInd"`
	WrittenPolicyOrProcedureInd    bool                                 `xml:"WrittenPolicyOrProcedureInd,omitempty"`
	StatesWhereCopyOfReturnIsFldCd []string                             `xml:"StatesWhereCopyOfReturnIsFldCd,omitempty"`
	OwnWebsiteInd                  string                               `xml:"OwnWebsiteInd,omitempty"`
	OtherWebsiteInd                string                               `xml:"OtherWebsiteInd,omitempty"`
	UponRequestInd                 string                               `xml:"UponRequestInd,omitempty"`
	OtherInd                       string                               `xml:"OtherInd,omitempty"`
	BooksInCareOfDetail            *BooksInCareOfDetail                 `xml:"BooksInCareOfDetail"`
	InfoInScheduleOPartVIIInd      string                               `xml:"InfoInScheduleOPartVIIInd,omitempty"`
	NoListedPersonsCompensatedInd  string                               `xml:"NoListedPersonsCompensatedInd,omitempty"`
	Form990PartVIISectionAGrp      []*Form990PartVIISectionAGrp         `xml:"Form990PartVIISectionAGrp"`
	TotalReportableCompFromOrgAmt  int                                  `xml:"TotalReportableCompFromOrgAmt,omitempty"`
	TotReportableCompRltdOrgAmt    int                                  `xml:"TotReportableCompRltdOrgAmt,omitempty"`
	TotalOtherCompensationAmt      int                                  `xml:"TotalOtherCompensationAmt,omitempty"`
	IndivRcvdGreaterThan100KCnt    int                                  `xml:"IndivRcvdGreaterThan100KCnt,omitempty"`
	FormerOfcrEmployeesListedInd   bool                                 `xml:"FormerOfcrEmployeesListedInd"`
	TotalCompGreaterThan150KInd    bool                                 `xml:"TotalCompGreaterThan150KInd"`
	CompensationFromOtherSrcsInd   bool                                 `xml:"CompensationFromOtherSrcsInd"`
	ContractorCompensationGrp      []*Form990PartVIIGroup1Type          `xml:"ContractorCompensationGrp,omitempty"`
	CntrctRcvdGreaterThan100KCnt   int                                  `xml:"CntrctRcvdGreaterThan100KCnt,omitempty"`
	InfoInScheduleOPartVIIIInd     string                               `xml:"InfoInScheduleOPartVIIIInd,omitempty"`
	FederatedCampaignsAmt          int                                  `xml:"FederatedCampaignsAmt,omitempty"`
	MembershipDuesAmt              int                                  `xml:"MembershipDuesAmt,omitempty"`
	FundraisingAmt                 int                                  `xml:"FundraisingAmt,omitempty"`
	RelatedOrganizationsAmt        int                                  `xml:"RelatedOrganizationsAmt,omitempty"`
	GovernmentGrantsAmt            int                                  `xml:"GovernmentGrantsAmt,omitempty"`
	AllOtherContributionsAmt       int                                  `xml:"AllOtherContributionsAmt,omitempty"`
	NoncashContributionsAmt        int                                  `xml:"NoncashContributionsAmt,omitempty"`
	TotalContributionsAmt          int                                  `xml:"TotalContributionsAmt,omitempty"`
	ProgramServiceRevenueGrp       []*Form990PartVIIIGroup2Type         `xml:"ProgramServiceRevenueGrp,omitempty"`
	TotalOthProgramServiceRevGrp   *Form990PartVIIIGroup3Type           `xml:"TotalOthProgramServiceRevGrp,omitempty"`
	TotalProgramServiceRevenueAmt  int                                  `xml:"TotalProgramServiceRevenueAmt,omitempty"`
	InvestmentIncomeGrp            *Form990PartVIIIGroup3Type           `xml:"InvestmentIncomeGrp,omitempty"`
	IncmFromInvestBondProceedsGrp  *Form990PartVIIIGroup3Type           `xml:"IncmFromInvestBondProceedsGrp,omitempty"`
	RoyaltiesRevenueGrp            *Form990PartVIIIGroup3Type           `xml:"RoyaltiesRevenueGrp,omitempty"`
	GrossRentsGrp                  *Form990PartVIIIGroup4Type           `xml:"GrossRentsGrp,omitempty"`
	LessRentalExpensesGrp          *Form990PartVIIIGroup4Type           `xml:"LessRentalExpensesGrp,omitempty"`
	RentalIncomeOrLossGrp          *Form990PartVIIIGroup4Type           `xml:"RentalIncomeOrLossGrp,omitempty"`
	NetRentalIncomeOrLossGrp       *Form990PartVIIIGroup3Type           `xml:"NetRentalIncomeOrLossGrp,omitempty"`
	GrossAmountSalesAssetsGrp      *Form990PartVIIIGroup5Type           `xml:"GrossAmountSalesAssetsGrp,omitempty"`
	LessCostOthBasisSalesExpnssGrp *Form990PartVIIIGroup5Type           `xml:"LessCostOthBasisSalesExpnssGrp,omitempty"`
	GainOrLossGrp                  *Form990PartVIIIGroup5Type           `xml:"GainOrLossGrp,omitempty"`
	NetGainOrLossInvestmentsGrp    *Form990PartVIIIGroup3Type           `xml:"NetGainOrLossInvestmentsGrp,omitempty"`
	FundraisingGrossIncomeAmt      int                                  `xml:"FundraisingGrossIncomeAmt,omitempty"`
	ContriRptFundraisingEventAmt   int                                  `xml:"ContriRptFundraisingEventAmt,omitempty"`
	FundraisingDirectExpensesAmt   int                                  `xml:"FundraisingDirectExpensesAmt,omitempty"`
	NetIncmFromFundraisingEvtGrp   *Form990PartVIIIGroup7Type           `xml:"NetIncmFromFundraisingEvtGrp,omitempty"`
	GamingGrossIncomeAmt           int                                  `xml:"GamingGrossIncomeAmt,omitempty"`
	GamingDirectExpensesAmt        int                                  `xml:"GamingDirectExpensesAmt,omitempty"`
	NetIncomeFromGamingGrp         *Form990PartVIIIGroup3Type           `xml:"NetIncomeFromGamingGrp,omitempty"`
	GrossSalesOfInventoryAmt       int                                  `xml:"GrossSalesOfInventoryAmt,omitempty"`
	CostOfGoodsSoldAmt             int                                  `xml:"CostOfGoodsSoldAmt,omitempty"`
	NetIncomeOrLossGrp             *Form990PartVIIIGroup3Type           `xml:"NetIncomeOrLossGrp,omitempty"`
	OtherRevenueMiscGrp            []*Form990PartVIIIGroup2Type         `xml:"OtherRevenueMiscGrp,omitempty"`
	MiscellaneousRevenueGrp        *Form990PartVIIIGroup3Type           `xml:"MiscellaneousRevenueGrp,omitempty"`
	OtherRevenueTotalAmt           int                                  `xml:"OtherRevenueTotalAmt,omitempty"`
	TotalRevenueGrp                *Form990PartVIIIGroup6Type           `xml:"TotalRevenueGrp"`
	InfoInScheduleOPartIXInd       string                               `xml:"InfoInScheduleOPartIXInd,omitempty"`
	GrantsToDomesticOrgsGrp        *Form990PartIXGroup1Type             `xml:"GrantsToDomesticOrgsGrp,omitempty"`
	GrantsToDomesticIndividualsGrp *Form990PartIXGroup1Type             `xml:"GrantsToDomesticIndividualsGrp,omitempty"`
	ForeignGrantsGrp               *Form990PartIXGroup1Type             `xml:"ForeignGrantsGrp,omitempty"`
	BenefitsToMembersGrp           *Form990PartIXGroup1Type             `xml:"BenefitsToMembersGrp,omitempty"`
	CompCurrentOfcrDirectorsGrp    *Form990PartIXGroup2Type             `xml:"CompCurrentOfcrDirectorsGrp,omitempty"`
	CompDisqualPersonsGrp          *Form990PartIXGroup2Type             `xml:"CompDisqualPersonsGrp,omitempty"`
	OtherSalariesAndWagesGrp       *Form990PartIXGroup2Type             `xml:"OtherSalariesAndWagesGrp,omitempty"`
	PensionPlanContributionsGrp    *Form990PartIXGroup2Type             `xml:"PensionPlanContributionsGrp,omitempty"`
	OtherEmployeeBenefitsGrp       *Form990PartIXGroup2Type             `xml:"OtherEmployeeBenefitsGrp,omitempty"`
	PayrollTaxesGrp                *Form990PartIXGroup2Type             `xml:"PayrollTaxesGrp,omitempty"`
	FeesForServicesManagementGrp   *Form990PartIXGroup2Type             `xml:"FeesForServicesManagementGrp,omitempty"`
	FeesForServicesLegalGrp        *Form990PartIXGroup2Type             `xml:"FeesForServicesLegalGrp,omitempty"`
	FeesForServicesAccountingGrp   *Form990PartIXGroup2Type             `xml:"FeesForServicesAccountingGrp,omitempty"`
	FeesForServicesLobbyingGrp     *Form990PartIXGroup2Type             `xml:"FeesForServicesLobbyingGrp,omitempty"`
	FeesForServicesProfFundraising *FeesForServicesProfFundraising      `xml:"FeesForServicesProfFundraising,omitempty"`
	FeesForSrvcInvstMgmntFeesGrp   *Form990PartIXGroup2Type             `xml:"FeesForSrvcInvstMgmntFeesGrp,omitempty"`
	FeesForServicesOtherGrp        *Form990PartIXGroup2Type             `xml:"FeesForServicesOtherGrp,omitempty"`
	AdvertisingGrp                 *Form990PartIXGroup2Type             `xml:"AdvertisingGrp,omitempty"`
	OfficeExpensesGrp              *Form990PartIXGroup2Type             `xml:"OfficeExpensesGrp,omitempty"`
	InformationTechnologyGrp       *Form990PartIXGroup2Type             `xml:"InformationTechnologyGrp,omitempty"`
	RoyaltiesGrp                   *Form990PartIXGroup2Type             `xml:"RoyaltiesGrp,omitempty"`
	OccupancyGrp                   *Form990PartIXGroup2Type             `xml:"OccupancyGrp,omitempty"`
	TravelGrp                      *Form990PartIXGroup2Type             `xml:"TravelGrp,omitempty"`
	PymtTravelEntrtnmntPubOfclGrp  *Form990PartIXGroup2Type             `xml:"PymtTravelEntrtnmntPubOfclGrp,omitempty"`
	ConferencesMeetingsGrp         *Form990PartIXGroup2Type             `xml:"ConferencesMeetingsGrp,omitempty"`
	InterestGrp                    *Form990PartIXGroup2Type             `xml:"InterestGrp,omitempty"`
	PaymentsToAffiliatesGrp        *Form990PartIXGroup2Type             `xml:"PaymentsToAffiliatesGrp,omitempty"`
	DepreciationDepletionGrp       *Form990PartIXGroup2Type             `xml:"DepreciationDepletionGrp,omitempty"`
	InsuranceGrp                   *Form990PartIXGroup2Type             `xml:"InsuranceGrp,omitempty"`
	OtherExpensesGrp               []*Form990PartIXGroup4Type           `xml:"OtherExpensesGrp,omitempty"`
	AllOtherExpensesGrp            *Form990PartIXGroup2Type             `xml:"AllOtherExpensesGrp,omitempty"`
	TotalFunctionalExpensesGrp     *Form990PartIXGroup3Type             `xml:"TotalFunctionalExpensesGrp"`
	JointCostsInd                  string                               `xml:"JointCostsInd,omitempty"`
	TotalJointCostsGrp             *Form990PartIXGroup2Type             `xml:"TotalJointCostsGrp,omitempty"`
	InfoInScheduleOPartXInd        string                               `xml:"InfoInScheduleOPartXInd,omitempty"`
	CashNonInterestBearingGrp      *Form990PartXGroup1Type              `xml:"CashNonInterestBearingGrp,omitempty"`
	SavingsAndTempCashInvstGrp     *Form990PartXGroup1Type              `xml:"SavingsAndTempCashInvstGrp,omitempty"`
	PledgesAndGrantsReceivableGrp  *Form990PartXGroup1Type              `xml:"PledgesAndGrantsReceivableGrp,omitempty"`
	AccountsReceivableGrp          *Form990PartXGroup1Type              `xml:"AccountsReceivableGrp,omitempty"`
	ReceivablesFromOfficersEtcGrp  *Form990PartXGroup1Type              `xml:"ReceivablesFromOfficersEtcGrp,omitempty"`
	RcvblFromDisqualifiedPrsnGrp   *Form990PartXGroup1Type              `xml:"RcvblFromDisqualifiedPrsnGrp,omitempty"`
	OthNotesLoansReceivableNetGrp  *Form990PartXGroup1Type              `xml:"OthNotesLoansReceivableNetGrp,omitempty"`
	InventoriesForSaleOrUseGrp     *Form990PartXGroup1Type              `xml:"InventoriesForSaleOrUseGrp,omitempty"`
	PrepaidExpensesDefrdChargesGrp *Form990PartXGroup1Type              `xml:"PrepaidExpensesDefrdChargesGrp,omitempty"`
	LandBldgEquipCostOrOtherBssAmt int                                  `xml:"LandBldgEquipCostOrOtherBssAmt,omitempty"`
	LandBldgEquipAccumDeprecAmt    int                                  `xml:"LandBldgEquipAccumDeprecAmt,omitempty"`
	LandBldgEquipBasisNetGrp       *Form990PartXGroup1Type              `xml:"LandBldgEquipBasisNetGrp,omitempty"`
	InvestmentsPubTradedSecGrp     *Form990PartXGroup1Type              `xml:"InvestmentsPubTradedSecGrp,omitempty"`
	InvestmentsOtherSecuritiesGrp  *Form990PartXGroup1Type              `xml:"InvestmentsOtherSecuritiesGrp,omitempty"`
	InvestmentsProgramRelatedGrp   *Form990PartXGroup1Type              `xml:"InvestmentsProgramRelatedGrp,omitempty"`
	IntangibleAssetsGrp            *Form990PartXGroup1Type              `xml:"IntangibleAssetsGrp,omitempty"`
	OtherAssetsTotalGrp            *Form990PartXGroup1Type              `xml:"OtherAssetsTotalGrp,omitempty"`
	TotalAssetsGrp                 *Form990PartXGroup2Type              `xml:"TotalAssetsGrp"`
	AccountsPayableAccrExpnssGrp   *Form990PartXGroup1Type              `xml:"AccountsPayableAccrExpnssGrp,omitempty"`
	GrantsPayableGrp               *Form990PartXGroup1Type              `xml:"GrantsPayableGrp,omitempty"`
	DeferredRevenueGrp             *Form990PartXGroup1Type              `xml:"DeferredRevenueGrp,omitempty"`
	TaxExemptBondLiabilitiesGrp    *Form990PartXGroup1Type              `xml:"TaxExemptBondLiabilitiesGrp,omitempty"`
	EscrowAccountLiabilityGrp      *Form990PartXGroup1Type              `xml:"EscrowAccountLiabilityGrp,omitempty"`
	LoansFromOfficersDirectorsGrp  *Form990PartXGroup1Type              `xml:"LoansFromOfficersDirectorsGrp,omitempty"`
	MortgNotesPyblScrdInvstPropGrp *Form990PartXGroup1Type              `xml:"MortgNotesPyblScrdInvstPropGrp,omitempty"`
	UnsecuredNotesLoansPayableGrp  *Form990PartXGroup1Type              `xml:"UnsecuredNotesLoansPayableGrp,omitempty"`
	OtherLiabilitiesGrp            *Form990PartXGroup1Type              `xml:"OtherLiabilitiesGrp,omitempty"`
	TotalLiabilitiesGrp            *Form990PartXGroup2Type              `xml:"TotalLiabilitiesGrp"`
	OrganizationFollowsFASB117Ind  string                               `xml:"OrganizationFollowsFASB117Ind,omitempty"`
	NoDonorRestrictionNetAssetsGrp *Form990PartXGroup1Type              `xml:"NoDonorRestrictionNetAssetsGrp,omitempty"`
	DonorRestrictionNetAssetsGrp   *Form990PartXGroup1Type              `xml:"DonorRestrictionNetAssetsGrp,omitempty"`
	OrgDoesNotFollowFASB117Ind     string                               `xml:"OrgDoesNotFollowFASB117Ind,omitempty"`
	CapStkTrPrinCurrentFundsGrp    *Form990PartXGroup1Type              `xml:"CapStkTrPrinCurrentFundsGrp,omitempty"`
	PdInCapSrplsLandBldgEqpFundGrp *Form990PartXGroup1Type              `xml:"PdInCapSrplsLandBldgEqpFundGrp,omitempty"`
	RtnEarnEndowmentIncmOthFndsGrp *Form990PartXGroup1Type              `xml:"RtnEarnEndowmentIncmOthFndsGrp,omitempty"`
	TotalNetAssetsFundBalanceGrp   *Form990PartXGroup2Type              `xml:"TotalNetAssetsFundBalanceGrp"`
	TotLiabNetAssetsFundBalanceGrp *Form990PartXGroup2Type              `xml:"TotLiabNetAssetsFundBalanceGrp"`
	InfoInScheduleOPartXIInd       string                               `xml:"InfoInScheduleOPartXIInd,omitempty"`
	ReconcilationRevenueExpnssAmt  int                                  `xml:"ReconcilationRevenueExpnssAmt"`
	NetUnrlzdGainsLossesInvstAmt   int                                  `xml:"NetUnrlzdGainsLossesInvstAmt,omitempty"`
	DonatedServicesAndUseFcltsAmt  int                                  `xml:"DonatedServicesAndUseFcltsAmt,omitempty"`
	InvestmentExpenseAmt           int                                  `xml:"InvestmentExpenseAmt,omitempty"`
	PriorPeriodAdjustmentsAmt      int                                  `xml:"PriorPeriodAdjustmentsAmt,omitempty"`
	OtherChangesInNetAssetsAmt     int                                  `xml:"OtherChangesInNetAssetsAmt,omitempty"`
	InfoInScheduleOPartXIIInd      string                               `xml:"InfoInScheduleOPartXIIInd,omitempty"`
	MethodOfAccountingCashInd      string                               `xml:"MethodOfAccountingCashInd"`
	MethodOfAccountingAccrualInd   string                               `xml:"MethodOfAccountingAccrualInd"`
	MethodOfAccountingOtherInd     *MethodOfAccountingOtherInd          `xml:"MethodOfAccountingOtherInd"`
	AccountantCompileOrReviewInd   bool                                 `xml:"AccountantCompileOrReviewInd"`
	AcctCompileOrReviewBasisGrp    *FinancialStatementType              `xml:"AcctCompileOrReviewBasisGrp,omitempty"`
	FSAuditedInd                   bool                                 `xml:"FSAuditedInd"`
	FSAuditedBasisGrp              *FinancialStatementType              `xml:"FSAuditedBasisGrp,omitempty"`
	AuditCommitteeInd              bool                                 `xml:"AuditCommitteeInd,omitempty"`
	FederalGrantAuditRequiredInd   bool                                 `xml:"FederalGrantAuditRequiredInd,omitempty"`
	FederalGrantAuditPerformedInd  bool                                 `xml:"FederalGrantAuditPerformedInd,omitempty"`
}

// ProgSrvcAccomplishmentActyGrpType is Part III
type ProgSrvcAccomplishmentActyGrpType struct {
	ActivityCd int    `xml:"ActivityCd,omitempty"`
	ExpenseAmt int    `xml:"ExpenseAmt,omitempty"`
	GrantAmt   int    `xml:"GrantAmt,omitempty"`
	RevenueAmt int    `xml:"RevenueAmt,omitempty"`
	Desc       string `xml:"Desc,omitempty"`
}

// ContractorName is Part VII Section B Line 1(A)
type ContractorName struct {
	PersonNm     string            `xml:"PersonNm"`
	BusinessName *BusinessNameType `xml:"BusinessName"`
}

// ContractorAddress is Address of contractor
type ContractorAddress struct {
	USAddress      *USAddressType      `xml:"USAddress"`
	ForeignAddress *ForeignAddressType `xml:"ForeignAddress"`
}

// Form990PartVIIGroup1Type ...
type Form990PartVIIGroup1Type struct {
	ContractorName    *ContractorName    `xml:"ContractorName,omitempty"`
	ContractorAddress *ContractorAddress `xml:"ContractorAddress,omitempty"`
	ServicesDesc      string             `xml:"ServicesDesc,omitempty"`
	CompensationAmt   int                `xml:"CompensationAmt,omitempty"`
}

// Form990PartVIIIMainGroup ...
type Form990PartVIIIMainGroup struct {
	TotalRevenueColumnAmt        int
	RelatedOrExemptFuncIncomeAmt int
	UnrelatedBusinessRevenueAmt  int
	ExclusionAmt                 int
}

// Form990PartVIIIGroup3Type ...
type Form990PartVIIIGroup3Type struct {
	Form990PartVIIIMainGroup *Form990PartVIIIMainGroup
}

// Form990PartVIIIGroup4Type is Part VIII Column (ii)
type Form990PartVIIIGroup4Type struct {
	RealAmt     int `xml:"RealAmt,omitempty"`
	PersonalAmt int `xml:"PersonalAmt,omitempty"`
}

// Form990PartVIIIGroup5Type is Part VIII Column (ii)
type Form990PartVIIIGroup5Type struct {
	SecuritiesAmt int `xml:"SecuritiesAmt,omitempty"`
	OtherAmt      int `xml:"OtherAmt,omitempty"`
}

// Form990PartVIIIGroup6Type is Part VIII Column (D)
type Form990PartVIIIGroup6Type struct {
	TotalRevenueColumnAmt        int `xml:"TotalRevenueColumnAmt"`
	RelatedOrExemptFuncIncomeAmt int `xml:"RelatedOrExemptFuncIncomeAmt,omitempty"`
	UnrelatedBusinessRevenueAmt  int `xml:"UnrelatedBusinessRevenueAmt,omitempty"`
	ExclusionAmt                 int `xml:"ExclusionAmt,omitempty"`
}

// Form990PartVIIIGroup7Type is Part VIII Column (D)
type Form990PartVIIIGroup7Type struct {
	TotalRevenueColumnAmt       int `xml:"TotalRevenueColumnAmt"`
	UnrelatedBusinessRevenueAmt int `xml:"UnrelatedBusinessRevenueAmt,omitempty"`
	ExclusionAmt                int `xml:"ExclusionAmt,omitempty"`
}

// Form990PartIXGroup1Type ...
type Form990PartIXGroup1Type struct {
	TotalAmt            int `xml:"TotalAmt"`
	ProgramServicesAmt  int `xml:"ProgramServicesAmt,omitempty"`
}

// Form990PartIXGroup2Type ...
type Form990PartIXGroup2Type struct {
	TotalAmt            int `xml:"TotalAmt"`
	ProgramServicesAmt  int `xml:"ProgramServicesAmt,omitempty"`
	ManagementAndGeneralAmt  int `xml:"ManagementAndGeneralAmt,omitempty"`
	FundraisingAmt  int `xml:"FundraisingAmt,omitempty"`
}

// Form990PartIXGroup3Type is col (B)
type Form990PartIXGroup3Type struct {
	TotalAmt            int `xml:"TotalAmt"`
	ProgramServicesAmt  int `xml:"ProgramServicesAmt,omitempty"`
	ManagementAndGeneralAmt  int `xml:"ManagementAndGeneralAmt,omitempty"`
	FundraisingAmt  int `xml:"FundraisingAmt,omitempty"`
}

// Form990PartIXGroup4Type is Description
type Form990PartIXGroup4Type struct {
	TotalAmt            int `xml:"TotalAmt"`
	ProgramServicesAmt  int `xml:"ProgramServicesAmt,omitempty"`
	ManagementAndGeneralAmt  int `xml:"ManagementAndGeneralAmt,omitempty"`
	FundraisingAmt  int `xml:"FundraisingAmt,omitempty"`
	Desc                string `xml:"Desc,omitempty"`
}

// Form990PartXGroup1Type is Part X Column (B)
type Form990PartXGroup1Type struct {
	BOYAmt int `xml:"BOYAmt,omitempty"`
	EOYAmt int `xml:"EOYAmt,omitempty"`
}

// Form990PartXGroup2Type is Part X Column (B)
type Form990PartXGroup2Type struct {
	BOYAmt int `xml:"BOYAmt"`
	EOYAmt int `xml:"EOYAmt"`
}

// FinancialStatementType is Part XII Lines 2a and 2b
type FinancialStatementType struct {
	SeparateBasisFinclStmtInd     string `xml:"SeparateBasisFinclStmtInd"`
	ConsolidatedBasisFinclStmtInd string `xml:"ConsolidatedBasisFinclStmtInd"`
	ConsolAndSepBasisFinclStmtInd string `xml:"ConsolAndSepBasisFinclStmtInd"`
}

type Form990PartVIIIGroup2Type struct {
	Desc string `xml:"Desc,omitempty"`
	BusinessCd string `xml:"BusinessCd,omitempty"`
	TotalRevenueColumnAmt int `xml:"TotalRevenueColumnAmt,omitempty"`
	RelatedOrExemptFuncIncomeAmt int `xml:"RelatedOrExemptFuncIncomeAmt,omitempty"`
}

// CountType ...
type CountType int
