// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990ScheduleH is Common return document attributes
type IRS990ScheduleH struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*IRS990ScheduleHType
}

// FreeCareOthPercentageGrp is Part I Line 3a
type FreeCareOthPercentageGrp struct {
	OtherInd         string  `xml:"OtherInd"`
	FreeCareOtherPct float64 `xml:"FreeCareOtherPct"`
}

// DiscountedCareOthPercentageGrp ...
type DiscountedCareOthPercentageGrp struct {
	OtherInd               string  `xml:"OtherInd"`
	DiscountedCareOtherPct float64 `xml:"DiscountedCareOtherPct"`
}

// CostingMethodologyUsedGrp is Checkbox choice
type CostingMethodologyUsedGrp struct {
	CostAccountingSystemInd string `xml:"CostAccountingSystemInd"`
	CostToChargeRatioInd    string `xml:"CostToChargeRatioInd"`
	OtherInd                string `xml:"OtherInd"`
}

// ManagementCoAndJntVenturesGrp is Part IV repeating group
type ManagementCoAndJntVenturesGrp struct {
	EntityName                     *BusinessNameType `xml:"EntityName,omitempty"`
	PrimaryActivitiesTxt           string            `xml:"PrimaryActivitiesTxt,omitempty"`
	OrgProfitOrOwnershipPct        float64           `xml:"OrgProfitOrOwnershipPct,omitempty"`
	OfcrEtcProfitOrOwnershipPct    float64           `xml:"OfcrEtcProfitOrOwnershipPct,omitempty"`
	PhysiciansProfitOrOwnershipPct float64           `xml:"PhysiciansProfitOrOwnershipPct,omitempty"`
}

// HospitalFacilitiesGrp is Part V Section A repeating group
type HospitalFacilitiesGrp struct {
	FacilityNum                  int               `xml:"FacilityNum"`
	BusinessName                 *BusinessNameType `xml:"BusinessName,omitempty"`
	USAddress                    *USAddressType    `xml:"USAddress,omitempty"`
	WebsiteAddressTxt            string            `xml:"WebsiteAddressTxt,omitempty"`
	StateLicenseNum              interface{}       `xml:"StateLicenseNum,omitempty"`
	SubordinateHospitalName      *BusinessNameType `xml:"SubordinateHospitalName,omitempty"`
	SubordinateHospitalEIN       string            `xml:"SubordinateHospitalEIN,omitempty"`
	LicensedHospitalInd          string            `xml:"LicensedHospitalInd,omitempty"`
	GeneralMedicalAndSurgicalInd string            `xml:"GeneralMedicalAndSurgicalInd,omitempty"`
	ChildrensHospitalInd         string            `xml:"ChildrensHospitalInd,omitempty"`
	TeachingHospitalInd          string            `xml:"TeachingHospitalInd,omitempty"`
	CriticalAccessHospitalInd    string            `xml:"CriticalAccessHospitalInd,omitempty"`
	ResearchFacilityInd          string            `xml:"ResearchFacilityInd,omitempty"`
	EmergencyRoom24HrsInd        string            `xml:"EmergencyRoom24HrsInd,omitempty"`
	EmergencyRoomOtherInd        string            `xml:"EmergencyRoomOtherInd,omitempty"`
	OtherDesc                    string            `xml:"OtherDesc,omitempty"`
	FacilityReportingGroupCd     interface{}       `xml:"FacilityReportingGroupCd,omitempty"`
}

// StrategyAttachedInd is Part V Section B Line 10b
type StrategyAttachedInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// HospitalFcltyPoliciesPrctcGrp is Part V Section B repeating group
type HospitalFcltyPoliciesPrctcGrp struct {
	HospitalFacilityName           *BusinessNameType    `xml:"HospitalFacilityName,omitempty"`
	FacilityNum                    int                  `xml:"FacilityNum,omitempty"`
	FirstLicensedCYOrPYInd         bool                 `xml:"FirstLicensedCYOrPYInd"`
	TaxExemptHospitalCYOrPYInd     bool                 `xml:"TaxExemptHospitalCYOrPYInd"`
	CHNAConductedInd               bool                 `xml:"CHNAConductedInd"`
	CommunityDefinitionInd         string               `xml:"CommunityDefinitionInd,omitempty"`
	CommunityDemographicsInd       string               `xml:"CommunityDemographicsInd,omitempty"`
	ExistingResourcesInd           string               `xml:"ExistingResourcesInd,omitempty"`
	HowDataObtainedInd             string               `xml:"HowDataObtainedInd,omitempty"`
	CommunityHealthNeedsInd        string               `xml:"CommunityHealthNeedsInd,omitempty"`
	OtherHealthIssuesInd           string               `xml:"OtherHealthIssuesInd,omitempty"`
	CommunityHlthNeedsIdProcessInd string               `xml:"CommunityHlthNeedsIdProcessInd,omitempty"`
	ConsultingProcessInd           string               `xml:"ConsultingProcessInd,omitempty"`
	PriorCHNAImpactInd             string               `xml:"PriorCHNAImpactInd,omitempty"`
	OtherInd                       string               `xml:"OtherInd,omitempty"`
	CHNAConductedYr                interface{}          `xml:"CHNAConductedYr,omitempty"`
	TakeIntoAccountOthersInputInd  bool                 `xml:"TakeIntoAccountOthersInputInd,omitempty"`
	CHNAConductedWithOtherFcltsInd bool                 `xml:"CHNAConductedWithOtherFcltsInd,omitempty"`
	CHNAConductedWithNonFcltsInd   bool                 `xml:"CHNAConductedWithNonFcltsInd,omitempty"`
	CHNAReportWidelyAvailableInd   bool                 `xml:"CHNAReportWidelyAvailableInd,omitempty"`
	RptAvailableOnOwnWebsiteInd    string               `xml:"RptAvailableOnOwnWebsiteInd,omitempty"`
	OwnWebsiteURLTxt               string               `xml:"OwnWebsiteURLTxt,omitempty"`
	OtherWebsiteInd                string               `xml:"OtherWebsiteInd,omitempty"`
	OtherWebsiteURLTxt             string               `xml:"OtherWebsiteURLTxt,omitempty"`
	PaperCopyPublicInspectionInd   string               `xml:"PaperCopyPublicInspectionInd,omitempty"`
	RptAvailableThruOtherMethodInd string               `xml:"RptAvailableThruOtherMethodInd,omitempty"`
	ImplementationStrategyAdoptInd bool                 `xml:"ImplementationStrategyAdoptInd,omitempty"`
	ImplementationStrategyAdptYr   interface{}          `xml:"ImplementationStrategyAdptYr,omitempty"`
	StrategyPostedWebsiteInd       bool                 `xml:"StrategyPostedWebsiteInd,omitempty"`
	StrategyWebsiteURLTxt          string               `xml:"StrategyWebsiteURLTxt,omitempty"`
	StrategyAttachedInd            *StrategyAttachedInd `xml:"StrategyAttachedInd,omitempty"`
	OrganizationIncurExciseTaxInd  bool                 `xml:"OrganizationIncurExciseTaxInd,omitempty"`
	Form4720FiledInd               bool                 `xml:"Form4720FiledInd,omitempty"`
	ExciseReportForm4720ForAllAmt  int                  `xml:"ExciseReportForm4720ForAllAmt,omitempty"`
	EligCriteriaExplainedInd       bool                 `xml:"EligCriteriaExplainedInd"`
	FPGFamilyIncmLmtFreeDscntInd   string               `xml:"FPGFamilyIncmLmtFreeDscntInd,omitempty"`
	FPGFamilyIncmLmtFreeCarePct    float64              `xml:"FPGFamilyIncmLmtFreeCarePct,omitempty"`
	FPGFamilyIncmLmtDscntCarePct   float64              `xml:"FPGFamilyIncmLmtDscntCarePct,omitempty"`
	IncomeLevelCriteriaInd         string               `xml:"IncomeLevelCriteriaInd,omitempty"`
	AssetLevelCriteriaInd          string               `xml:"AssetLevelCriteriaInd,omitempty"`
	MedicalIndigencyCriteriaInd    string               `xml:"MedicalIndigencyCriteriaInd,omitempty"`
	InsuranceStatusCriteriaInd     string               `xml:"InsuranceStatusCriteriaInd,omitempty"`
	UnderinsuranceStatCriteriaInd  string               `xml:"UnderinsuranceStatCriteriaInd,omitempty"`
	ResidencyCriteriaInd           string               `xml:"ResidencyCriteriaInd,omitempty"`
	OtherCriteriaInd               string               `xml:"OtherCriteriaInd,omitempty"`
	ExplainedBasisInd              bool                 `xml:"ExplainedBasisInd"`
	AppFinancialAsstExplnInd       bool                 `xml:"AppFinancialAsstExplnInd"`
	DescribedInfoInd               string               `xml:"DescribedInfoInd,omitempty"`
	DescribedSuprtDocInd           string               `xml:"DescribedSuprtDocInd,omitempty"`
	ProvidedHospitalContactInd     string               `xml:"ProvidedHospitalContactInd,omitempty"`
	ProvidedNonprofitContactInd    string               `xml:"ProvidedNonprofitContactInd,omitempty"`
	OtherMethodInd                 string               `xml:"OtherMethodInd,omitempty"`
	IncludesPublicityMeasuresInd   bool                 `xml:"IncludesPublicityMeasuresInd"`
	FAPAvailableOnWebsiteInd       string               `xml:"FAPAvailableOnWebsiteInd,omitempty"`
	FAPAvailableOnWebsiteURLTxt    string               `xml:"FAPAvailableOnWebsiteURLTxt,omitempty"`
	FAPAppAvailableOnWebsiteInd    string               `xml:"FAPAppAvailableOnWebsiteInd,omitempty"`
	FAPAppAvailableOnWebsiteURLTxt string               `xml:"FAPAppAvailableOnWebsiteURLTxt,omitempty"`
	FAPSummaryOnWebsiteInd         string               `xml:"FAPSummaryOnWebsiteInd,omitempty"`
	FAPSummaryOnWebsiteURLTxt      string               `xml:"FAPSummaryOnWebsiteURLTxt,omitempty"`
	FAPAvlblOnRequestNoChargeInd   string               `xml:"FAPAvlblOnRequestNoChargeInd,omitempty"`
	FAPAppAvlblOnRequestNoChrgInd  string               `xml:"FAPAppAvlblOnRequestNoChrgInd,omitempty"`
	FAPSumAvlblOnRequestNoChrgInd  string               `xml:"FAPSumAvlblOnRequestNoChrgInd,omitempty"`
	NotifiedFAPCopyBillDisplayInd  string               `xml:"NotifiedFAPCopyBillDisplayInd,omitempty"`
	CommuntityNotifiedFAPInd       string               `xml:"CommuntityNotifiedFAPInd,omitempty"`
	FAPTranslatedInd               string               `xml:"FAPTranslatedInd,omitempty"`
	OtherPublicityInd              string               `xml:"OtherPublicityInd,omitempty"`
	FAPActionsOnNonpaymentInd      bool                 `xml:"FAPActionsOnNonpaymentInd"`
	PermitReportToCreditAgencyInd  string               `xml:"PermitReportToCreditAgencyInd,omitempty"`
	PermitSellingDebtInd           string               `xml:"PermitSellingDebtInd,omitempty"`
	PermitDeferDenyRqrPaymentInd   string               `xml:"PermitDeferDenyRqrPaymentInd,omitempty"`
	PermitLegalJudicialProcessInd  string               `xml:"PermitLegalJudicialProcessInd,omitempty"`
	PermitOtherActionsInd          string               `xml:"PermitOtherActionsInd,omitempty"`
	PermitNoActionsInd             string               `xml:"PermitNoActionsInd,omitempty"`
	CollectionActivitiesInd        bool                 `xml:"CollectionActivitiesInd"`
	ReportingToCreditAgencyInd     string               `xml:"ReportingToCreditAgencyInd,omitempty"`
	EngagedSellingDebtInd          string               `xml:"EngagedSellingDebtInd,omitempty"`
	EngageDeferDenyRqrPaymentInd   string               `xml:"EngageDeferDenyRqrPaymentInd,omitempty"`
	EngagedLegalJudicialProcessInd string               `xml:"EngagedLegalJudicialProcessInd,omitempty"`
	OtherActionsInd                string               `xml:"OtherActionsInd,omitempty"`
	ProvidedWrittenNoticeInd       string               `xml:"ProvidedWrittenNoticeInd,omitempty"`
	MadeEffortOrallyNotifyInd      string               `xml:"MadeEffortOrallyNotifyInd,omitempty"`
	ProcessedFAPApplicationInd     string               `xml:"ProcessedFAPApplicationInd,omitempty"`
	MadePresumptiveEligDetermInd   string               `xml:"MadePresumptiveEligDetermInd,omitempty"`
	OtherActionsTakenInd           string               `xml:"OtherActionsTakenInd,omitempty"`
	NoneMadeInd                    string               `xml:"NoneMadeInd,omitempty"`
	NondisEmergencyCarePolicyInd   bool                 `xml:"NondisEmergencyCarePolicyInd"`
	NoEmergencyCareInd             string               `xml:"NoEmergencyCareInd,omitempty"`
	NoEmergencyCarePolicyInd       string               `xml:"NoEmergencyCarePolicyInd,omitempty"`
	EmergencyCareLimitedInd        string               `xml:"EmergencyCareLimitedInd,omitempty"`
	OtherReasonInd                 string               `xml:"OtherReasonInd,omitempty"`
	LookBackMedicareInd            string               `xml:"LookBackMedicareInd,omitempty"`
	LookBackMedicarePrivateInd     string               `xml:"LookBackMedicarePrivateInd,omitempty"`
	LookBackMedicaidMedcrPrvtInd   string               `xml:"LookBackMedicaidMedcrPrvtInd,omitempty"`
	ProspectiveMedicareMedicaidInd string               `xml:"ProspectiveMedicareMedicaidInd,omitempty"`
	AmountsGenerallyBilledInd      bool                 `xml:"AmountsGenerallyBilledInd"`
	GrossChargesInd                bool                 `xml:"GrossChargesInd"`
}

// SupplementalInformationGrp is Part V Section C, Supplemental Information for Part V Section B
type SupplementalInformationGrp struct {
	FormAndLineReferenceDesc string `xml:"FormAndLineReferenceDesc,omitempty"`
	ExplanationTxt           string `xml:"ExplanationTxt,omitempty"`
}

// OthHlthCareFcltsGrp is Part V Section D repeating group
type OthHlthCareFcltsGrp struct {
	BusinessName *BusinessNameType `xml:"BusinessName"`
	USAddress    *USAddressType    `xml:"USAddress"`
	FacilityTxt  string            `xml:"FacilityTxt"`
}

// OthHlthCareFcltsNotHospitalGrp is Part V section D, other health care facilities
type OthHlthCareFcltsNotHospitalGrp struct {
	OthHlthCareFcltsGrp []*OthHlthCareFcltsGrp `xml:"OthHlthCareFcltsGrp"`
}


// IRS990ScheduleHType is Part I Line 3a
type IRS990ScheduleHType struct {
	FinancialAssistancePolicyInd   bool                             `xml:"FinancialAssistancePolicyInd,omitempty"`
	WrittenPolicyInd               bool                             `xml:"WrittenPolicyInd,omitempty"`
	AllHospitalsPolicyInd          string                           `xml:"AllHospitalsPolicyInd"`
	MostHospitalsPolicyInd         string                           `xml:"MostHospitalsPolicyInd"`
	IndivHospitalTailoredPolicyInd string                           `xml:"IndivHospitalTailoredPolicyInd"`
	FPGReferenceFreeCareInd        bool                             `xml:"FPGReferenceFreeCareInd,omitempty"`
	Percent100Ind                  string                           `xml:"Percent100Ind"`
	Percent150Ind                  string                           `xml:"Percent150Ind"`
	Percent200Ind                  string                           `xml:"Percent200Ind"`
	FreeCareOthPercentageGrp       *FreeCareOthPercentageGrp        `xml:"FreeCareOthPercentageGrp"`
	FPGReferenceDiscountedCareInd  bool                             `xml:"FPGReferenceDiscountedCareInd,omitempty"`
	Percent200DInd                 string                           `xml:"Percent200DInd"`
	Percent250Ind                  string                           `xml:"Percent250Ind"`
	Percent300Ind                  string                           `xml:"Percent300Ind"`
	Percent350Ind                  string                           `xml:"Percent350Ind"`
	Percent400Ind                  string                           `xml:"Percent400Ind"`
	DiscountedCareOthPercentageGrp *DiscountedCareOthPercentageGrp  `xml:"DiscountedCareOthPercentageGrp"`
	FreeCareMedicallyIndigentInd   bool                             `xml:"FreeCareMedicallyIndigentInd,omitempty"`
	FinancialAssistanceBudgetInd   bool                             `xml:"FinancialAssistanceBudgetInd,omitempty"`
	ExpensesExceedBudgetInd        bool                             `xml:"ExpensesExceedBudgetInd,omitempty"`
	UnableToProvideCareInd         bool                             `xml:"UnableToProvideCareInd,omitempty"`
	AnnualCommunityBnftReportInd   bool                             `xml:"AnnualCommunityBnftReportInd,omitempty"`
	ReportPublicallyAvailableInd   bool                             `xml:"ReportPublicallyAvailableInd,omitempty"`
	FinancialAssistanceAtCostTyp   *Form990SchHPartIGroup1Type      `xml:"FinancialAssistanceAtCostTyp,omitempty"`
	UnreimbursedMedicaidGrp        *Form990SchHPartIGroup1Type      `xml:"UnreimbursedMedicaidGrp,omitempty"`
	UnreimbursedCostsGrp           *Form990SchHPartIGroup1Type      `xml:"UnreimbursedCostsGrp,omitempty"`
	TotalFinancialAssistanceTyp    *Form990SchHPartIGroup1Type      `xml:"TotalFinancialAssistanceTyp,omitempty"`
	CommunityHealthServicesGrp     *Form990SchHPartIGroup1Type      `xml:"CommunityHealthServicesGrp,omitempty"`
	HealthProfessionsEducationGrp  *Form990SchHPartIGroup1Type      `xml:"HealthProfessionsEducationGrp,omitempty"`
	SubsidizedHealthServicesGrp    *Form990SchHPartIGroup1Type      `xml:"SubsidizedHealthServicesGrp,omitempty"`
	ResearchGrp                    *Form990SchHPartIGroup1Type      `xml:"ResearchGrp,omitempty"`
	CashAndInKindContributionsGrp  *Form990SchHPartIGroup1Type      `xml:"CashAndInKindContributionsGrp,omitempty"`
	TotalOtherBenefitsGrp          *Form990SchHPartIGroup1Type      `xml:"TotalOtherBenefitsGrp,omitempty"`
	TotalCommunityBenefitsGrp      *Form990SchHPartIGroup1Type      `xml:"TotalCommunityBenefitsGrp,omitempty"`
	PhysicalImprvAndHousingGrp     *Form990SchHPartIIGroup1Type     `xml:"PhysicalImprvAndHousingGrp,omitempty"`
	EconomicDevelopmentGrp         *Form990SchHPartIIGroup1Type     `xml:"EconomicDevelopmentGrp,omitempty"`
	CommunitySupportGrp            *Form990SchHPartIIGroup1Type     `xml:"CommunitySupportGrp,omitempty"`
	EnvironmentalImprovementsGrp   *Form990SchHPartIIGroup1Type     `xml:"EnvironmentalImprovementsGrp,omitempty"`
	LeadershipDevelopmentGrp       *Form990SchHPartIIGroup1Type     `xml:"LeadershipDevelopmentGrp,omitempty"`
	CoalitionBuildingGrp           *Form990SchHPartIIGroup1Type     `xml:"CoalitionBuildingGrp,omitempty"`
	HealthImprovementAdvocacyGrp   *Form990SchHPartIIGroup1Type     `xml:"HealthImprovementAdvocacyGrp,omitempty"`
	WorkforceDevelopmentGrp        *Form990SchHPartIIGroup1Type     `xml:"WorkforceDevelopmentGrp,omitempty"`
	OtherCommuntityBuildingActyGrp *Form990SchHPartIIGroup1Type     `xml:"OtherCommuntityBuildingActyGrp,omitempty"`
	TotalCommuntityBuildingActyGrp *Form990SchHPartIIGroup1Type     `xml:"TotalCommuntityBuildingActyGrp,omitempty"`
	BadDebtExpenseReportedInd      bool                             `xml:"BadDebtExpenseReportedInd,omitempty"`
	BadDebtExpenseAmt              int                              `xml:"BadDebtExpenseAmt,omitempty"`
	BadDebtExpenseAttributableAmt  int                              `xml:"BadDebtExpenseAttributableAmt,omitempty"`
	ReimbursedByMedicareAmt        int                              `xml:"ReimbursedByMedicareAmt,omitempty"`
	CostOfCareReimbursedByMedcrAmt int                              `xml:"CostOfCareReimbursedByMedcrAmt,omitempty"`
	MedicareSurplusOrShortfallAmt  int                              `xml:"MedicareSurplusOrShortfallAmt,omitempty"`
	CostingMethodologyUsedGrp      *CostingMethodologyUsedGrp       `xml:"CostingMethodologyUsedGrp,omitempty"`
	WrittenDebtCollectionPolicyInd bool                             `xml:"WrittenDebtCollectionPolicyInd,omitempty"`
	FinancialAssistancePrvsnInd    bool                             `xml:"FinancialAssistancePrvsnInd,omitempty"`
	ManagementCoAndJntVenturesGrp  []*ManagementCoAndJntVenturesGrp `xml:"ManagementCoAndJntVenturesGrp,omitempty"`
	HospitalFacilitiesCnt          int                              `xml:"HospitalFacilitiesCnt"`
	HospitalFacilitiesGrp          []*HospitalFacilitiesGrp         `xml:"HospitalFacilitiesGrp"`
	HospitalFcltyPoliciesPrctcGrp  []*HospitalFcltyPoliciesPrctcGrp `xml:"HospitalFcltyPoliciesPrctcGrp,omitempty"`
	SupplementalInformationGrp     []*SupplementalInformationGrp    `xml:"SupplementalInformationGrp,omitempty"`
	FacilityNum                    int                              `xml:"FacilityNum,omitempty"`
	OthHlthCareFcltsNotHospitalGrp *OthHlthCareFcltsNotHospitalGrp  `xml:"OthHlthCareFcltsNotHospitalGrp,omitempty"`
	SupplementalInformationDetail  []*SupplementalInformationDetail `xml:"SupplementalInformationDetail,omitempty"`
}

// Form990SchHPartIGroup1Type is Column (f)
type Form990SchHPartIGroup1Type struct {
	ActivitiesOrProgramsCnt       int     `xml:"ActivitiesOrProgramsCnt,omitempty"`
	PersonsServedCnt              int     `xml:"PersonsServedCnt,omitempty"`
	TotalCommunityBenefitExpnsAmt int     `xml:"TotalCommunityBenefitExpnsAmt,omitempty"`
	DirectOffsettingRevenueAmt    int     `xml:"DirectOffsettingRevenueAmt,omitempty"`
	NetCommunityBenefitExpnsAmt   int     `xml:"NetCommunityBenefitExpnsAmt,omitempty"`
	TotalExpensePct               float64 `xml:"TotalExpensePct,omitempty"`
}

// Form990SchHPartIIGroup1Type is Column (f)
type Form990SchHPartIIGroup1Type struct {
	ActivitiesOrProgramsCnt       int     `xml:"ActivitiesOrProgramsCnt,omitempty"`
	PersonsServedCnt              int     `xml:"PersonsServedCnt,omitempty"`
	TotalCommunityBenefitExpnsAmt int     `xml:"TotalCommunityBenefitExpnsAmt,omitempty"`
	DirectOffsettingRevenueAmt    int     `xml:"DirectOffsettingRevenueAmt,omitempty"`
	NetCommunityBenefitExpnsAmt   int     `xml:"NetCommunityBenefitExpnsAmt,omitempty"`
	TotalExpensePct               float64 `xml:"TotalExpensePct,omitempty"`
}

// Count2Type ...
type Count2Type int
