// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990ScheduleL is Common return document attributes
type IRS990ScheduleL struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*IRS990ScheduleLType
}

// GrntAsstBnftInterestedPrsnGrp is Part III Column (e)
type GrntAsstBnftInterestedPrsnGrp struct {
	PersonNm               string            `xml:"PersonNm"`
	BusinessName           *BusinessNameType `xml:"BusinessName"`
	RelationshipWithOrgTxt string            `xml:"RelationshipWithOrgTxt,omitempty"`
	CashGrantAmt           int               `xml:"CashGrantAmt,omitempty"`
	TypeOfAssistanceTxt    string            `xml:"TypeOfAssistanceTxt,omitempty"`
	AssistancePurposeTxt   string            `xml:"AssistancePurposeTxt,omitempty"`
}

// NameOfInterested is Name of interested person
type NameOfInterested struct {
	PersonNm     string            `xml:"PersonNm"`
	BusinessName *BusinessNameType `xml:"BusinessName"`
}

// BusTrInvolveInterestedPrsnGrp is Part IV content
type BusTrInvolveInterestedPrsnGrp struct {
	NameOfInterested           *NameOfInterested `xml:"NameOfInterested,omitempty"`
	RelationshipDescriptionTxt string            `xml:"RelationshipDescriptionTxt,omitempty"`
	TransactionAmt             int               `xml:"TransactionAmt,omitempty"`
	TransactionDesc            string            `xml:"TransactionDesc,omitempty"`
	SharingOfRevenuesInd       bool              `xml:"SharingOfRevenuesInd,omitempty"`
}


// IRS990ScheduleLType is Part II Column d
type IRS990ScheduleLType struct {
	DisqualifiedPersonExBnftTrGrp []*DisqualifiedPersonExBnftTrGrpType `xml:"DisqualifiedPersonExBnftTrGrp,omitempty"`
	TaxImposedAmt                 int                                  `xml:"TaxImposedAmt,omitempty"`
	TaxReimbursedAmt              int                                  `xml:"TaxReimbursedAmt,omitempty"`
	LoansBtwnOrgInterestedPrsnGrp []*LoansBtwnOrgInterestedPrsnGrpType `xml:"LoansBtwnOrgInterestedPrsnGrp,omitempty"`
	TotalBalanceDueAmt            int                                  `xml:"TotalBalanceDueAmt,omitempty"`
	GrntAsstBnftInterestedPrsnGrp []*GrntAsstBnftInterestedPrsnGrp     `xml:"GrntAsstBnftInterestedPrsnGrp,omitempty"`
	BusTrInvolveInterestedPrsnGrp []*BusTrInvolveInterestedPrsnGrp     `xml:"BusTrInvolveInterestedPrsnGrp,omitempty"`
	SupplementalInformationDetail []*SupplementalInformationDetail     `xml:"SupplementalInformationDetail,omitempty"`
}

// DisqualifiedPersonExBnftTrGrpType is Part I Column (1d)
type DisqualifiedPersonExBnftTrGrpType struct {
	PersonNm                    string            `xml:"PersonNm"`
	BusinessName                *BusinessNameType `xml:"BusinessName"`
	RlnDisqualifiedPersonOrgTxt string            `xml:"RlnDisqualifiedPersonOrgTxt,omitempty"`
	TransactionDesc             string            `xml:"TransactionDesc,omitempty"`
	TransactionCorrectedInd     bool              `xml:"TransactionCorrectedInd,omitempty"`
}

// LoansBtwnOrgInterestedPrsnGrpType is Part II Column (i)
type LoansBtwnOrgInterestedPrsnGrpType struct {
	PersonNm                    string            `xml:"PersonNm"`
	BusinessName                *BusinessNameType `xml:"BusinessName"`
	RelationshipWithOrgTxt      string            `xml:"RelationshipWithOrgTxt,omitempty"`
	LoanPurposeTxt              string            `xml:"LoanPurposeTxt,omitempty"`
	LoanToOrganizationInd       string            `xml:"LoanToOrganizationInd"`
	LoanFromOrganizationInd     string            `xml:"LoanFromOrganizationInd"`
	OriginalPrincipalAmt        int               `xml:"OriginalPrincipalAmt,omitempty"`
	BalanceDueAmt               int               `xml:"BalanceDueAmt,omitempty"`
	DefaultInd                  bool              `xml:"DefaultInd,omitempty"`
	BoardOrCommitteeApprovalInd bool              `xml:"BoardOrCommitteeApprovalInd,omitempty"`
	WrittenAgreementInd         bool              `xml:"WrittenAgreementInd,omitempty"`
}
