// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990PF is Common return document attributes
type IRS990PF struct {
	DocumentAttributes                *DocumentAttributes
	DocumentNameAttr                  string      `xml:"documentName,attr,omitempty"`
	ReferenceDocumentIdAttr           *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr         string      `xml:"referenceDocumentName,attr,omitempty"`
	AccountingPeriodChangeCdAttr      string      `xml:"accountingPeriodChangeCd,attr,omitempty"`
	AccountingPeriodChangeApprvCdAttr string      `xml:"accountingPeriodChangeApprvCd,attr,omitempty"`
	*IRS990PFType
}


// NetGainSaleAstRevAndExpnssAmt is Part I Line 6a(a)
type NetGainSaleAstRevAndExpnssAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// GrossProfitRevAndExpnssAmt is Part I Line 10c(a)
type GrossProfitRevAndExpnssAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// OtherIncomeRevAndExpnssAmt is Part I Line 11(a)
type OtherIncomeRevAndExpnssAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// LegalFeesRevAndExpnssAmt is Part I Line 16a(a)
type LegalFeesRevAndExpnssAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// AccountingFeesRevAndExpnssAmt is Part I Line 16b(a)
type AccountingFeesRevAndExpnssAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// OtherProfFeesRevAndExpnssAmt is Part I Line 16c(a)
type OtherProfFeesRevAndExpnssAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// TaxesRevAndExpnssAmt is Part I Line 18(a)
type TaxesRevAndExpnssAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// DeprecAndDpltnRevAndExpnssAmt is Part I Line 19(a)
type DeprecAndDpltnRevAndExpnssAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// OtherExpensesRevAndExpnssAmt is Part I Line 23(a)
type OtherExpensesRevAndExpnssAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// AnalysisOfRevenueAndExpenses ...
type AnalysisOfRevenueAndExpenses struct {
	ContriRcvdRevAndExpnssAmt      int                            `xml:"ContriRcvdRevAndExpnssAmt,omitempty"`
	ScheduleBNotRequiredInd        string                         `xml:"ScheduleBNotRequiredInd,omitempty"`
	InterestOnSavRevAndExpnssAmt   int                            `xml:"InterestOnSavRevAndExpnssAmt,omitempty"`
	InterestOnSavNetInvstIncmAmt   int                            `xml:"InterestOnSavNetInvstIncmAmt,omitempty"`
	InterestOnSavingsAdjNetIncmAmt int                            `xml:"InterestOnSavingsAdjNetIncmAmt,omitempty"`
	DividendsRevAndExpnssAmt       int                            `xml:"DividendsRevAndExpnssAmt,omitempty"`
	DividendsNetInvstIncmAmt       int                            `xml:"DividendsNetInvstIncmAmt,omitempty"`
	DividendsAdjNetIncmAmt         int                            `xml:"DividendsAdjNetIncmAmt,omitempty"`
	GrossRentsRevAndExpnssAmt      int                            `xml:"GrossRentsRevAndExpnssAmt,omitempty"`
	GrossRentsNetInvstIncmAmt      int                            `xml:"GrossRentsNetInvstIncmAmt,omitempty"`
	GrossRentsAdjNetIncmAmt        int                            `xml:"GrossRentsAdjNetIncmAmt,omitempty"`
	NetRentalIncomeOrLossAmt       int                            `xml:"NetRentalIncomeOrLossAmt,omitempty"`
	NetGainSaleAstRevAndExpnssAmt  *NetGainSaleAstRevAndExpnssAmt `xml:"NetGainSaleAstRevAndExpnssAmt,omitempty"`
	GrossSalesPriceAmt             int                            `xml:"GrossSalesPriceAmt,omitempty"`
	CapGainNetIncmNetInvstIncmAmt  int                            `xml:"CapGainNetIncmNetInvstIncmAmt,omitempty"`
	NetSTCapitalGainAdjNetIncmAmt  int                            `xml:"NetSTCapitalGainAdjNetIncmAmt,omitempty"`
	IncmModificationsAdjNetIncmAmt int                            `xml:"IncmModificationsAdjNetIncmAmt,omitempty"`
	GrossSalesLessRetAndAllwncAmt  int                            `xml:"GrossSalesLessRetAndAllwncAmt,omitempty"`
	CostOfGoodsSoldAmt             int                            `xml:"CostOfGoodsSoldAmt,omitempty"`
	GrossProfitRevAndExpnssAmt     *GrossProfitRevAndExpnssAmt    `xml:"GrossProfitRevAndExpnssAmt,omitempty"`
	GrossProfitAdjNetIncmAmt       int                            `xml:"GrossProfitAdjNetIncmAmt,omitempty"`
	OtherIncomeRevAndExpnssAmt     *OtherIncomeRevAndExpnssAmt    `xml:"OtherIncomeRevAndExpnssAmt,omitempty"`
	OtherIncomeNetInvstIncmAmt     int                            `xml:"OtherIncomeNetInvstIncmAmt,omitempty"`
	OtherIncomeAdjNetIncmAmt       int                            `xml:"OtherIncomeAdjNetIncmAmt,omitempty"`
	TotalRevAndExpnssAmt           int                            `xml:"TotalRevAndExpnssAmt"`
	TotalNetInvstIncmAmt           int                            `xml:"TotalNetInvstIncmAmt"`
	TotalAdjNetIncmAmt             int                            `xml:"TotalAdjNetIncmAmt,omitempty"`
	CompOfcrDirTrstRevAndExpnssAmt int                            `xml:"CompOfcrDirTrstRevAndExpnssAmt,omitempty"`
	CompOfcrDirTrstNetInvstIncmAmt int                            `xml:"CompOfcrDirTrstNetInvstIncmAmt,omitempty"`
	CompOfcrDirTrstAdjNetIncmAmt   int                            `xml:"CompOfcrDirTrstAdjNetIncmAmt,omitempty"`
	CompOfcrDirTrstDsbrsChrtblAmt  int                            `xml:"CompOfcrDirTrstDsbrsChrtblAmt,omitempty"`
	OthEmplSlrsWgsRevAndExpnssAmt  int                            `xml:"OthEmplSlrsWgsRevAndExpnssAmt,omitempty"`
	OthEmplSlrsWgsNetInvstIncmAmt  int                            `xml:"OthEmplSlrsWgsNetInvstIncmAmt,omitempty"`
	OthEmplSlrsWgsAdjNetIncmAmt    int                            `xml:"OthEmplSlrsWgsAdjNetIncmAmt,omitempty"`
	OthEmplSlrsWgsDsbrsChrtblAmt   int                            `xml:"OthEmplSlrsWgsDsbrsChrtblAmt,omitempty"`
	PensionEmplBnftRevAndExpnssAmt int                            `xml:"PensionEmplBnftRevAndExpnssAmt,omitempty"`
	PensionEmplBnftNetInvstIncmAmt int                            `xml:"PensionEmplBnftNetInvstIncmAmt,omitempty"`
	PensionEmplBnftAdjNetIncmAmt   int                            `xml:"PensionEmplBnftAdjNetIncmAmt,omitempty"`
	PensionEmplBnftDsbrsChrtblAmt  int                            `xml:"PensionEmplBnftDsbrsChrtblAmt,omitempty"`
	LegalFeesRevAndExpnssAmt       *LegalFeesRevAndExpnssAmt      `xml:"LegalFeesRevAndExpnssAmt,omitempty"`
	LegalFeesNetInvstIncmAmt       int                            `xml:"LegalFeesNetInvstIncmAmt,omitempty"`
	LegalFeesAdjNetIncmAmt         int                            `xml:"LegalFeesAdjNetIncmAmt,omitempty"`
	LegalFeesDsbrsChrtblAmt        int                            `xml:"LegalFeesDsbrsChrtblAmt,omitempty"`
	AccountingFeesRevAndExpnssAmt  *AccountingFeesRevAndExpnssAmt `xml:"AccountingFeesRevAndExpnssAmt,omitempty"`
	AccountingFeesNetInvstIncmAmt  int                            `xml:"AccountingFeesNetInvstIncmAmt,omitempty"`
	AccountingFeesAdjNetIncmAmt    int                            `xml:"AccountingFeesAdjNetIncmAmt,omitempty"`
	AccountingFeesChrtblPrpsAmt    int                            `xml:"AccountingFeesChrtblPrpsAmt,omitempty"`
	OtherProfFeesRevAndExpnssAmt   *OtherProfFeesRevAndExpnssAmt  `xml:"OtherProfFeesRevAndExpnssAmt,omitempty"`
	OtherProfFeesNetInvstIncmAmt   int                            `xml:"OtherProfFeesNetInvstIncmAmt,omitempty"`
	OtherProfFeesAdjNetIncmAmt     int                            `xml:"OtherProfFeesAdjNetIncmAmt,omitempty"`
	OtherProfFeesDsbrsChrtblAmt    int                            `xml:"OtherProfFeesDsbrsChrtblAmt,omitempty"`
	InterestRevAndExpnssAmt        int                            `xml:"InterestRevAndExpnssAmt,omitempty"`
	InterestNetInvstIncmAmt        int                            `xml:"InterestNetInvstIncmAmt,omitempty"`
	InterestAdjNetIncmAmt          int                            `xml:"InterestAdjNetIncmAmt,omitempty"`
	InterestDsbrsChrtblAmt         int                            `xml:"InterestDsbrsChrtblAmt,omitempty"`
	TaxesRevAndExpnssAmt           *TaxesRevAndExpnssAmt          `xml:"TaxesRevAndExpnssAmt,omitempty"`
	TaxesNetInvstIncmAmt           int                            `xml:"TaxesNetInvstIncmAmt,omitempty"`
	TaxesAdjNetIncmAmt             int                            `xml:"TaxesAdjNetIncmAmt,omitempty"`
	TaxesDsbrsChrtblAmt            int                            `xml:"TaxesDsbrsChrtblAmt,omitempty"`
	DeprecAndDpltnRevAndExpnssAmt  *DeprecAndDpltnRevAndExpnssAmt `xml:"DeprecAndDpltnRevAndExpnssAmt,omitempty"`
	DeprecAndDpltnNetInvstIncmAmt  int                            `xml:"DeprecAndDpltnNetInvstIncmAmt,omitempty"`
	DeprecAndDpltnAdjNetIncmAmt    int                            `xml:"DeprecAndDpltnAdjNetIncmAmt,omitempty"`
	OccupancyRevAndExpnssAmt       int                            `xml:"OccupancyRevAndExpnssAmt,omitempty"`
	OccupancyNetInvstIncmAmt       int                            `xml:"OccupancyNetInvstIncmAmt,omitempty"`
	OccupancyAdjNetIncmAmt         int                            `xml:"OccupancyAdjNetIncmAmt,omitempty"`
	OccupancyDsbrsChrtblAmt        int                            `xml:"OccupancyDsbrsChrtblAmt,omitempty"`
	TravConfMeetingRevAndExpnssAmt int                            `xml:"TravConfMeetingRevAndExpnssAmt,omitempty"`
	TravConfMeetingNetInvstIncmAmt int                            `xml:"TravConfMeetingNetInvstIncmAmt,omitempty"`
	TravConfMeetingAdjNetIncmAmt   int                            `xml:"TravConfMeetingAdjNetIncmAmt,omitempty"`
	TravConfMeetingDsbrsChrtblAmt  int                            `xml:"TravConfMeetingDsbrsChrtblAmt,omitempty"`
	PrintingAndPubRevAndExpnssAmt  int                            `xml:"PrintingAndPubRevAndExpnssAmt,omitempty"`
	PrintingAndPubNetInvstIncmAmt  int                            `xml:"PrintingAndPubNetInvstIncmAmt,omitempty"`
	PrintingAndPubAdjNetIncmAmt    int                            `xml:"PrintingAndPubAdjNetIncmAmt,omitempty"`
	PrintingAndPubDsbrsChrtblAmt   int                            `xml:"PrintingAndPubDsbrsChrtblAmt,omitempty"`
	OtherExpensesRevAndExpnssAmt   *OtherExpensesRevAndExpnssAmt  `xml:"OtherExpensesRevAndExpnssAmt,omitempty"`
	OtherExpensesNetInvstIncmAmt   int                            `xml:"OtherExpensesNetInvstIncmAmt,omitempty"`
	OtherExpensesAdjNetIncmAmt     int                            `xml:"OtherExpensesAdjNetIncmAmt,omitempty"`
	OtherExpensesDsbrsChrtblAmt    int                            `xml:"OtherExpensesDsbrsChrtblAmt,omitempty"`
	TotOprExpensesRevAndExpnssAmt  int                            `xml:"TotOprExpensesRevAndExpnssAmt"`
	TotOprExpensesNetInvstIncmAmt  int                            `xml:"TotOprExpensesNetInvstIncmAmt"`
	TotOprExpensesAdjNetIncmAmt    int                            `xml:"TotOprExpensesAdjNetIncmAmt,omitempty"`
	TotOprExpensesDsbrsChrtblAmt   int                            `xml:"TotOprExpensesDsbrsChrtblAmt"`
	ContriPaidRevAndExpnssAmt      int                            `xml:"ContriPaidRevAndExpnssAmt"`
	ContriPaidDsbrsChrtblAmt       int                            `xml:"ContriPaidDsbrsChrtblAmt"`
	TotalExpensesRevAndExpnssAmt   int                            `xml:"TotalExpensesRevAndExpnssAmt"`
	TotalExpensesNetInvstIncmAmt   int                            `xml:"TotalExpensesNetInvstIncmAmt"`
	TotalExpensesAdjNetIncmAmt     int                            `xml:"TotalExpensesAdjNetIncmAmt,omitempty"`
	TotalExpensesDsbrsChrtblAmt    int                            `xml:"TotalExpensesDsbrsChrtblAmt"`
	ExcessRevenueOverExpensesAmt   int                            `xml:"ExcessRevenueOverExpensesAmt"`
	NetInvestmentIncomeAmt         int                            `xml:"NetInvestmentIncomeAmt"`
	AdjustedNetIncomeAmt           int                            `xml:"AdjustedNetIncomeAmt,omitempty"`
}

// RcvblFromOfficersEOYAmt is Part II Line 6(b)
type RcvblFromOfficersEOYAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// OtherNtsAndLoansRcvblEOYAmt is Part II Line 7(b)
type OtherNtsAndLoansRcvblEOYAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// USGovernmentObligationsEOYAmt is Part II Line 10a(b)
type USGovernmentObligationsEOYAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// CorporateStockEOYAmt is Part II Line 10b(b)
type CorporateStockEOYAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// CorporateBondsEOYAmt is Part II Line 10c(b)
type CorporateBondsEOYAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// LandBldgInvestmentsEOYAmt is Part II Line 11(b)
type LandBldgInvestmentsEOYAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// OtherInvestmentsEOYAmt is Part II Line 13(b)
type OtherInvestmentsEOYAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// LandEOYAmt is Part II Line 14(b)
type LandEOYAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// OtherAssetsBOYAmt is Part II Line 15(a)
type OtherAssetsBOYAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// OtherAssetsEOYAmt is Part II Line 15(b)
type OtherAssetsEOYAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// OtherAssetsEOYFMVAmt is Part II Line 15(c)
type OtherAssetsEOYFMVAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// LoansFromOfficersEOYAmt is Part II Line 20(b)
type LoansFromOfficersEOYAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// MortgagesAndNotesPayableEOYAmt is Part II Line 21(b)
type MortgagesAndNotesPayableEOYAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// OtherLiabilitiesBOYAmt is Part II Line 22(a)
type OtherLiabilitiesBOYAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// OtherLiabilitiesEOYAmt is Part II Line 22(b)
type OtherLiabilitiesEOYAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// Form990PFBalanceSheetsGrp ...
type Form990PFBalanceSheetsGrp struct {
	CashBOYAmt                     int                             `xml:"CashBOYAmt,omitempty"`
	CashEOYAmt                     int                             `xml:"CashEOYAmt,omitempty"`
	CashEOYFMVAmt                  int                             `xml:"CashEOYFMVAmt,omitempty"`
	SavAndTempCashInvstBOYAmt      int                             `xml:"SavAndTempCashInvstBOYAmt,omitempty"`
	SavAndTempCashInvstEOYAmt      int                             `xml:"SavAndTempCashInvstEOYAmt,omitempty"`
	SavAndTempCashInvstEOYFMVAmt   int                             `xml:"SavAndTempCashInvstEOYFMVAmt,omitempty"`
	AcctRcvblAmt                   int                             `xml:"AcctRcvblAmt,omitempty"`
	AcctRcvblAllwncDbtflAcctAmt    int                             `xml:"AcctRcvblAllwncDbtflAcctAmt,omitempty"`
	AcctRcvblBOYAmt                int                             `xml:"AcctRcvblBOYAmt,omitempty"`
	AcctRcvblEOYAmt                int                             `xml:"AcctRcvblEOYAmt,omitempty"`
	AcctRcvblEOYFMVAmt             int                             `xml:"AcctRcvblEOYFMVAmt,omitempty"`
	PledgesRcvblAmt                int                             `xml:"PledgesRcvblAmt,omitempty"`
	PledgesRcvblAllwncDbtflAcctAmt int                             `xml:"PledgesRcvblAllwncDbtflAcctAmt,omitempty"`
	PledgesRcvblBOYAmt             int                             `xml:"PledgesRcvblBOYAmt,omitempty"`
	PledgesRcvblEOYAmt             int                             `xml:"PledgesRcvblEOYAmt,omitempty"`
	PledgesRcvblEOYFMVAmt          int                             `xml:"PledgesRcvblEOYFMVAmt,omitempty"`
	GrantsReceivableBOYAmt         int                             `xml:"GrantsReceivableBOYAmt,omitempty"`
	GrantsReceivableEOYAmt         int                             `xml:"GrantsReceivableEOYAmt,omitempty"`
	GrantsReceivableEOYFMVAmt      int                             `xml:"GrantsReceivableEOYFMVAmt,omitempty"`
	RcvblFromOfficersBOYAmt        int                             `xml:"RcvblFromOfficersBOYAmt,omitempty"`
	RcvblFromOfficersEOYAmt        *RcvblFromOfficersEOYAmt        `xml:"RcvblFromOfficersEOYAmt,omitempty"`
	RcvblFromOfficersEOYFMVAmt     int                             `xml:"RcvblFromOfficersEOYFMVAmt,omitempty"`
	OtherNtsAndLoansRcvblAmt       int                             `xml:"OtherNtsAndLoansRcvblAmt,omitempty"`
	OtherRcvblAllwncDbtflAcctAmt   int                             `xml:"OtherRcvblAllwncDbtflAcctAmt,omitempty"`
	OtherNtsAndLoansRcvblBOYAmt    int                             `xml:"OtherNtsAndLoansRcvblBOYAmt,omitempty"`
	OtherNtsAndLoansRcvblEOYAmt    *OtherNtsAndLoansRcvblEOYAmt    `xml:"OtherNtsAndLoansRcvblEOYAmt,omitempty"`
	OtherNtsAndLoansRcvblEOYFMVAmt int                             `xml:"OtherNtsAndLoansRcvblEOYFMVAmt,omitempty"`
	InventoriesBOYAmt              int                             `xml:"InventoriesBOYAmt,omitempty"`
	InventoriesEOYAmt              int                             `xml:"InventoriesEOYAmt,omitempty"`
	InventoriesEOYFMVAmt           int                             `xml:"InventoriesEOYFMVAmt,omitempty"`
	PrepaidExpensesBOYAmt          int                             `xml:"PrepaidExpensesBOYAmt,omitempty"`
	PrepaidExpensesEOYAmt          int                             `xml:"PrepaidExpensesEOYAmt,omitempty"`
	PrepaidExpensesEOYFMVAmt       int                             `xml:"PrepaidExpensesEOYFMVAmt,omitempty"`
	USGovernmentObligationsBOYAmt  int                             `xml:"USGovernmentObligationsBOYAmt,omitempty"`
	USGovernmentObligationsEOYAmt  *USGovernmentObligationsEOYAmt  `xml:"USGovernmentObligationsEOYAmt,omitempty"`
	USGovtObligationsEOYFMVAmt     int                             `xml:"USGovtObligationsEOYFMVAmt,omitempty"`
	CorporateStockBOYAmt           int                             `xml:"CorporateStockBOYAmt,omitempty"`
	CorporateStockEOYAmt           *CorporateStockEOYAmt           `xml:"CorporateStockEOYAmt,omitempty"`
	CorporateStockEOYFMVAmt        int                             `xml:"CorporateStockEOYFMVAmt,omitempty"`
	CorporateBondsBOYAmt           int                             `xml:"CorporateBondsBOYAmt,omitempty"`
	CorporateBondsEOYAmt           *CorporateBondsEOYAmt           `xml:"CorporateBondsEOYAmt,omitempty"`
	CorporateBondsEOYFMVAmt        int                             `xml:"CorporateBondsEOYFMVAmt,omitempty"`
	InvstLandCostOrOtherBasisAmt   int                             `xml:"InvstLandCostOrOtherBasisAmt,omitempty"`
	InvstLandAccumDepreciationAmt  int                             `xml:"InvstLandAccumDepreciationAmt,omitempty"`
	LandBldgInvestmentsBOYAmt      int                             `xml:"LandBldgInvestmentsBOYAmt,omitempty"`
	LandBldgInvestmentsEOYAmt      *LandBldgInvestmentsEOYAmt      `xml:"LandBldgInvestmentsEOYAmt,omitempty"`
	LandBldgInvestmentsEOYFMVAmt   int                             `xml:"LandBldgInvestmentsEOYFMVAmt,omitempty"`
	MortgageLoansBOYAmt            int                             `xml:"MortgageLoansBOYAmt,omitempty"`
	MortgageLoansEOYAmt            int                             `xml:"MortgageLoansEOYAmt,omitempty"`
	MortgageLoansEOYFMVAmt         int                             `xml:"MortgageLoansEOYFMVAmt,omitempty"`
	OtherInvestmentsBOYAmt         int                             `xml:"OtherInvestmentsBOYAmt,omitempty"`
	OtherInvestmentsEOYAmt         *OtherInvestmentsEOYAmt         `xml:"OtherInvestmentsEOYAmt,omitempty"`
	OtherInvestmentsEOYFMVAmt      int                             `xml:"OtherInvestmentsEOYFMVAmt,omitempty"`
	LandBldgEquipCostOrOtherBssAmt int                             `xml:"LandBldgEquipCostOrOtherBssAmt,omitempty"`
	LandBldgEquipAccumDeprecAmt    int                             `xml:"LandBldgEquipAccumDeprecAmt,omitempty"`
	LandBOYAmt                     int                             `xml:"LandBOYAmt,omitempty"`
	LandEOYAmt                     *LandEOYAmt                     `xml:"LandEOYAmt,omitempty"`
	LandEOYFMVAmt                  int                             `xml:"LandEOYFMVAmt,omitempty"`
	OtherAssetsBOYAmt              *OtherAssetsBOYAmt              `xml:"OtherAssetsBOYAmt,omitempty"`
	OtherAssetsEOYAmt              *OtherAssetsEOYAmt              `xml:"OtherAssetsEOYAmt,omitempty"`
	OtherAssetsEOYFMVAmt           *OtherAssetsEOYFMVAmt           `xml:"OtherAssetsEOYFMVAmt,omitempty"`
	TotalAssetsBOYAmt              int                             `xml:"TotalAssetsBOYAmt,omitempty"`
	TotalAssetsEOYAmt              int                             `xml:"TotalAssetsEOYAmt"`
	TotalAssetsEOYFMVAmt           int                             `xml:"TotalAssetsEOYFMVAmt"`
	AccountsPayableBOYAmt          int                             `xml:"AccountsPayableBOYAmt,omitempty"`
	AccountsPayableEOYAmt          int                             `xml:"AccountsPayableEOYAmt,omitempty"`
	GrantsPayableBOYAmt            int                             `xml:"GrantsPayableBOYAmt,omitempty"`
	GrantsPayableEOYAmt            int                             `xml:"GrantsPayableEOYAmt,omitempty"`
	DeferredRevenueBOYAmt          int                             `xml:"DeferredRevenueBOYAmt,omitempty"`
	DeferredRevenueEOYAmt          int                             `xml:"DeferredRevenueEOYAmt,omitempty"`
	LoansFromOfficersBOYAmt        int                             `xml:"LoansFromOfficersBOYAmt,omitempty"`
	LoansFromOfficersEOYAmt        *LoansFromOfficersEOYAmt        `xml:"LoansFromOfficersEOYAmt,omitempty"`
	MortgagesAndNotesPayableBOYAmt int                             `xml:"MortgagesAndNotesPayableBOYAmt,omitempty"`
	MortgagesAndNotesPayableEOYAmt *MortgagesAndNotesPayableEOYAmt `xml:"MortgagesAndNotesPayableEOYAmt,omitempty"`
	OtherLiabilitiesBOYAmt         *OtherLiabilitiesBOYAmt         `xml:"OtherLiabilitiesBOYAmt,omitempty"`
	OtherLiabilitiesEOYAmt         *OtherLiabilitiesEOYAmt         `xml:"OtherLiabilitiesEOYAmt,omitempty"`
	TotalLiabilitiesBOYAmt         int                             `xml:"TotalLiabilitiesBOYAmt,omitempty"`
	TotalLiabilitiesEOYAmt         int                             `xml:"TotalLiabilitiesEOYAmt"`
	OrganizationFollowsFASB117Ind  string                          `xml:"OrganizationFollowsFASB117Ind,omitempty"`
	NoDonorRstrNetAssestsBOYAmt    int                             `xml:"NoDonorRstrNetAssestsBOYAmt,omitempty"`
	NoDonorRstrNetAssestsEOYAmt    int                             `xml:"NoDonorRstrNetAssestsEOYAmt,omitempty"`
	DonorRstrNetAssetsBOYAmt       int                             `xml:"DonorRstrNetAssetsBOYAmt,omitempty"`
	DonorRstrNetAssetsEOYAmt       int                             `xml:"DonorRstrNetAssetsEOYAmt,omitempty"`
	OrgDoesNotFollowFASB117Ind     string                          `xml:"OrgDoesNotFollowFASB117Ind,omitempty"`
	CapitalStockBOYAmt             int                             `xml:"CapitalStockBOYAmt,omitempty"`
	CapitalStockEOYAmt             int                             `xml:"CapitalStockEOYAmt,omitempty"`
	AdditionalPaidInCapitalBOYAmt  int                             `xml:"AdditionalPaidInCapitalBOYAmt,omitempty"`
	AdditionalPaidInCapitalEOYAmt  int                             `xml:"AdditionalPaidInCapitalEOYAmt,omitempty"`
	RetainedEarningBOYAmt          int                             `xml:"RetainedEarningBOYAmt,omitempty"`
	RetainedEarningEOYAmt          int                             `xml:"RetainedEarningEOYAmt,omitempty"`
	TotNetAstOrFundBalancesBOYAmt  int                             `xml:"TotNetAstOrFundBalancesBOYAmt,omitempty"`
	TotNetAstOrFundBalancesEOYAmt  int                             `xml:"TotNetAstOrFundBalancesEOYAmt"`
	TotalLiabilitiesNetAstBOYAmt   int                             `xml:"TotalLiabilitiesNetAstBOYAmt"`
	TotalLiabilitiesNetAstEOYAmt   int                             `xml:"TotalLiabilitiesNetAstEOYAmt"`
}

// OtherIncreasesAmt is Part III Line 3
type OtherIncreasesAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// OtherDecreasesAmt is Part III Line 5
type OtherDecreasesAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// ChgInNetAssetsFundBalancesGrp ...
type ChgInNetAssetsFundBalancesGrp struct {
	TotNetAstOrFundBalancesBOYAmt int                `xml:"TotNetAstOrFundBalancesBOYAmt,omitempty"`
	ExcessRevenueOverExpensesAmt  int                `xml:"ExcessRevenueOverExpensesAmt,omitempty"`
	OtherIncreasesAmt             *OtherIncreasesAmt `xml:"OtherIncreasesAmt,omitempty"`
	SubtotalAmt                   int                `xml:"SubtotalAmt,omitempty"`
	OtherDecreasesAmt             *OtherDecreasesAmt `xml:"OtherDecreasesAmt,omitempty"`
	TotNetAstOrFundBalancesEOYAmt int                `xml:"TotNetAstOrFundBalancesEOYAmt,omitempty"`
}

// CapGainsLossTxInvstIncmGrp ...
type CapGainsLossTxInvstIncmGrp struct {
	PropertyDesc                string      `xml:"PropertyDesc,omitempty"`
	HowAcquiredCd               interface{} `xml:"HowAcquiredCd,omitempty"`
	AcquiredDt                  string      `xml:"AcquiredDt,omitempty"`
	SoldDt                      string      `xml:"SoldDt,omitempty"`
	GrossSalesPriceAmt          int         `xml:"GrossSalesPriceAmt,omitempty"`
	DepreciationAmt             int         `xml:"DepreciationAmt,omitempty"`
	CostOrOtherBasisAmt         int         `xml:"CostOrOtherBasisAmt,omitempty"`
	GainOrLossAmt               int         `xml:"GainOrLossAmt,omitempty"`
	FMVAsOf123169Amt            int         `xml:"FMVAsOf123169Amt,omitempty"`
	AdjustedBasisAsOf123169Amt  int         `xml:"AdjustedBasisAsOf123169Amt,omitempty"`
	ExcessFMVOverAdjustedBssAmt int         `xml:"ExcessFMVOverAdjustedBssAmt,omitempty"`
	GainsMinusExcessOrLossesAmt int         `xml:"GainsMinusExcessOrLossesAmt,omitempty"`
}

// CapGainsLossTxInvstIncmDetail ...
type CapGainsLossTxInvstIncmDetail struct {
	CapGainsLossTxInvstIncmGrp     []*CapGainsLossTxInvstIncmGrp `xml:"CapGainsLossTxInvstIncmGrp,omitempty"`
	CapitalGainNetIncomeAmt        int                           `xml:"CapitalGainNetIncomeAmt,omitempty"`
	NetShortTermCapitalGainLossAmt int                           `xml:"NetShortTermCapitalGainLossAmt,omitempty"`
}

// TaxUnderSection511Amt is Part V Line 2
type TaxUnderSection511Amt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// ExemptFrgnOrgTaxWthldAtSrceAmt is Part V Line 6b
type ExemptFrgnOrgTaxWthldAtSrceAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// Form2220AttachedInd is Part V Line 8
type Form2220AttachedInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     string      `xml:",chardata"`
}

// ExciseTaxBasedOnInvstIncmGrp ...
type ExciseTaxBasedOnInvstIncmGrp struct {
	ExemptOperatingFoundationsInd  string                          `xml:"ExemptOperatingFoundationsInd,omitempty"`
	RulingLetterDt                 string                          `xml:"RulingLetterDt,omitempty"`
	InvestmentIncomeExciseTaxAmt   int                             `xml:"InvestmentIncomeExciseTaxAmt"`
	NotApplicableCd                interface{}                     `xml:"NotApplicableCd"`
	TaxUnderSection511Amt          *TaxUnderSection511Amt          `xml:"TaxUnderSection511Amt,omitempty"`
	SubtotalAmt                    int                             `xml:"SubtotalAmt,omitempty"`
	SubtitleATaxAmt                int                             `xml:"SubtitleATaxAmt,omitempty"`
	TaxBasedOnInvestmentIncomeAmt  int                             `xml:"TaxBasedOnInvestmentIncomeAmt,omitempty"`
	EstimatedPlusOvpmtIncmTxAmt    int                             `xml:"EstimatedPlusOvpmtIncmTxAmt,omitempty"`
	ExemptFrgnOrgTaxWthldAtSrceAmt *ExemptFrgnOrgTaxWthldAtSrceAmt `xml:"ExemptFrgnOrgTaxWthldAtSrceAmt,omitempty"`
	ExtsnRequestIncomeTaxPaidAmt   int                             `xml:"ExtsnRequestIncomeTaxPaidAmt,omitempty"`
	BackupWithholdingWithheldAmt   int                             `xml:"BackupWithholdingWithheldAmt,omitempty"`
	TotalPaymentsAndCreditsAmt     int                             `xml:"TotalPaymentsAndCreditsAmt,omitempty"`
	OriginalReturnTaxPaidAmt       int                             `xml:"OriginalReturnTaxPaidAmt"`
	OriginalReturnOverpaymentAmt   int                             `xml:"OriginalReturnOverpaymentAmt"`
	Form2220AttachedInd            *Form2220AttachedInd            `xml:"Form2220AttachedInd,omitempty"`
	EsPenaltyAmt                   int                             `xml:"EsPenaltyAmt,omitempty"`
	TaxDueAmt                      int                             `xml:"TaxDueAmt"`
	OverpaymentAmt                 int                             `xml:"OverpaymentAmt"`
	AppliedToESTaxAmt              int                             `xml:"AppliedToESTaxAmt,omitempty"`
	RefundAmt                      int                             `xml:"RefundAmt,omitempty"`
}

// LegislativePoliticalActyInd is Part VI-A Line 1a
type LegislativePoliticalActyInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// ActivitiesNotPreviouslyRptInd is Part VI-A Line 2
type ActivitiesNotPreviouslyRptInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// ChangesToArticlesOrBylawsInd is Part VI-A Line 3
type ChangesToArticlesOrBylawsInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}


// Form990PFFiledWithAttyGenInd is Part VI-A Line 8b
type Form990PFFiledWithAttyGenInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// NewSubstantialContributorsInd is Part VI-A Line 10
type NewSubstantialContributorsInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// OwnControlledEntityInd is Part VI-A Line 11
type OwnControlledEntityInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}


// StatementsRegardingActyGrp ...
type StatementsRegardingActyGrp struct {
	LegislativePoliticalActyInd   *LegislativePoliticalActyInd   `xml:"LegislativePoliticalActyInd,omitempty"`
	MoreThan100SpentInd           bool                           `xml:"MoreThan100SpentInd,omitempty"`
	Form1120POLFiledInd           bool                           `xml:"Form1120POLFiledInd,omitempty"`
	Section4955OrganizationTaxAmt int                            `xml:"Section4955OrganizationTaxAmt,omitempty"`
	Section4955ManagersTaxAmt     int                            `xml:"Section4955ManagersTaxAmt,omitempty"`
	TaxReimbursedAmt              int                            `xml:"TaxReimbursedAmt,omitempty"`
	ActivitiesNotPreviouslyRptInd *ActivitiesNotPreviouslyRptInd `xml:"ActivitiesNotPreviouslyRptInd,omitempty"`
	ChangesToArticlesOrBylawsInd  *ChangesToArticlesOrBylawsInd  `xml:"ChangesToArticlesOrBylawsInd,omitempty"`
	UnrelatedBusIncmOverLimitInd  bool                           `xml:"UnrelatedBusIncmOverLimitInd,omitempty"`
	Form990TFiledInd              bool                           `xml:"Form990TFiledInd,omitempty"`
	OrganizationDissolvedEtcInd   *OrganizationDissolvedEtcInd   `xml:"OrganizationDissolvedEtcInd,omitempty"`
	Section508eRqrSatisfiedInd    bool                           `xml:"Section508eRqrSatisfiedInd,omitempty"`
	AtLeast5000InAssetsInd        bool                           `xml:"AtLeast5000InAssetsInd,omitempty"`
	OrgReportOrRegisterStateCd    []string                       `xml:"OrgReportOrRegisterStateCd,omitempty"`
	Form990PFFiledWithAttyGenInd  *Form990PFFiledWithAttyGenInd  `xml:"Form990PFFiledWithAttyGenInd,omitempty"`
	PrivateOperatingFoundationInd bool                           `xml:"PrivateOperatingFoundationInd,omitempty"`
	NewSubstantialContributorsInd *NewSubstantialContributorsInd `xml:"NewSubstantialContributorsInd"`
	OwnControlledEntityInd        *OwnControlledEntityInd        `xml:"OwnControlledEntityInd,omitempty"`
	DonorAdvisedFundInd           *DonorAdvisedFundInd           `xml:"DonorAdvisedFundInd,omitempty"`
	ComplyWithPublicInspRqrInd    bool                           `xml:"ComplyWithPublicInspRqrInd"`
	WebsiteAddressTxt             string                         `xml:"WebsiteAddressTxt,omitempty"`
	PersonsWithBooksName          *BusinessNameType              `xml:"PersonsWithBooksName"`
	IndividualWithBooksNm         string                         `xml:"IndividualWithBooksNm"`
	PhoneNum                      string                         `xml:"PhoneNum,omitempty"`
	LocationOfBooksUSAddress      *USAddressType                 `xml:"LocationOfBooksUSAddress"`
	LocationOfBooksForeignAddress *ForeignAddressType            `xml:"LocationOfBooksForeignAddress"`
	NECTFilingInLieuOFForm1041Ind string                         `xml:"NECTFilingInLieuOFForm1041Ind,omitempty"`
	TaxExemptInterestAmt          int                            `xml:"TaxExemptInterestAmt,omitempty"`
	ForeignAccountsQuestionInd    bool                           `xml:"ForeignAccountsQuestionInd,omitempty"`
	ForeignCountryCd              []string                       `xml:"ForeignCountryCd,omitempty"`
}

// UndistrIncmSect4942a2NotAppInd is Part VI-B Line 2b
type UndistrIncmSect4942a2NotAppInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// MaintainedExpenditureRspnsInd is Part VI-B Line 5c
type MaintainedExpenditureRspnsInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// StatementsRegardingActy4720Grp ...
type StatementsRegardingActy4720Grp struct {
	SaleOrExchDisqualifiedPrsnInd  bool                            `xml:"SaleOrExchDisqualifiedPrsnInd,omitempty"`
	BrrwOrLendDisqualifiedPrsnInd  bool                            `xml:"BrrwOrLendDisqualifiedPrsnInd,omitempty"`
	FurnGoodsDisqualifiedPrsnInd   bool                            `xml:"FurnGoodsDisqualifiedPrsnInd,omitempty"`
	PayCompDisqualifiedPrsnInd     bool                            `xml:"PayCompDisqualifiedPrsnInd,omitempty"`
	TransferAstDisqualifiedPrsnInd bool                            `xml:"TransferAstDisqualifiedPrsnInd,omitempty"`
	PaymentToGovernmentOfficialInd bool                            `xml:"PaymentToGovernmentOfficialInd,omitempty"`
	ActsFailToQlfyAsExceptionsInd  bool                            `xml:"ActsFailToQlfyAsExceptionsInd,omitempty"`
	RelyingCurrentNtcDsstrAsstInd  string                          `xml:"RelyingCurrentNtcDsstrAsstInd,omitempty"`
	UncorrectedPriorActsInd        bool                            `xml:"UncorrectedPriorActsInd,omitempty"`
	UndistributedIncomePYInd       bool                            `xml:"UndistributedIncomePYInd,omitempty"`
	UndistributedIncomePY1Yr       string                          `xml:"UndistributedIncomePY1Yr,omitempty"`
	UndistributedIncomePY2Yr       string                          `xml:"UndistributedIncomePY2Yr,omitempty"`
	UndistributedIncomePY3Yr       string                          `xml:"UndistributedIncomePY3Yr,omitempty"`
	UndistributedIncomePY4Yr       string                          `xml:"UndistributedIncomePY4Yr,omitempty"`
	UndistrIncmSect4942a2NotAppInd *UndistrIncmSect4942a2NotAppInd `xml:"UndistrIncmSect4942a2NotAppInd,omitempty"`
	UndistrIncmSect4942a2AppYr1Yr  string                          `xml:"UndistrIncmSect4942a2AppYr1Yr,omitempty"`
	UndistrIncmSect4942a2AppYr2Yr  string                          `xml:"UndistrIncmSect4942a2AppYr2Yr,omitempty"`
	UndistrIncmSect4942a2AppYr3Yr  string                          `xml:"UndistrIncmSect4942a2AppYr3Yr,omitempty"`
	UndistrIncmSect4942a2AppYr4Yr  string                          `xml:"UndistrIncmSect4942a2AppYr4Yr,omitempty"`
	BusinessHoldingsInd            bool                            `xml:"BusinessHoldingsInd,omitempty"`
	ExcessBusinessHoldingsInd      bool                            `xml:"ExcessBusinessHoldingsInd,omitempty"`
	JeopardyInvestmentsInd         bool                            `xml:"JeopardyInvestmentsInd,omitempty"`
	UncorrectedPYJeopardyInvstInd  bool                            `xml:"UncorrectedPYJeopardyInvstInd,omitempty"`
	InfluenceLegislationInd        bool                            `xml:"InfluenceLegislationInd,omitempty"`
	InfluenceElectionInd           bool                            `xml:"InfluenceElectionInd,omitempty"`
	GrantsToIndividualsInd         bool                            `xml:"GrantsToIndividualsInd,omitempty"`
	GrantsToOrganizationsInd       bool                            `xml:"GrantsToOrganizationsInd,omitempty"`
	NoncharitablePurposeInd        bool                            `xml:"NoncharitablePurposeInd,omitempty"`
	TransactionsFailToQlfyAsExcInd bool                            `xml:"TransactionsFailToQlfyAsExcInd,omitempty"`
	RelyingCurrentNtcDsstrAsst1Ind string                          `xml:"RelyingCurrentNtcDsstrAsst1Ind,omitempty"`
	MaintainedExpenditureRspnsInd  *MaintainedExpenditureRspnsInd  `xml:"MaintainedExpenditureRspnsInd,omitempty"`
	RcvFndsToPayPrsnlBnftCntrctInd bool                            `xml:"RcvFndsToPayPrsnlBnftCntrctInd,omitempty"`
	PayPremiumsPrsnlBnftCntrctInd  bool                            `xml:"PayPremiumsPrsnlBnftCntrctInd,omitempty"`
	ProhibitedTaxShelterTransInd   bool                            `xml:"ProhibitedTaxShelterTransInd,omitempty"`
	ProceedsOrNetIncomeInd         bool                            `xml:"ProceedsOrNetIncomeInd,omitempty"`
	SubjToTaxRmnrtnExPrchtPymtInd  bool                            `xml:"SubjToTaxRmnrtnExPrchtPymtInd,omitempty"`
}



// OfficerDirTrstKeyEmplGrp is Part VII Line 1
type OfficerDirTrstKeyEmplGrp struct {
	PersonNm                      *PersonNm           `xml:"PersonNm"`
	BusinessName                  *BusinessName       `xml:"BusinessName"`
	USAddress                     *USAddressType      `xml:"USAddress"`
	ForeignAddress                *ForeignAddressType `xml:"ForeignAddress"`
	TitleTxt                      string              `xml:"TitleTxt"`
	AverageHrsPerWkDevotedToPosRt interface{}         `xml:"AverageHrsPerWkDevotedToPosRt"`
	CompensationAmt               int                 `xml:"CompensationAmt"`
	EmployeeBenefitProgramAmt     int                 `xml:"EmployeeBenefitProgramAmt,omitempty"`
	ExpenseAccountOtherAllwncAmt  int                 `xml:"ExpenseAccountOtherAllwncAmt,omitempty"`
}

// CompensationHighestPaidEmplGrp is Part VII Line 2
type CompensationHighestPaidEmplGrp struct {
	PersonNm                      *PersonNm           `xml:"PersonNm"`
	USAddress                     *USAddressType      `xml:"USAddress"`
	ForeignAddress                *ForeignAddressType `xml:"ForeignAddress"`
	TitleTxt                      string              `xml:"TitleTxt"`
	AverageHrsPerWkDevotedToPosRt interface{}         `xml:"AverageHrsPerWkDevotedToPosRt"`
	CompensationAmt               int                 `xml:"CompensationAmt"`
	EmployeeBenefitsAmt           int                 `xml:"EmployeeBenefitsAmt,omitempty"`
	ExpenseAccountAmt             int                 `xml:"ExpenseAccountAmt,omitempty"`
}

// CompensationOfHghstPdCntrctGrp is Part VII Line 3
type CompensationOfHghstPdCntrctGrp struct {
	BusinessName    *BusinessName       `xml:"BusinessName"`
	PersonNm        *PersonNm           `xml:"PersonNm"`
	USAddress       *USAddressType      `xml:"USAddress"`
	ForeignAddress  *ForeignAddressType `xml:"ForeignAddress"`
	ServiceTypeTxt  string              `xml:"ServiceTypeTxt"`
	CompensationAmt int                 `xml:"CompensationAmt"`
}

// OfficerDirTrstKeyEmplInfoGrp ...
type OfficerDirTrstKeyEmplInfoGrp struct {
	OfficerDirTrstKeyEmplGrp       []*OfficerDirTrstKeyEmplGrp       `xml:"OfficerDirTrstKeyEmplGrp"`
	CompensationHighestPaidEmplGrp []*CompensationHighestPaidEmplGrp `xml:"CompensationHighestPaidEmplGrp"`
	CompOfHghstPdEmplOrNONETxt     interface{}                       `xml:"CompOfHghstPdEmplOrNONETxt"`
	OtherEmployeePaidOver50kCnt    interface{}                       `xml:"OtherEmployeePaidOver50kCnt,omitempty"`
	CompensationOfHghstPdCntrctGrp []*CompensationOfHghstPdCntrctGrp `xml:"CompensationOfHghstPdCntrctGrp"`
	CompOfHghstPdCntrctOrNONETxt   interface{}                       `xml:"CompOfHghstPdCntrctOrNONETxt"`
	ContractorPaidOver50kCnt       interface{}                       `xml:"ContractorPaidOver50kCnt,omitempty"`
}

// SummaryOfDirectChrtblActyGrp ...
type SummaryOfDirectChrtblActyGrp struct {
	Description1Txt string `xml:"Description1Txt,omitempty"`
	Expenses1Amt    int    `xml:"Expenses1Amt,omitempty"`
	Description2Txt string `xml:"Description2Txt,omitempty"`
	Expenses2Amt    int    `xml:"Expenses2Amt,omitempty"`
	Description3Txt string `xml:"Description3Txt,omitempty"`
	Expenses3Amt    int    `xml:"Expenses3Amt,omitempty"`
	Description4Txt string `xml:"Description4Txt,omitempty"`
	Expenses4Amt    int    `xml:"Expenses4Amt,omitempty"`
}

// AllOtherProgramRltdInvstTotAmt is Part VIII-B Line 3
type AllOtherProgramRltdInvstTotAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// SumOfProgramRelatedInvstGrp ...
type SumOfProgramRelatedInvstGrp struct {
	Description1Txt                string                          `xml:"Description1Txt,omitempty"`
	Expenses1Amt                   int                             `xml:"Expenses1Amt,omitempty"`
	Description2Txt                string                          `xml:"Description2Txt,omitempty"`
	Expenses2Amt                   int                             `xml:"Expenses2Amt,omitempty"`
	AllOtherProgramRltdInvstTotAmt *AllOtherProgramRltdInvstTotAmt `xml:"AllOtherProgramRltdInvstTotAmt,omitempty"`
	TotalAmt                       int                             `xml:"TotalAmt,omitempty"`
}

// ReductionClaimedAmt is Part IX Line 1e
type ReductionClaimedAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// CashDeemedCharitableAmt is Part IX Line 4
type CashDeemedCharitableAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// MinimumInvestmentReturnGrp ...
type MinimumInvestmentReturnGrp struct {
	AverageMonthlyFMVOfSecAmt      int                      `xml:"AverageMonthlyFMVOfSecAmt"`
	AverageMonthlyCashBalancesAmt  int                      `xml:"AverageMonthlyCashBalancesAmt"`
	FMVAllOtherNoncharitableAstAmt int                      `xml:"FMVAllOtherNoncharitableAstAmt"`
	TotalFMVOfUnusedAssetsAmt      int                      `xml:"TotalFMVOfUnusedAssetsAmt"`
	ReductionClaimedAmt            *ReductionClaimedAmt     `xml:"ReductionClaimedAmt,omitempty"`
	AcquisitionIndebtednessAmt     int                      `xml:"AcquisitionIndebtednessAmt,omitempty"`
	AdjustedTotalFMVOfUnusedAstAmt int                      `xml:"AdjustedTotalFMVOfUnusedAstAmt"`
	CashDeemedCharitableAmt        *CashDeemedCharitableAmt `xml:"CashDeemedCharitableAmt"`
	NetVlNoncharitableAssetsAmt    int                      `xml:"NetVlNoncharitableAssetsAmt"`
	MinimumInvestmentReturnAmt     int                      `xml:"MinimumInvestmentReturnAmt"`
}

// ExpensesAndContributionsAmt is Part XI Line 1a
type ExpensesAndContributionsAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// SetAsideCashDistriTestAmt is Part XI Line 3b
type SetAsideCashDistriTestAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// PFQualifyingDistributionsGrp ...
type PFQualifyingDistributionsGrp struct {
	ExpensesAndContributionsAmt   *ExpensesAndContributionsAmt `xml:"ExpensesAndContributionsAmt,omitempty"`
	ProgramRelatedInvstTotalAmt   int                          `xml:"ProgramRelatedInvstTotalAmt,omitempty"`
	CharitableAssetsAcquisPaidAmt int                          `xml:"CharitableAssetsAcquisPaidAmt,omitempty"`
	SetAsideSuitabilityTestAmt    int                          `xml:"SetAsideSuitabilityTestAmt,omitempty"`
	SetAsideCashDistriTestAmt     *SetAsideCashDistriTestAmt   `xml:"SetAsideCashDistriTestAmt,omitempty"`
	QualifyingDistributionsAmt    int                          `xml:"QualifyingDistributionsAmt,omitempty"`
}

// AppliedToPriorYearsAmt is Part XII Line 4b(b)
type AppliedToPriorYearsAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// TreatedAsDistriFromCorpusAmt is Part XII Line 4c(a)
type TreatedAsDistriFromCorpusAmt struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     int         `xml:",chardata"`
}

// UndistributedIncomeGrp ...
type UndistributedIncomeGrp struct {
	DistributableAsAdjustedAmt     int                           `xml:"DistributableAsAdjustedAmt,omitempty"`
	UndistributedIncomePYAmt       int                           `xml:"UndistributedIncomePYAmt,omitempty"`
	PriorYear1Yr                   string                        `xml:"PriorYear1Yr,omitempty"`
	PriorYear2Yr                   string                        `xml:"PriorYear2Yr,omitempty"`
	PriorYear3Yr                   string                        `xml:"PriorYear3Yr,omitempty"`
	TotalForPriorYearsAmt          int                           `xml:"TotalForPriorYearsAmt,omitempty"`
	ExcessDistributionCyovYr5Amt   int                           `xml:"ExcessDistributionCyovYr5Amt,omitempty"`
	ExcessDistributionCyovYr4Amt   int                           `xml:"ExcessDistributionCyovYr4Amt,omitempty"`
	ExcessDistributionCyovYr3Amt   int                           `xml:"ExcessDistributionCyovYr3Amt,omitempty"`
	ExcessDistributionCyovYr2Amt   int                           `xml:"ExcessDistributionCyovYr2Amt,omitempty"`
	ExcessDistributionCyovYr1Amt   int                           `xml:"ExcessDistributionCyovYr1Amt,omitempty"`
	TotalExcessDistributionCyovAmt int                           `xml:"TotalExcessDistributionCyovAmt,omitempty"`
	QualifyingDistributionsAmt     int                           `xml:"QualifyingDistributionsAmt,omitempty"`
	AppliedToYear1Amt              int                           `xml:"AppliedToYear1Amt,omitempty"`
	AppliedToPriorYearsAmt         *AppliedToPriorYearsAmt       `xml:"AppliedToPriorYearsAmt,omitempty"`
	TreatedAsDistriFromCorpusAmt   *TreatedAsDistriFromCorpusAmt `xml:"TreatedAsDistriFromCorpusAmt,omitempty"`
	AppliedToCurrentYearAmt        int                           `xml:"AppliedToCurrentYearAmt,omitempty"`
	RemainingDistriFromCorpusAmt   int                           `xml:"RemainingDistriFromCorpusAmt,omitempty"`
	ExcessDistriCyovAppCYCorpusAmt int                           `xml:"ExcessDistriCyovAppCYCorpusAmt,omitempty"`
	ExcessDistributionCyovAppCYAmt int                           `xml:"ExcessDistributionCyovAppCYAmt,omitempty"`
	TotalCorpusAmt                 int                           `xml:"TotalCorpusAmt,omitempty"`
	PriorYearUndistributedIncmAmt  int                           `xml:"PriorYearUndistributedIncmAmt,omitempty"`
	PriorYearDeficiencyOrTaxAmt    int                           `xml:"PriorYearDeficiencyOrTaxAmt,omitempty"`
	Taxable1Amt                    int                           `xml:"Taxable1Amt,omitempty"`
	Taxable2Amt                    int                           `xml:"Taxable2Amt,omitempty"`
	UndistributedIncomeCYAmt       int                           `xml:"UndistributedIncomeCYAmt,omitempty"`
	CorpusDistri170b1EOr4942g3Amt  int                           `xml:"CorpusDistri170b1EOr4942g3Amt,omitempty"`
	ExcessDistriCyovFromYr5Amt     int                           `xml:"ExcessDistriCyovFromYr5Amt,omitempty"`
	ExcessDistriCyovToNextYrAmt    int                           `xml:"ExcessDistriCyovToNextYrAmt,omitempty"`
	ExcessFromYear4Amt             int                           `xml:"ExcessFromYear4Amt,omitempty"`
	ExcessFromYear3Amt             int                           `xml:"ExcessFromYear3Amt,omitempty"`
	ExcessFromYear2Amt             int                           `xml:"ExcessFromYear2Amt,omitempty"`
	ExcessFromYear1Amt             int                           `xml:"ExcessFromYear1Amt,omitempty"`
	ExcessFromCurrentYearAmt       int                           `xml:"ExcessFromCurrentYearAmt,omitempty"`
}

// PrivateOperatingFoundationsGrp ...
type PrivateOperatingFoundationsGrp struct {
	PrivateOperatingFndtnRulingDt  string                         `xml:"PrivateOperatingFndtnRulingDt,omitempty"`
	Section4942j3Ind               string                         `xml:"Section4942j3Ind"`
	Section4942j5Ind               string                         `xml:"Section4942j5Ind"`
	LessorAdjNetIncmMinInvstRetGrp *Frm990PFTYPriorYrNNAmtGrpType `xml:"LessorAdjNetIncmMinInvstRetGrp,omitempty"`
	Pct85LessorAdjIncmOrMinRetGrp  *Frm990PFTYPriorYrNNAmtGrpType `xml:"Pct85LessorAdjIncmOrMinRetGrp,omitempty"`
	QualifyingDistributionsGrp     *Frm990PFTYPriorYrNNAmtGrpType `xml:"QualifyingDistributionsGrp,omitempty"`
	QualifyingDistriNotUsedDrtGrp  *Frm990PFTYPriorYrNNAmtGrpType `xml:"QualifyingDistriNotUsedDrtGrp,omitempty"`
	QualifyingDistriMadeDrtGrp     *Frm990PFTYPriorYrAmtGrpType   `xml:"QualifyingDistriMadeDrtGrp,omitempty"`
	TotalAssetsGrp                 *Frm990PFTYPriorYrAmtGrpType   `xml:"TotalAssetsGrp,omitempty"`
	TotalAssetsSect4942j3BiGrp     *Frm990PFTYPriorYrAmtGrpType   `xml:"TotalAssetsSect4942j3BiGrp,omitempty"`
	TwoThirdsMinimumInvstRetGrp    *Frm990PFTYPriorYrAmtGrpType   `xml:"TwoThirdsMinimumInvstRetGrp,omitempty"`
	TotalSupportGrp                *Frm990PFTYPriorYrAmtGrpType   `xml:"TotalSupportGrp,omitempty"`
	PublicSupportType              *Frm990PFTYPriorYrAmtGrpType   `xml:"PublicSupportType,omitempty"`
	LargestSupportFromEOGrp        *Frm990PFTYPriorYrNNAmtGrpType `xml:"LargestSupportFromEOGrp,omitempty"`
	GrossInvestmentIncomeGrp       *Frm990PFTYPriorYrAmtGrpType   `xml:"GrossInvestmentIncomeGrp,omitempty"`
}

// ApplicationSubmissionInfoGrp ...
type ApplicationSubmissionInfoGrp struct {
	RecipientPersonNm          string              `xml:"RecipientPersonNm,omitempty"`
	RecipientUSAddress         *USAddressType      `xml:"RecipientUSAddress"`
	RecipientForeignAddress    *ForeignAddressType `xml:"RecipientForeignAddress"`
	RecipientPhoneNum          string              `xml:"RecipientPhoneNum,omitempty"`
	RecipientEmailAddressTxt   string              `xml:"RecipientEmailAddressTxt,omitempty"`
	FormAndInfoAndMaterialsTxt string              `xml:"FormAndInfoAndMaterialsTxt,omitempty"`
	SubmissionDeadlinesTxt     string              `xml:"SubmissionDeadlinesTxt,omitempty"`
	RestrictionsOnAwardsTxt    string              `xml:"RestrictionsOnAwardsTxt,omitempty"`
}

// SupplementaryInformationGrp ...
type SupplementaryInformationGrp struct {
	ContributingManagerNm         []string                        `xml:"ContributingManagerNm,omitempty"`
	ShareholderManagerNm          []string                        `xml:"ShareholderManagerNm,omitempty"`
	OnlyContriToPreselectedInd    string                          `xml:"OnlyContriToPreselectedInd,omitempty"`
	ApplicationSubmissionInfoGrp  []*ApplicationSubmissionInfoGrp `xml:"ApplicationSubmissionInfoGrp,omitempty"`
	GrantOrContributionPdDurYrGrp []*GrantOrContributionGrpType   `xml:"GrantOrContributionPdDurYrGrp,omitempty"`
	TotalGrantOrContriPdDurYrAmt  int                             `xml:"TotalGrantOrContriPdDurYrAmt,omitempty"`
	GrantOrContriApprvForFutGrp   []*GrantOrContributionGrpType   `xml:"GrantOrContriApprvForFutGrp,omitempty"`
	TotalGrantOrContriApprvFutAmt int                             `xml:"TotalGrantOrContriApprvFutAmt,omitempty"`
}

// SubtotalsIncmProducingActyGrp is Part XV-A Line 12
type SubtotalsIncmProducingActyGrp struct {
	UnrelatedBusinessTaxblIncmAmt  int `xml:"UnrelatedBusinessTaxblIncmAmt,omitempty"`
	ExclusionAmt                   int `xml:"ExclusionAmt,omitempty"`
	RelatedOrExemptFunctionIncmAmt int `xml:"RelatedOrExemptFunctionIncmAmt,omitempty"`
}

// AnalysisIncomeProducingActyGrp ...
type AnalysisIncomeProducingActyGrp struct {
	ProgramServiceRevenueDtl       []*Form990PFGroup1NNType       `xml:"ProgramServiceRevenueDtl,omitempty"`
	FeesContractsFromGovtAgGrp     *Form990PFGroup2NNType         `xml:"FeesContractsFromGovtAgGrp,omitempty"`
	MembershipDuesAndAssmntGrp     *Form990PFGroup2NNType         `xml:"MembershipDuesAndAssmntGrp,omitempty"`
	IntOnSavAndTempCashInvstGrp    *Form990PFGroup2NNType         `xml:"IntOnSavAndTempCashInvstGrp,omitempty"`
	DividendsAndInterestFromSecDtl *Form990PFGroup2NNType         `xml:"DividendsAndInterestFromSecDtl,omitempty"`
	NetRntlIncmReDebtFincdPropGrp  *Form990PFGroup2Type           `xml:"NetRntlIncmReDebtFincdPropGrp,omitempty"`
	NetRntlIncmReNotDebtFincdProp  *Form990PFGroup2Type           `xml:"NetRntlIncmReNotDebtFincdProp,omitempty"`
	NetRentalIncomePersonalPropGrp *Form990PFGroup2Type           `xml:"NetRentalIncomePersonalPropGrp,omitempty"`
	OtherInvestmentIncomeGrp       *Form990PFGroup2NNType         `xml:"OtherInvestmentIncomeGrp,omitempty"`
	GainSalesAstOthThanInvntryGrp  *Form990PFGroup2Type           `xml:"GainSalesAstOthThanInvntryGrp,omitempty"`
	NetIncomeLossFromSpecialEvtGrp *Form990PFGroup2Type           `xml:"NetIncomeLossFromSpecialEvtGrp,omitempty"`
	GrossProfitLossSlsOfInvntryGrp *Form990PFGroup2Type           `xml:"GrossProfitLossSlsOfInvntryGrp,omitempty"`
	OtherRevenueDescribedGrp       []*Form990PFGroup1Type         `xml:"OtherRevenueDescribedGrp,omitempty"`
	SubtotalsIncmProducingActyGrp  *SubtotalsIncmProducingActyGrp `xml:"SubtotalsIncmProducingActyGrp,omitempty"`
	TotalIncomeProducingActyAmt    int                            `xml:"TotalIncomeProducingActyAmt,omitempty"`
}

// RlnOfActyToAccomOfExmptPrpsGrp is Part XV-B
type RlnOfActyToAccomOfExmptPrpsGrp struct {
	LineNumberTxt            interface{} `xml:"LineNumberTxt"`
	RelationshipStatementTxt string      `xml:"RelationshipStatementTxt"`
}

// TrnsfrTransRlnNonchrtblEOGrp ...
type TrnsfrTransRlnNonchrtblEOGrp struct {
	TrnsfrOfCashToNonchrtblEOInd   bool                              `xml:"TrnsfrOfCashToNonchrtblEOInd"`
	TrnsfrOtherAssetNonchrtblEOInd bool                              `xml:"TrnsfrOtherAssetNonchrtblEOInd"`
	SalesOrExchangesOfAssetsInd    bool                              `xml:"SalesOrExchangesOfAssetsInd"`
	PurchaseOfAssetsNonchrtblEOInd bool                              `xml:"PurchaseOfAssetsNonchrtblEOInd"`
	RentalOfFacilitiesOthAssetsInd bool                              `xml:"RentalOfFacilitiesOthAssetsInd"`
	ReimbursementArrangementsInd   bool                              `xml:"ReimbursementArrangementsInd"`
	LoansOrLoanGuaranteesInd       bool                              `xml:"LoansOrLoanGuaranteesInd"`
	PerformanceOfServicesEtcInd    bool                              `xml:"PerformanceOfServicesEtcInd"`
	SharingOfFacilitiesEtcInd      bool                              `xml:"SharingOfFacilitiesEtcInd"`
	TransferScheduleDetail         []*TransferScheduleDetailType     `xml:"TransferScheduleDetail,omitempty"`
	RelationshipsNonchrtblEOInd    bool                              `xml:"RelationshipsNonchrtblEOInd"`
	RelationshipScheduleDetail     []*RelationshipScheduleDetailType `xml:"RelationshipScheduleDetail,omitempty"`
}

// IRS990PFType is Content model for Form 990-PF
type IRS990PFType struct {
	SpecialConditionDesc           []interface{}                   `xml:"SpecialConditionDesc,omitempty"`
	ApplicationPendingInd          string                          `xml:"ApplicationPendingInd,omitempty"`
	ForeignOrganizationInd         string                          `xml:"ForeignOrganizationInd,omitempty"`
	ForeignOrgMeeting85PctTestInd  string                          `xml:"ForeignOrgMeeting85PctTestInd,omitempty"`
	PFStatusTermSect507b1AInd      string                          `xml:"PFStatusTermSect507b1AInd,omitempty"`
	PF60MonthTermSect507b1BInd     string                          `xml:"PF60MonthTermSect507b1BInd,omitempty"`
	InitialReturnInd               string                          `xml:"InitialReturnInd,omitempty"`
	InitialReturnFormerPubChrtyInd string                          `xml:"InitialReturnFormerPubChrtyInd,omitempty"`
	FinalReturnInd                 string                          `xml:"FinalReturnInd,omitempty"`
	AmendedReturnInd               string                          `xml:"AmendedReturnInd,omitempty"`
	AddressChangeInd               string                          `xml:"AddressChangeInd,omitempty"`
	NameChangeInd                  string                          `xml:"NameChangeInd,omitempty"`
	Organization501c3ExemptPFInd   string                          `xml:"Organization501c3ExemptPFInd"`
	Organization4947a1TrtdPFInd    string                          `xml:"Organization4947a1TrtdPFInd"`
	Organization501c3TaxablePFInd  string                          `xml:"Organization501c3TaxablePFInd"`
	FMVAssetsEOYAmt                int                             `xml:"FMVAssetsEOYAmt"`
	MethodOfAccountingCashInd      string                          `xml:"MethodOfAccountingCashInd"`
	MethodOfAccountingAccrualInd   string                          `xml:"MethodOfAccountingAccrualInd"`
	MethodOfAccountingOtherInd     *MethodOfAccountingOtherInd     `xml:"MethodOfAccountingOtherInd"`
	AnalysisOfRevenueAndExpenses   *AnalysisOfRevenueAndExpenses   `xml:"AnalysisOfRevenueAndExpenses"`
	Form990PFBalanceSheetsGrp      *Form990PFBalanceSheetsGrp      `xml:"Form990PFBalanceSheetsGrp"`
	ChgInNetAssetsFundBalancesGrp  *ChgInNetAssetsFundBalancesGrp  `xml:"ChgInNetAssetsFundBalancesGrp,omitempty"`
	CapGainsLossTxInvstIncmDetail  *CapGainsLossTxInvstIncmDetail  `xml:"CapGainsLossTxInvstIncmDetail,omitempty"`
	ExciseTaxBasedOnInvstIncmGrp   *ExciseTaxBasedOnInvstIncmGrp   `xml:"ExciseTaxBasedOnInvstIncmGrp,omitempty"`
	StatementsRegardingActyGrp     *StatementsRegardingActyGrp     `xml:"StatementsRegardingActyGrp,omitempty"`
	StatementsRegardingActy4720Grp *StatementsRegardingActy4720Grp `xml:"StatementsRegardingActy4720Grp,omitempty"`
	OfficerDirTrstKeyEmplInfoGrp   *OfficerDirTrstKeyEmplInfoGrp   `xml:"OfficerDirTrstKeyEmplInfoGrp"`
	SummaryOfDirectChrtblActyGrp   *SummaryOfDirectChrtblActyGrp   `xml:"SummaryOfDirectChrtblActyGrp,omitempty"`
	SumOfProgramRelatedInvstGrp    *SumOfProgramRelatedInvstGrp    `xml:"SumOfProgramRelatedInvstGrp,omitempty"`
	MinimumInvestmentReturnGrp     *MinimumInvestmentReturnGrp     `xml:"MinimumInvestmentReturnGrp,omitempty"`
	DistributableAmountGrp         *DistributableAmountGrp         `xml:"DistributableAmountGrp,omitempty"`
	PFQualifyingDistributionsGrp   *PFQualifyingDistributionsGrp   `xml:"PFQualifyingDistributionsGrp,omitempty"`
	UndistributedIncomeGrp         *UndistributedIncomeGrp         `xml:"UndistributedIncomeGrp,omitempty"`
	PrivateOperatingFoundationsGrp *PrivateOperatingFoundationsGrp `xml:"PrivateOperatingFoundationsGrp,omitempty"`
	SupplementaryInformationGrp    *SupplementaryInformationGrp    `xml:"SupplementaryInformationGrp,omitempty"`
	AnalysisIncomeProducingActyGrp *AnalysisIncomeProducingActyGrp `xml:"AnalysisIncomeProducingActyGrp,omitempty"`
	RlnOfActyToAccomOfExmptPrpsGrp *RlnOfActyToAccomOfExmptPrpsGrp `xml:"RlnOfActyToAccomOfExmptPrpsGrp,omitempty"`
	TrnsfrTransRlnNonchrtblEOGrp   *TrnsfrTransRlnNonchrtblEOGrp   `xml:"TrnsfrTransRlnNonchrtblEOGrp,omitempty"`
}

// Frm990PFTYPriorYrNNAmtGrpType is column (e)
type Frm990PFTYPriorYrNNAmtGrpType struct {
	CurrentYearAmt int `xml:"CurrentYearAmt,omitempty"`
	Year1Amt       int `xml:"Year1Amt,omitempty"`
	Year2Amt       int `xml:"Year2Amt,omitempty"`
	Year3Amt       int `xml:"Year3Amt,omitempty"`
	TotalAmt       int `xml:"TotalAmt,omitempty"`
}

// Frm990PFTYPriorYrAmtGrpType is column (e)
type Frm990PFTYPriorYrAmtGrpType struct {
	CurrentYearAmt int `xml:"CurrentYearAmt,omitempty"`
	Year1Amt       int `xml:"Year1Amt,omitempty"`
	Year2Amt       int `xml:"Year2Amt,omitempty"`
	Year3Amt       int `xml:"Year3Amt,omitempty"`
	TotalAmt       int `xml:"TotalAmt,omitempty"`
}

// GrantOrContributionGrpType is Amount
type GrantOrContributionGrpType struct {
	RecipientPersonNm             string              `xml:"RecipientPersonNm"`
	RecipientBusinessName         *BusinessNameType   `xml:"RecipientBusinessName"`
	RecipientUSAddress            *USAddressType      `xml:"RecipientUSAddress"`
	RecipientForeignAddress       *ForeignAddressType `xml:"RecipientForeignAddress"`
	RecipientRelationshipTxt      string              `xml:"RecipientRelationshipTxt,omitempty"`
	RecipientFoundationStatusTxt  string              `xml:"RecipientFoundationStatusTxt,omitempty"`
	GrantOrContributionPurposeTxt string              `xml:"GrantOrContributionPurposeTxt,omitempty"`
	Amt                           int                 `xml:"Amt,omitempty"`
}


// ExclusionCd is Part XVI-A - Column (C)
type ExclusionCd interface{}

// Form990PFGroup1Type is Description
type Form990PFGroup1Type struct {
	Desc                         string `xml:"Desc,omitempty"`
}

// Form990PFGroup1NNType is Description
type Form990PFGroup1NNType struct {
	Desc                           string `xml:"Desc,omitempty"`
}

// Form990PFGroup2Type ...
type Form990PFGroup2Type struct {}

// Form990PFGroup2NNType ...
type Form990PFGroup2NNType struct {}

// TransferScheduleDetailType ...
type TransferScheduleDetailType struct {
	LineNumberTxt                  interface{}       `xml:"LineNumberTxt,omitempty"`
	InvolvedAmt                    int               `xml:"InvolvedAmt,omitempty"`
	NoncharitableExemptOrgName     *BusinessNameType `xml:"NoncharitableExemptOrgName,omitempty"`
	TransfersTransAndShrArrngmDesc string            `xml:"TransfersTransAndShrArrngmDesc,omitempty"`
}

// RelationshipScheduleDetailType is Part XVII Line 2b Column (c)
type RelationshipScheduleDetailType struct {
	OrganizationBusinessName   *BusinessNameType `xml:"OrganizationBusinessName,omitempty"`
	OrganizationTypeDesc       string            `xml:"OrganizationTypeDesc,omitempty"`
	RelationshipDescriptionTxt string            `xml:"RelationshipDescriptionTxt,omitempty"`
}

// IRS990PFPartVDistriRatioType is A non-negative decimal that allows up to 12 total digits and 6 fraction digits
type IRS990PFPartVDistriRatioType float64
