// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990ScheduleJ is Common return document attributes
type IRS990ScheduleJ struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*IRS990ScheduleJType
}

// RltdOrgOfficerTrstKeyEmplGrp is Part II Column (F)
type RltdOrgOfficerTrstKeyEmplGrp struct {
	PersonNm                       string            `xml:"PersonNm"`
	BusinessName                   *BusinessNameType `xml:"BusinessName"`
	TitleTxt                       string            `xml:"TitleTxt,omitempty"`
	BaseCompensationFilingOrgAmt   int               `xml:"BaseCompensationFilingOrgAmt,omitempty"`
	CompensationBasedOnRltdOrgsAmt int               `xml:"CompensationBasedOnRltdOrgsAmt,omitempty"`
	BonusFilingOrganizationAmount  int               `xml:"BonusFilingOrganizationAmount,omitempty"`
	BonusRelatedOrganizationsAmt   int               `xml:"BonusRelatedOrganizationsAmt,omitempty"`
	OtherCompensationFilingOrgAmt  int               `xml:"OtherCompensationFilingOrgAmt,omitempty"`
	OtherCompensationRltdOrgsAmt   int               `xml:"OtherCompensationRltdOrgsAmt,omitempty"`
	DeferredCompensationFlngOrgAmt int               `xml:"DeferredCompensationFlngOrgAmt,omitempty"`
	DeferredCompRltdOrgsAmt        int               `xml:"DeferredCompRltdOrgsAmt,omitempty"`
	NontaxableBenefitsFilingOrgAmt int               `xml:"NontaxableBenefitsFilingOrgAmt,omitempty"`
	NontaxableBenefitsRltdOrgsAmt  int               `xml:"NontaxableBenefitsRltdOrgsAmt,omitempty"`
	TotalCompensationFilingOrgAmt  int               `xml:"TotalCompensationFilingOrgAmt,omitempty"`
	TotalCompensationRltdOrgsAmt   int               `xml:"TotalCompensationRltdOrgsAmt,omitempty"`
	CompReportPrior990FilingOrgAmt int               `xml:"CompReportPrior990FilingOrgAmt,omitempty"`
	CompReportPrior990RltdOrgsAmt  int               `xml:"CompReportPrior990RltdOrgsAmt,omitempty"`
}


// IRS990ScheduleJType is Part I Line 9
type IRS990ScheduleJType struct {
	FirstClassOrCharterTravelInd   string                           `xml:"FirstClassOrCharterTravelInd,omitempty"`
	TravelForCompanionsInd         string                           `xml:"TravelForCompanionsInd,omitempty"`
	IdemnificationGrossUpPmtsInd   string                           `xml:"IdemnificationGrossUpPmtsInd,omitempty"`
	DiscretionarySpendingAcctInd   string                           `xml:"DiscretionarySpendingAcctInd,omitempty"`
	HousingAllowanceOrResidenceInd string                           `xml:"HousingAllowanceOrResidenceInd,omitempty"`
	PaymentsForUseOfResidenceInd   string                           `xml:"PaymentsForUseOfResidenceInd,omitempty"`
	ClubDuesOrFeesInd              string                           `xml:"ClubDuesOrFeesInd,omitempty"`
	PersonalServicesInd            string                           `xml:"PersonalServicesInd,omitempty"`
	WrittenPolicyRefTAndEExpnssInd bool                             `xml:"WrittenPolicyRefTAndEExpnssInd,omitempty"`
	SubstantiationRequiredInd      bool                             `xml:"SubstantiationRequiredInd,omitempty"`
	CompensationCommitteeInd       string                           `xml:"CompensationCommitteeInd,omitempty"`
	IndependentConsultantInd       string                           `xml:"IndependentConsultantInd,omitempty"`
	Form990OfOtherOrganizationsInd string                           `xml:"Form990OfOtherOrganizationsInd,omitempty"`
	WrittenEmploymentContractInd   string                           `xml:"WrittenEmploymentContractInd,omitempty"`
	CompensationSurveyInd          string                           `xml:"CompensationSurveyInd,omitempty"`
	BoardOrCommitteeApprovalInd    string                           `xml:"BoardOrCommitteeApprovalInd,omitempty"`
	SeverancePaymentInd            bool                             `xml:"SeverancePaymentInd,omitempty"`
	SupplementalNonqualRtrPlanInd  bool                             `xml:"SupplementalNonqualRtrPlanInd,omitempty"`
	EquityBasedCompArrngmInd       bool                             `xml:"EquityBasedCompArrngmInd,omitempty"`
	CompBasedOnRevenueOfFlngOrgInd bool                             `xml:"CompBasedOnRevenueOfFlngOrgInd,omitempty"`
	CompBsdOnRevRelatedOrgsInd     bool                             `xml:"CompBsdOnRevRelatedOrgsInd,omitempty"`
	CompBsdNetEarnsFlngOrgInd      bool                             `xml:"CompBsdNetEarnsFlngOrgInd,omitempty"`
	CompBsdNetEarnsRltdOrgsInd     bool                             `xml:"CompBsdNetEarnsRltdOrgsInd,omitempty"`
	AnyNonFixedPaymentsInd         bool                             `xml:"AnyNonFixedPaymentsInd,omitempty"`
	InitialContractExceptionInd    bool                             `xml:"InitialContractExceptionInd,omitempty"`
	RebuttablePresumptionProcInd   bool                             `xml:"RebuttablePresumptionProcInd,omitempty"`
	RltdOrgOfficerTrstKeyEmplGrp   []*RltdOrgOfficerTrstKeyEmplGrp  `xml:"RltdOrgOfficerTrstKeyEmplGrp,omitempty"`
	SupplementalInformationDetail  []*SupplementalInformationDetail `xml:"SupplementalInformationDetail,omitempty"`
}
