// Code generated by xgen. DO NOT EDIT.

package irsform

// IRS990ScheduleK is Common return document attributes
type IRS990ScheduleK struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*IRS990ScheduleKType
}


// IRS990ScheduleKType is Part V
type IRS990ScheduleKType struct {
	TaxExemptBondsIssuesGrp        []*TaxExemptBondsIssuesGrpType        `xml:"TaxExemptBondsIssuesGrp,omitempty"`
	TaxExemptBondsProceedsGrp      []*TaxExemptBondsProceedsGrpType      `xml:"TaxExemptBondsProceedsGrp,omitempty"`
	TaxExemptBondsPrivateBusUseGrp []*TaxExemptBondsPrivateBusUseGrpType `xml:"TaxExemptBondsPrivateBusUseGrp,omitempty"`
	TaxExemptBondsArbitrageGrp     []*TaxExemptBondsArbitrageGrpType     `xml:"TaxExemptBondsArbitrageGrp,omitempty"`
	ProceduresCorrectiveActionGrp  []*ProceduresCorrectiveActionGrpType  `xml:"ProceduresCorrectiveActionGrp,omitempty"`
	SupplementalInformationDetail  []*SupplementalInformationDetail      `xml:"SupplementalInformationDetail,omitempty"`
}

// TaxExemptBondsIssuesGrpType ...
type TaxExemptBondsIssuesGrpType struct {
	BondReferenceCd     interface{}       `xml:"BondReferenceCd"`
	IssuerName          *BusinessNameType `xml:"IssuerName,omitempty"`
	BondIssuerEIN       string            `xml:"BondIssuerEIN,omitempty"`
	CUSIPNum            string            `xml:"CUSIPNum,omitempty"`
	BondIssuedDt        string            `xml:"BondIssuedDt,omitempty"`
	IssuePriceAmt       int               `xml:"IssuePriceAmt,omitempty"`
	PurposeDesc         string            `xml:"PurposeDesc,omitempty"`
	DefeasedInd         bool              `xml:"DefeasedInd,omitempty"`
	OnBehalfOfIssuerInd bool              `xml:"OnBehalfOfIssuerInd,omitempty"`
	PoolFinancingInd    bool              `xml:"PoolFinancingInd,omitempty"`
}

// TaxExemptBondsProceedsGrpType ...
type TaxExemptBondsProceedsGrpType struct {
	BondReferenceCd               interface{} `xml:"BondReferenceCd"`
	RetiredAmt                    int         `xml:"RetiredAmt,omitempty"`
	BondDefeasedAmt               int         `xml:"BondDefeasedAmt,omitempty"`
	TotalProceedsAmt              int         `xml:"TotalProceedsAmt,omitempty"`
	InReserveFundAmt              int         `xml:"InReserveFundAmt,omitempty"`
	CapitalizedInterestAmt        int         `xml:"CapitalizedInterestAmt,omitempty"`
	RefundingEscrowAmt            int         `xml:"RefundingEscrowAmt,omitempty"`
	IssuanceCostsFromProceedsAmt  int         `xml:"IssuanceCostsFromProceedsAmt,omitempty"`
	CreditEnhancementAmt          int         `xml:"CreditEnhancementAmt,omitempty"`
	WorkingCapitalExpendituresAmt int         `xml:"WorkingCapitalExpendituresAmt,omitempty"`
	CapitalExpendituresAmt        int         `xml:"CapitalExpendituresAmt,omitempty"`
	OtherSpentProceedsAmt         int         `xml:"OtherSpentProceedsAmt,omitempty"`
	UnspentAmt                    int         `xml:"UnspentAmt,omitempty"`
	SubstantialCompletionYr       string      `xml:"SubstantialCompletionYr,omitempty"`
	RefundingTaxExemptBondsInd    bool        `xml:"RefundingTaxExemptBondsInd,omitempty"`
	RefundingTaxableBondsInd      bool        `xml:"RefundingTaxableBondsInd,omitempty"`
	FinalAllocationMadeInd        bool        `xml:"FinalAllocationMadeInd,omitempty"`
	AdequateBooksAndRecMaintInd   bool        `xml:"AdequateBooksAndRecMaintInd,omitempty"`
}

// TaxExemptBondsPrivateBusUseGrpType ...
type TaxExemptBondsPrivateBusUseGrpType struct {
	BondReferenceCd                interface{} `xml:"BondReferenceCd,omitempty"`
	OwningBondFinancedPropertyInd  bool        `xml:"OwningBondFinancedPropertyInd,omitempty"`
	AnyLeaseArrangementsInd        bool        `xml:"AnyLeaseArrangementsInd,omitempty"`
	MgmtContractBondFincdPropInd   bool        `xml:"MgmtContractBondFincdPropInd,omitempty"`
	EngageBondCounselContractsInd  bool        `xml:"EngageBondCounselContractsInd,omitempty"`
	AnyResearchAgreementsInd       bool        `xml:"AnyResearchAgreementsInd,omitempty"`
	EngageBondCounselResearchInd   bool        `xml:"EngageBondCounselResearchInd,omitempty"`
	PrivateBusUseByOthersPct       float64     `xml:"PrivateBusUseByOthersPct,omitempty"`
	PrivateBusConcerningUBIPct     float64     `xml:"PrivateBusConcerningUBIPct,omitempty"`
	TotalPrivateBusinessUsePct     float64     `xml:"TotalPrivateBusinessUsePct,omitempty"`
	BondIssMeetPrvtSecPymtTestInd  bool        `xml:"BondIssMeetPrvtSecPymtTestInd,omitempty"`
	ChangeInUseBondFinancedPropInd bool        `xml:"ChangeInUseBondFinancedPropInd,omitempty"`
	ChangeInUseBondFinancedPropPct float64     `xml:"ChangeInUseBondFinancedPropPct,omitempty"`
	RemedialActionTakenInd         bool        `xml:"RemedialActionTakenInd,omitempty"`
	ProcsNonqualifiedBondRemdtdInd bool        `xml:"ProcsNonqualifiedBondRemdtdInd,omitempty"`
}

// TaxExemptBondsArbitrageGrpType ...
type TaxExemptBondsArbitrageGrpType struct {
	BondReferenceCd               interface{}       `xml:"BondReferenceCd"`
	Form8038TFiledInd             bool              `xml:"Form8038TFiledInd,omitempty"`
	RebateNotDueYetInd            bool              `xml:"RebateNotDueYetInd,omitempty"`
	ExceptionToRebateInd          bool              `xml:"ExceptionToRebateInd,omitempty"`
	NoRebateDueInd                bool              `xml:"NoRebateDueInd,omitempty"`
	VariableRateIssueInd          bool              `xml:"VariableRateIssueInd,omitempty"`
	HedgeIdentifiedInBksAndRecInd bool              `xml:"HedgeIdentifiedInBksAndRecInd,omitempty"`
	HedgeProviderName             *BusinessNameType `xml:"HedgeProviderName,omitempty"`
	TermOfHedgePct                float64           `xml:"TermOfHedgePct,omitempty"`
	SuperintegratedHedgeInd       bool              `xml:"SuperintegratedHedgeInd,omitempty"`
	HedgeTerminatedInd            bool              `xml:"HedgeTerminatedInd,omitempty"`
	GrossProceedsInvestedInGICInd bool              `xml:"GrossProceedsInvestedInGICInd,omitempty"`
	GICProviderName               *BusinessNameType `xml:"GICProviderName,omitempty"`
	TermOfGICPct                  float64           `xml:"TermOfGICPct,omitempty"`
	RegulatorySafeHarborStsfdInd  bool              `xml:"RegulatorySafeHarborStsfdInd,omitempty"`
	GrossProceedsInvestedInd      bool              `xml:"GrossProceedsInvestedInd,omitempty"`
	WrittenProcToMonitorReqsInd   bool              `xml:"WrittenProcToMonitorReqsInd,omitempty"`
}

// ProceduresCorrectiveActionGrpType ...
type ProceduresCorrectiveActionGrpType struct {
	BondReferenceCd               interface{} `xml:"BondReferenceCd"`
	ProceduresCorrectiveActionInd bool        `xml:"ProceduresCorrectiveActionInd,omitempty"`
}
