// Code generated by xgen. DO NOT EDIT.

package irsform

// LandEtcSchedule2 is Common return document attributes
type LandEtcSchedule2 struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*LandEtcSchedule2Type
}

// LandEtcGrp is End of Year Fair Market Value
type LandEtcGrp struct {
	CategoryOrItemTxt          string `xml:"CategoryOrItemTxt,omitempty"`
	CostOrOtherBasisAmt        int    `xml:"CostOrOtherBasisAmt,omitempty"`
	AccumulatedDepreciationAmt int    `xml:"AccumulatedDepreciationAmt,omitempty"`
	BookValueAmt               int    `xml:"BookValueAmt,omitempty"`
	EOYFMVAmt                  int    `xml:"EOYFMVAmt,omitempty"`
}

// LandEtcSchedule2Type is Content model for Land, etc. schedule
type LandEtcSchedule2Type struct {
	LandEtcGrp []*LandEtcGrp `xml:"LandEtcGrp,omitempty"`
}
