// Code generated by xgen. DO NOT EDIT.

package irsform

// LegalFeesSchedule is Common return document attributes
type LegalFeesSchedule struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*LegalFeesScheduleType
}

// LegalFeesGrp is Disbursements for Charitable Purposes
type LegalFeesGrp struct {
	CategoryTxt                    string `xml:"CategoryTxt,omitempty"`
	LegalFeesAmt                   int    `xml:"LegalFeesAmt,omitempty"`
	NetInvestmentIncomeAmt         int    `xml:"NetInvestmentIncomeAmt,omitempty"`
	AdjustedNetIncomeAmt           int    `xml:"AdjustedNetIncomeAmt,omitempty"`
	DisbursementsCharitablePrpsAmt int    `xml:"DisbursementsCharitablePrpsAmt,omitempty"`
}

// LegalFeesScheduleType is Content model for Legal Fees Schedule
type LegalFeesScheduleType struct {
	LegalFeesGrp []*LegalFeesGrp `xml:"LegalFeesGrp,omitempty"`
}
