// Code generated by xgen. DO NOT EDIT.

package irsform

// LiquidationExplanationStmt is Common return document attributes
type LiquidationExplanationStmt struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*LiquidationExplanationStmtType
}

// LiquidationExplanationStmtType is Content model for Liquidation Explanation Statement
type LiquidationExplanationStmtType struct {
	ExplanationTxt string `xml:"ExplanationTxt,omitempty"`
}
