// Code generated by xgen. DO NOT EDIT.

package irsform

// LoansFromOfficersSchedule is Common return document attributes
type LoansFromOfficersSchedule struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*LoansFromOfficersScheduleType
}

// LoansFromOfficersScheduleType is Content model for Loans from officers schedule
type LoansFromOfficersScheduleType struct {
	LoansFromOfficerGrp []*LoansFromOfficerGrpType `xml:"LoansFromOfficerGrp,omitempty"`
}

// LoansFromOfficerGrpType is Consideration FMV
type LoansFromOfficerGrpType struct {
	LenderPersonNm              string  `xml:"LenderPersonNm,omitempty"`
	TitleTxt                    string  `xml:"TitleTxt,omitempty"`
	LoanOriginalAmt             int     `xml:"LoanOriginalAmt,omitempty"`
	BalanceDueAmt               int     `xml:"BalanceDueAmt,omitempty"`
	NoteDt                      string  `xml:"NoteDt,omitempty"`
	LoanMaturityDt              string  `xml:"LoanMaturityDt,omitempty"`
	RepaymentTermsTxt           string  `xml:"RepaymentTermsTxt,omitempty"`
	InterestRt                  float64 `xml:"InterestRt,omitempty"`
	SecurityProvidedBorrowerTxt string  `xml:"SecurityProvidedBorrowerTxt,omitempty"`
	LoanPurposeTxt              string  `xml:"LoanPurposeTxt,omitempty"`
	LenderConsiderationDesc     string  `xml:"LenderConsiderationDesc,omitempty"`
	ConsiderationFMVAmt         int     `xml:"ConsiderationFMVAmt,omitempty"`
}
