// Code generated by xgen. DO NOT EDIT.

package irsform

// MortgagesAndNotesPayableSch is Common return document attributes
type MortgagesAndNotesPayableSch struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*MortgagesAndNotesPayableSchTyp
}

// MortgagesAndNotesPayableSchTyp is Total mortgage amount
type MortgagesAndNotesPayableSchTyp struct {
	MortgageAmt    int                   `xml:"MortgageAmt,omitempty"`
	NotePayableGrp []*NotePayableGrpType `xml:"NotePayableGrp,omitempty"`
}

// LenderNameGrp is Lender's name
type LenderNameGrp struct {
	PersonNm     string            `xml:"PersonNm"`
	BusinessName *BusinessNameType `xml:"BusinessName"`
}

// NotePayableGrpType is Content model for note payable
type NotePayableGrpType struct {
	LenderNameGrp               *LenderNameGrp `xml:"LenderNameGrp,omitempty"`
	TitleTxt                    string         `xml:"TitleTxt,omitempty"`
	InsiderRelationshipTxt      string         `xml:"InsiderRelationshipTxt,omitempty"`
	LoanOriginalAmt             int            `xml:"LoanOriginalAmt,omitempty"`
	BalanceDueAmt               int            `xml:"BalanceDueAmt,omitempty"`
	NoteDt                      string         `xml:"NoteDt,omitempty"`
	LoanMaturityDt              string         `xml:"LoanMaturityDt,omitempty"`
	RepaymentTermsTxt           string         `xml:"RepaymentTermsTxt,omitempty"`
	InterestRt                  float64        `xml:"InterestRt,omitempty"`
	SecurityProvidedBorrowerTxt string         `xml:"SecurityProvidedBorrowerTxt,omitempty"`
	LoanPurposeTxt              string         `xml:"LoanPurposeTxt,omitempty"`
	LenderConsiderationDesc     string         `xml:"LenderConsiderationDesc,omitempty"`
	ConsiderationFMVAmt         int            `xml:"ConsiderationFMVAmt,omitempty"`
}
