// Code generated by xgen. DO NOT EDIT.

package irsform

// OtherIncreasesSchedule is Common return document attributes
type OtherIncreasesSchedule struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*OtherIncreasesScheduleType
}

// OtherIncreasesScheduleType is Content model for Other Increases Schedule
type OtherIncreasesScheduleType struct {
	OtherIncreasesDetail []*USItemizedEntryType `xml:"OtherIncreasesDetail,omitempty"`
}
