// Code generated by xgen. DO NOT EDIT.

package irsform

// OtherAssetsSchedule is Common return document attributes
type OtherAssetsSchedule struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*OtherAssetsScheduleType
}

// OtherAssetsScheduleGrp is End of Year - Fair Market Value
type OtherAssetsScheduleGrp struct {
	Desc            string `xml:"Desc,omitempty"`
	BOYBookValueAmt int    `xml:"BOYBookValueAmt,omitempty"`
	EOYBookValueAmt int    `xml:"EOYBookValueAmt,omitempty"`
	EOYFMVAmt       int    `xml:"EOYFMVAmt,omitempty"`
}

// OtherAssetsScheduleType is Content model for Other Assets Schedule
type OtherAssetsScheduleType struct {
	OtherAssetsScheduleGrp []*OtherAssetsScheduleGrp `xml:"OtherAssetsScheduleGrp,omitempty"`
}
