// Code generated by xgen. DO NOT EDIT.

package irsform

// OtherNotesLoansRcvblShortSch2 is Common return document attributes
type OtherNotesLoansRcvblShortSch2 struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*OtherNotesLoansRcvblShortSch2Type
}

// OtherNotesLoansRcvblShortGrp is Balance Due
type OtherNotesLoansRcvblShortGrp struct {
	Organization501c3Name *BusinessNameType `xml:"Organization501c3Name,omitempty"`
	BalanceDueAmt         int               `xml:"BalanceDueAmt,omitempty"`
}

// OtherNotesLoansRcvblShortSch2Type is Content model for other notes/loans receivable short schedule
type OtherNotesLoansRcvblShortSch2Type struct {
	OtherNotesLoansRcvblShortGrp []*OtherNotesLoansRcvblShortGrp `xml:"OtherNotesLoansRcvblShortGrp,omitempty"`
}
