// Code generated by xgen. DO NOT EDIT.

package irsform

// OtherLiabilitiesSchedule is Common return document attributes
type OtherLiabilitiesSchedule struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*OtherLiabilitiesScheduleType
}

// OtherLiabilitiesDetail is End of Year - Book Value
type OtherLiabilitiesDetail struct {
	Desc            string `xml:"Desc,omitempty"`
	BOYBookValueAmt int    `xml:"BOYBookValueAmt,omitempty"`
	EOYBookValueAmt int    `xml:"EOYBookValueAmt,omitempty"`
}

// OtherLiabilitiesScheduleType is Content model for Other Liabilities Schedule
type OtherLiabilitiesScheduleType struct {
	OtherLiabilitiesDetail []*OtherLiabilitiesDetail `xml:"OtherLiabilitiesDetail,omitempty"`
}
