// Code generated by xgen. DO NOT EDIT.

package irsform

// OtherIncomeSchedule2 is Common return document attributes
type OtherIncomeSchedule2 struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*OtherIncomeSchedule2Type
}

// OtherIncomeDetail is Adjusted Net Income
type OtherIncomeDetail struct {
	Desc                          string `xml:"Desc,omitempty"`
	RevenueAndExpensesPerBooksAmt int    `xml:"RevenueAndExpensesPerBooksAmt,omitempty"`
	NetInvestmentIncomeAmt        int    `xml:"NetInvestmentIncomeAmt,omitempty"`
	AdjustedNetIncomeAmt          int    `xml:"AdjustedNetIncomeAmt,omitempty"`
}

// OtherIncomeSchedule2Type is Content model for Other Income Schedule
type OtherIncomeSchedule2Type struct {
	OtherIncomeDetail []*OtherIncomeDetail `xml:"OtherIncomeDetail,omitempty"`
}
