// Code generated by xgen. DO NOT EDIT.

package irsform

// OtherDecreasesSchedule is Common return document attributes
type OtherDecreasesSchedule struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*OtherDecreasesScheduleType
}

// OtherDecreasesScheduleType is Content model for Other Decreases Schedule
type OtherDecreasesScheduleType struct {
	OtherDecreasesDetail []*USItemizedEntryType `xml:"OtherDecreasesDetail,omitempty"`
}
