// Code generated by xgen. DO NOT EDIT.

package irsform

// OtherProfessionalFeesSchedule is Common return document attributes
type OtherProfessionalFeesSchedule struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*OtherProfessionalFeesScheduleType
}

// OtherProfessionalFeesDetail is Disbursements for Charitable Purposes
type OtherProfessionalFeesDetail struct {
	CategoryTxt                    string `xml:"CategoryTxt,omitempty"`
	Amt                            int    `xml:"Amt,omitempty"`
	NetInvestmentIncomeAmt         int    `xml:"NetInvestmentIncomeAmt,omitempty"`
	AdjustedNetIncomeAmt           int    `xml:"AdjustedNetIncomeAmt,omitempty"`
	DisbursementsCharitablePrpsAmt int    `xml:"DisbursementsCharitablePrpsAmt,omitempty"`
}

// OtherProfessionalFeesScheduleType is Content model for Other Professional Fees Schedule
type OtherProfessionalFeesScheduleType struct {
	OtherProfessionalFeesDetail []*OtherProfessionalFeesDetail `xml:"OtherProfessionalFeesDetail,omitempty"`
}
