// Code generated by xgen. DO NOT EDIT.

package irsform

// OtherReceivablesOfficersSch is Common return document attributes
type OtherReceivablesOfficersSch struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*OtherReceivablesOfficersSchTyp
}

// OtherReceivablesOfficersSchTyp is Travel advances to officers
type OtherReceivablesOfficersSchTyp struct {
	OfficerTravelAdvanceAmt int                         `xml:"OfficerTravelAdvanceAmt,omitempty"`
	OfficerOtherRcvblGrp    []*OfficerOtherRcvblGrpType `xml:"OfficerOtherRcvblGrp,omitempty"`
}

// OfficerOtherRcvblGrpType is Consideration FMV
type OfficerOtherRcvblGrpType struct {
	BorrowerPersonNm            string  `xml:"BorrowerPersonNm,omitempty"`
	BorrowerTitleTxt            string  `xml:"BorrowerTitleTxt,omitempty"`
	LoanOriginalAmt             int     `xml:"LoanOriginalAmt,omitempty"`
	BalanceDueAmt               int     `xml:"BalanceDueAmt,omitempty"`
	NoteDt                      string  `xml:"NoteDt,omitempty"`
	LoanMaturityDt              string  `xml:"LoanMaturityDt,omitempty"`
	RepaymentTermsTxt           string  `xml:"RepaymentTermsTxt,omitempty"`
	InterestRt                  float64 `xml:"InterestRt,omitempty"`
	SecurityProvidedBorrowerTxt string  `xml:"SecurityProvidedBorrowerTxt,omitempty"`
	LoanPurposeTxt              string  `xml:"LoanPurposeTxt,omitempty"`
	LenderConsiderationDesc     string  `xml:"LenderConsiderationDesc,omitempty"`
	ConsiderationFMVAmt         int     `xml:"ConsiderationFMVAmt,omitempty"`
}
