// Code generated by xgen. DO NOT EDIT.

package irsform

// OtherNotesLoansRcvblLongSch is Common return document attributes
type OtherNotesLoansRcvblLongSch struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*OtherNotesLoansRcvblLongSchTyp
}

// OtherNotesLoansRcvblLongSchTyp is Content model for other notes/loans receivable long schedule
type OtherNotesLoansRcvblLongSchTyp struct {
	OtherNotesLoansRcvblLongGrp []*OtherNotesLoansRcvblLongGrpType `xml:"OtherNotesLoansRcvblLongGrp,omitempty"`
}

// BorrowerNameGrp is Borrower's name
type BorrowerNameGrp struct {
	PersonNm     string            `xml:"PersonNm"`
	BusinessName *BusinessNameType `xml:"BusinessName"`
}

// OtherNotesLoansRcvblLongGrpType is Content model for other notes/loans receivable (long)
type OtherNotesLoansRcvblLongGrpType struct {
	BorrowerNameGrp             *BorrowerNameGrp `xml:"BorrowerNameGrp,omitempty"`
	InsiderRelationshipTxt      string           `xml:"InsiderRelationshipTxt,omitempty"`
	LoanOriginalAmt             int              `xml:"LoanOriginalAmt,omitempty"`
	BalanceDueAmt               int              `xml:"BalanceDueAmt,omitempty"`
	NoteDt                      string           `xml:"NoteDt,omitempty"`
	LoanMaturityDt              string           `xml:"LoanMaturityDt,omitempty"`
	RepaymentTermsTxt           string           `xml:"RepaymentTermsTxt,omitempty"`
	InterestRt                  float64          `xml:"InterestRt"`
	SecurityProvidedBorrowerTxt string           `xml:"SecurityProvidedBorrowerTxt,omitempty"`
	LoanPurposeTxt              string           `xml:"LoanPurposeTxt,omitempty"`
	LenderConsiderationDesc     string           `xml:"LenderConsiderationDesc,omitempty"`
	ConsiderationFMVAmt         int              `xml:"ConsiderationFMVAmt,omitempty"`
}
