// Code generated by xgen. DO NOT EDIT.

package irsform

// OtherExpensesSchedule is Common return document attributes
type OtherExpensesSchedule struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*OtherExpensesScheduleType
}

// OtherExpensesScheduleGrp is Disbursements for Charitable Purposes
type OtherExpensesScheduleGrp struct {
	Desc                           string `xml:"Desc,omitempty"`
	RevenueAndExpensesPerBooksAmt  int    `xml:"RevenueAndExpensesPerBooksAmt,omitempty"`
	NetInvestmentIncomeAmt         int    `xml:"NetInvestmentIncomeAmt,omitempty"`
	AdjustedNetIncomeAmt           int    `xml:"AdjustedNetIncomeAmt,omitempty"`
	DisbursementsCharitablePrpsAmt int    `xml:"DisbursementsCharitablePrpsAmt,omitempty"`
}

// OtherExpensesScheduleType is Content model for Other Expenses Schedule
type OtherExpensesScheduleType struct {
	OtherExpensesScheduleGrp []*OtherExpensesScheduleGrp `xml:"OtherExpensesScheduleGrp,omitempty"`
}
