// Code generated by xgen. DO NOT EDIT.

package irsform

// ReasonableCauseExplanation is Common return document attributes
type ReasonableCauseExplanation struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*ReasonableCauseExplanationType
}

// ReasonableCauseExplanationType is Content model for reasonable cause explanation
type ReasonableCauseExplanationType struct {
	ExplanationTxt string `xml:"ExplanationTxt,omitempty"`
}
