// Code generated by xgen. DO NOT EDIT.

package irsform

// ReductionExplanationStatement is Common return document attributes
type ReductionExplanationStatement struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*ReductionExplanationStatementType
}

// ReductionExplanationStatementType is Content model for Reduction Explanation Statement
type ReductionExplanationStatementType struct {
	ShortExplanationTxt string `xml:"ShortExplanationTxt,omitempty"`
}
