// Code generated by xgen. DO NOT EDIT.

package irsform

// RequestForCopyAttachment is Common return document attributes
type RequestForCopyAttachment struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*RequestForCopyAttachmentType
}

// RequestForCopyAttachmentType is Date
type RequestForCopyAttachmentType struct {
	CopyReceiverGovernmentCd []string `xml:"CopyReceiverGovernmentCd"`
	PersonNm                 string   `xml:"PersonNm"`
	PersonTitleTxt           string   `xml:"PersonTitleTxt"`
	PIN                      string   `xml:"PIN"`
	Dt                       string   `xml:"Dt"`
}
