package irsform

// GetFormType returns the form type for ReturnData990EZ
func (r *ReturnData990EZ) GetFormType() string {
	return "990EZ"
}

// ReturnData is Common return data attributes
type ReturnData990EZ struct {
	ReturnDataAttributes           interface{}
	IRS990EZ                       *IRS990EZ   `xml:"IRS990EZ"`
	IRS990ScheduleA                interface{}   `xml:"IRS990ScheduleA,omitempty"`
	IRS990ScheduleB                interface{}   `xml:"IRS990ScheduleB,omitempty"`
	IRS990ScheduleC                interface{}   `xml:"IRS990ScheduleC,omitempty"`
	IRS990ScheduleE                interface{}   `xml:"IRS990ScheduleE,omitempty"`
	IRS990ScheduleG                interface{}   `xml:"IRS990ScheduleG,omitempty"`
	IRS990ScheduleL                interface{}   `xml:"IRS990ScheduleL,omitempty"`
	IRS990ScheduleN                interface{}   `xml:"IRS990ScheduleN,omitempty"`
	IRS990ScheduleO                interface{}   `xml:"IRS990ScheduleO,omitempty"`
	IRS851                         interface{}   `xml:"IRS851,omitempty"`
	IRS926                         []interface{} `xml:"IRS926,omitempty"`
	IRS970                         interface{}   `xml:"IRS970,omitempty"`
	IRS1040ScheduleF               []interface{} `xml:"IRS1040ScheduleF,omitempty"`
	IRS1065ScheduleD               []interface{} `xml:"IRS1065ScheduleD,omitempty"`
	IRS2439                        []interface{} `xml:"IRS2439,omitempty"`
	IRS3115                        interface{}   `xml:"IRS3115,omitempty"`
	IRS3468                        []interface{} `xml:"IRS3468,omitempty"`
	IRS4255                        []interface{} `xml:"IRS4255,omitempty"`
	IRS4562                        []interface{} `xml:"IRS4562,omitempty"`
	IRS4684                        []interface{} `xml:"IRS4684,omitempty"`
	IRS4797                        []interface{} `xml:"IRS4797,omitempty"`
	IRS5452                        []interface{} `xml:"IRS5452,omitempty"`
	IRS5471                        []interface{} `xml:"IRS5471,omitempty"`
	IRS5471ScheduleE               []interface{} `xml:"IRS5471ScheduleE,omitempty"`
	IRS5471ScheduleG1              []interface{} `xml:"IRS5471ScheduleG1,omitempty"`
	IRS5471ScheduleH               []interface{} `xml:"IRS5471ScheduleH,omitempty"`
	IRS5471ScheduleI1              []interface{} `xml:"IRS5471ScheduleI1,omitempty"`
	IRS5471ScheduleJ               []interface{} `xml:"IRS5471ScheduleJ,omitempty"`
	IRS5471ScheduleM               []interface{} `xml:"IRS5471ScheduleM,omitempty"`
	IRS5471ScheduleO               []interface{} `xml:"IRS5471ScheduleO,omitempty"`
	IRS5471ScheduleP               []interface{} `xml:"IRS5471ScheduleP,omitempty"`
	IRS5471ScheduleQ               []interface{} `xml:"IRS5471ScheduleQ,omitempty"`
	IRS5471ScheduleR               []interface{} `xml:"IRS5471ScheduleR,omitempty"`
	IRS5713                        []interface{} `xml:"IRS5713,omitempty"`
	IRS5713ScheduleA               []interface{} `xml:"IRS5713ScheduleA,omitempty"`
	IRS5713ScheduleB               []interface{} `xml:"IRS5713ScheduleB,omitempty"`
	IRS5713ScheduleC               []interface{} `xml:"IRS5713ScheduleC,omitempty"`
	IRS5884                        []interface{} `xml:"IRS5884,omitempty"`
	IRS6478                        []interface{} `xml:"IRS6478,omitempty"`
	IRS6765                        []interface{} `xml:"IRS6765,omitempty"`
	IRS6781                        interface{}   `xml:"IRS6781,omitempty"`
	IRS8275                        []interface{} `xml:"IRS8275,omitempty"`
	IRS8275R                       []interface{} `xml:"IRS8275R,omitempty"`
	IRS8283                        []interface{} `xml:"IRS8283,omitempty"`
	IRS8586                        []interface{} `xml:"IRS8586,omitempty"`
	IRS8594                        []interface{} `xml:"IRS8594,omitempty"`
	IRS8609A                       []interface{} `xml:"IRS8609A,omitempty"`
	IRS8621                        []interface{} `xml:"IRS8621,omitempty"`
	IRS8697                        []interface{} `xml:"IRS8697,omitempty"`
	IRS8820                        []interface{} `xml:"IRS8820,omitempty"`
	IRS8824                        []interface{} `xml:"IRS8824,omitempty"`
	IRS8825                        []interface{} `xml:"IRS8825,omitempty"`
	IRS8826                        []interface{} `xml:"IRS8826,omitempty"`
	IRS8833                        []interface{} `xml:"IRS8833,omitempty"`
	IRS8834                        []interface{} `xml:"IRS8834,omitempty"`
	IRS8835                        []interface{} `xml:"IRS8835,omitempty"`
	IRS8838                        []interface{} `xml:"IRS8838,omitempty"`
	IRS8838P                       []interface{} `xml:"IRS8838P,omitempty"`
	IRS8844                        []interface{} `xml:"IRS8844,omitempty"`
	IRS8845                        []interface{} `xml:"IRS8845,omitempty"`
	IRS8846                        []interface{} `xml:"IRS8846,omitempty"`
	IRS8858                        []interface{} `xml:"IRS8858,omitempty"`
	IRS8858ScheduleM               []interface{} `xml:"IRS8858ScheduleM,omitempty"`
	IRS8864                        []interface{} `xml:"IRS8864,omitempty"`
	IRS8865                        []interface{} `xml:"IRS8865,omitempty"`
	IRS8865ScheduleG               []interface{} `xml:"IRS8865ScheduleG,omitempty"`
	IRS8865ScheduleH               []interface{} `xml:"IRS8865ScheduleH,omitempty"`
	IRS8865ScheduleK1              []interface{} `xml:"IRS8865ScheduleK1,omitempty"`
	IRS8865ScheduleK2              []interface{} `xml:"IRS8865ScheduleK2,omitempty"`
	IRS8865ScheduleK3              []interface{} `xml:"IRS8865ScheduleK3,omitempty"`
	SchK3BaseErosionWorksheetBStmt []interface{} `xml:"SchK3BaseErosionWorksheetBStmt,omitempty"`
	SchK3IntExpnsWorksheetAStmt    []interface{} `xml:"SchK3IntExpnsWorksheetAStmt,omitempty"`
	SchK3Sect267ADsallwDedStmt     []interface{} `xml:"SchK3Sect267ADsallwDedStmt,omitempty"`
	SchedulesK2K31118ScheduleIStmt []interface{} `xml:"SchedulesK2K31118ScheduleIStmt,omitempty"`
	SchK2K3AddnlDtPFICShrAcqStmt   []interface{} `xml:"SchK2K3AddnlDtPFICShrAcqStmt,omitempty"`
	SchK2K3Bss10PctOwnNonCFCStmt   []interface{} `xml:"SchK2K3Bss10PctOwnNonCFCStmt,omitempty"`
	SchK2K3BasisInStockOfCFCStmt   []interface{} `xml:"SchK2K3BasisInStockOfCFCStmt,omitempty"`
	SchK2K3DistriOwnrChainStmt     []interface{} `xml:"SchK2K3DistriOwnrChainStmt,omitempty"`
	SchK2K3FrgnTaxTranslationStmt  []interface{} `xml:"SchK2K3FrgnTaxTranslationStmt,omitempty"`
	SchK2K3HighTxdIncmSch1And2Stmt []interface{} `xml:"SchK2K3HighTxdIncmSch1And2Stmt,omitempty"`
	SchK2K3LoanTransactionsStmt    []interface{} `xml:"SchK2K3LoanTransactionsStmt,omitempty"`
	SchK2K3NIIPTEPSch3And4Stmt     []interface{} `xml:"SchK2K3NIIPTEPSch3And4Stmt,omitempty"`
	SchK2K3OtherDeductionsStmt     []interface{} `xml:"SchK2K3OtherDeductionsStmt,omitempty"`
	SchK2K3OtherIntntlItemsStmt    []interface{} `xml:"SchK2K3OtherIntntlItemsStmt,omitempty"`
	SchK2K3PersonalPropSoldStmt    []interface{} `xml:"SchK2K3PersonalPropSoldStmt,omitempty"`
	SchK2K3Sect743bBasisAdjStmt    []interface{} `xml:"SchK2K3Sect743bBasisAdjStmt,omitempty"`
	SchK2K3SplitterArrngmStmt      []interface{} `xml:"SchK2K3SplitterArrngmStmt,omitempty"`
	IRS8865ScheduleO               []interface{} `xml:"IRS8865ScheduleO,omitempty"`
	IRS8865ScheduleP               []interface{} `xml:"IRS8865ScheduleP,omitempty"`
	IRS8874                        []interface{} `xml:"IRS8874,omitempty"`
	IRS8881                        []interface{} `xml:"IRS8881,omitempty"`
	IRS8882                        []interface{} `xml:"IRS8882,omitempty"`
	IRS8883                        []interface{} `xml:"IRS8883,omitempty"`
	IRS8886                        []interface{} `xml:"IRS8886,omitempty"`
	IRS8896                        []interface{} `xml:"IRS8896,omitempty"`
	IRS8900                        []interface{} `xml:"IRS8900,omitempty"`
	IRS8906                        []interface{} `xml:"IRS8906,omitempty"`
	IRS8908                        []interface{} `xml:"IRS8908,omitempty"`
	IRS8910                        []interface{} `xml:"IRS8910,omitempty"`
	IRS8911                        []interface{} `xml:"IRS8911,omitempty"`
	IRS8912                        []interface{} `xml:"IRS8912,omitempty"`
	IRS8923                        []interface{} `xml:"IRS8923,omitempty"`
	IRS8925                        interface{}   `xml:"IRS8925,omitempty"`
	IRS8932                        []interface{} `xml:"IRS8932,omitempty"`
	IRS8949                        []interface{} `xml:"IRS8949,omitempty"`
	IRS8990                        []interface{} `xml:"IRS8990,omitempty"`
	IRS8997                        interface{}   `xml:"IRS8997,omitempty"`
	IRSFormT                       []interface{} `xml:"IRSFormT,omitempty"`
	CompensationExplanation        []interface{} `xml:"CompensationExplanation,omitempty"`
	ContractorCompensationExpln    []interface{} `xml:"ContractorCompensationExpln,omitempty"`
	EmployeeCompensationExpln      interface{}   `xml:"EmployeeCompensationExpln,omitempty"`
	ReasonableCauseExplanation     interface{}   `xml:"ReasonableCauseExplanation,omitempty"`
	TransferPrsnlBnftContractsDecl interface{}   `xml:"TransferPrsnlBnftContractsDecl,omitempty"`
	AffiliatedGroupAttachment      interface{}   `xml:"AffiliatedGroupAttachment,omitempty"`
	AffiliatedGroupSchedule        interface{}   `xml:"AffiliatedGroupSchedule,omitempty"`
	AveragingAttachment            interface{}   `xml:"AveragingAttachment,omitempty"`
	BscAdjUnderSect367a5Stmt       []interface{} `xml:"BscAdjUnderSect367a5Stmt,omitempty"`
	ExchGainRcgnzSect987TrnsfrStmt []interface{} `xml:"ExchGainRcgnzSect987TrnsfrStmt,omitempty"`
	GainRcgnzSect904f3TrnsfrStmt   []interface{} `xml:"GainRcgnzSect904f3TrnsfrStmt,omitempty"`
	GainRcgnzSect904f5FTrnsfrStmt  []interface{} `xml:"GainRcgnzSect904f5FTrnsfrStmt,omitempty"`
	RecaptureSect1503dTrnsfrStmt   []interface{} `xml:"RecaptureSect1503dTrnsfrStmt,omitempty"`
	AdjNotIncldInIncmOver3YrsExpln []interface{} `xml:"AdjNotIncldInIncmOver3YrsExpln,omitempty"`
	BLSPriceIndexRepMonthStmt      []interface{} `xml:"BLSPriceIndexRepMonthStmt,omitempty"`
	CostSystemUsedStatement        []interface{} `xml:"CostSystemUsedStatement,omitempty"`
	CreditReportIssuedStatement    []interface{} `xml:"CreditReportIssuedStatement,omitempty"`
	DetailedAnlysOfInventoriesStmt []interface{} `xml:"DetailedAnlysOfInventoriesStmt,omitempty"`
	GoodsAcqAtBelowMrktPricesStmt  []interface{} `xml:"GoodsAcqAtBelowMrktPricesStmt,omitempty"`
	GoodsNotTreatedAsAcquiredExpln []interface{} `xml:"GoodsNotTreatedAsAcquiredExpln,omitempty"`
	InventoryNotValuedAtCostExpln  []interface{} `xml:"InventoryNotValuedAtCostExpln,omitempty"`
	InvntryMthdUsedForPrTYStmt     []interface{} `xml:"InvntryMthdUsedForPrTYStmt,omitempty"`
	InvntryNotTakenAtActlCostExpln []interface{} `xml:"InvntryNotTakenAtActlCostExpln,omitempty"`
	LIFOCmptMthdForValuePoolingAtt []interface{} `xml:"LIFOCmptMthdForValuePoolingAtt,omitempty"`
	LIFOInvntryMthdNotUsedGoodStmt []interface{} `xml:"LIFOInvntryMthdNotUsedGoodStmt,omitempty"`
	LIFOInventoryMethodUsedBfrStmt []interface{} `xml:"LIFOInventoryMethodUsedBfrStmt,omitempty"`
	MethodOfDefiningItemsStatement []interface{} `xml:"MethodOfDefiningItemsStatement,omitempty"`
	OpngAndClsGoodsComparisonStmt  []interface{} `xml:"OpngAndClsGoodsComparisonStmt,omitempty"`
	OtherDollarValueMthdUsedExpln  []interface{} `xml:"OtherDollarValueMthdUsedExpln,omitempty"`
	OtherMethodUsedExplanation     []interface{} `xml:"OtherMethodUsedExplanation,omitempty"`
	OtherTablePPIDetailedRptStmt   []interface{} `xml:"OtherTablePPIDetailedRptStmt,omitempty"`
	OthGdsInvntryAndLIFOMthdStmt   []interface{} `xml:"OthGdsInvntryAndLIFOMthdStmt,omitempty"`
	PoolingMethodStatement         []interface{} `xml:"PoolingMethodStatement,omitempty"`
	StatementInLieuOfForm970       []interface{} `xml:"StatementInLieuOfForm970,omitempty"`
	CCCLoanDetailAccrualMethodStmt []interface{} `xml:"CCCLoanDetailAccrualMethodStmt,omitempty"`
	CCCLoanDetailCashMethodStmt    []interface{} `xml:"CCCLoanDetailCashMethodStmt,omitempty"`
	ExplnOfAddnlInterestDedStmt    []interface{} `xml:"ExplnOfAddnlInterestDedStmt,omitempty"`
	Form1098RecipientsStatement    []interface{} `xml:"Form1098RecipientsStatement,omitempty"`
	PostponementCropInsDsstrStmt   []interface{} `xml:"PostponementCropInsDsstrStmt,omitempty"`
	Collectables28PctGainStmt      []interface{} `xml:"Collectables28PctGainStmt,omitempty"`
	BadDebtDeductionStmt           []interface{} `xml:"BadDebtDeductionStmt,omitempty"`
	CostBasisStmt                  []interface{} `xml:"CostBasisStmt,omitempty"`
	RolloverGainFromQualifiedStock []interface{} `xml:"RolloverGainFromQualifiedStock,omitempty"`
	AffltGroupFilingCnsldtRetStmt  []interface{} `xml:"AffltGroupFilingCnsldtRetStmt,omitempty"`
	AllocnCapitalizationMthdStmt   []interface{} `xml:"AllocnCapitalizationMthdStmt,omitempty"`
	AppealsFederalCourtExplnStmt   []interface{} `xml:"AppealsFederalCourtExplnStmt,omitempty"`
	ApplcntNotRcvAudProtectionStmt []interface{} `xml:"ApplcntNotRcvAudProtectionStmt,omitempty"`
	ApplicantEligChgMthdAcctStmt   []interface{} `xml:"ApplicantEligChgMthdAcctStmt,omitempty"`
	ApplicantsContractsStatement   []interface{} `xml:"ApplicantsContractsStatement,omitempty"`
	ApplcntRcvdAudProtectionStmt   []interface{} `xml:"ApplcntRcvdAudProtectionStmt,omitempty"`
	ApplicantsRsnProposedChgStmt   []interface{} `xml:"ApplicantsRsnProposedChgStmt,omitempty"`
	AppWithdrwNotPerfDndCnsntStmt  []interface{} `xml:"AppWithdrwNotPerfDndCnsntStmt,omitempty"`
	BusDisqualifiesAutoCnsntStmt   []interface{} `xml:"BusDisqualifiesAutoCnsntStmt,omitempty"`
	ChangeInOverallMthdOfAcctStmt  []interface{} `xml:"ChangeInOverallMthdOfAcctStmt,omitempty"`
	ChangeInValuingInventoriesStmt []interface{} `xml:"ChangeInValuingInventoriesStmt,omitempty"`
	ChangeLIFOToNonLIFOMethodStmt  []interface{} `xml:"ChangeLIFOToNonLIFOMethodStmt,omitempty"`
	ChangeToCashMethodStatement    []interface{} `xml:"ChangeToCashMethodStatement,omitempty"`
	ChangeToIPICMethodStatement    []interface{} `xml:"ChangeToIPICMethodStatement,omitempty"`
	ChgInAcctMthdOrPrdPast5YrsStmt []interface{} `xml:"ChgInAcctMthdOrPrdPast5YrsStmt,omitempty"`
	ChgInOverallMthdBreakdownStmt  []interface{} `xml:"ChgInOverallMthdBreakdownStmt,omitempty"`
	ChgToDepreciateAmortzPropStmt  []interface{} `xml:"ChgToDepreciateAmortzPropStmt,omitempty"`
	CodeSectPropDeprecOrAmortzStmt []interface{} `xml:"CodeSectPropDeprecOrAmortzStmt,omitempty"`
	ComputationOfSect481aAdjStmt   []interface{} `xml:"ComputationOfSect481aAdjStmt,omitempty"`
	ConsolidatedGroupInfoStmt      []interface{} `xml:"ConsolidatedGroupInfoStmt,omitempty"`
	CostComparisonOrMethodUsedStmt []interface{} `xml:"CostComparisonOrMethodUsedStmt,omitempty"`
	DeferralMethodAdvancePayments  []interface{} `xml:"DeferralMethodAdvancePayments,omitempty"`
	DescOfInvntryGoodsChangedStmt  []interface{} `xml:"DescOfInvntryGoodsChangedStmt,omitempty"`
	DescOfInvntryGoodsNotChgdStmt  []interface{} `xml:"DescOfInvntryGoodsNotChgdStmt,omitempty"`
	DescOfPropertyBeingChangedStmt []interface{} `xml:"DescOfPropertyBeingChangedStmt,omitempty"`
	ExceptionUnderSection460eStmt  []interface{} `xml:"ExceptionUnderSection460eStmt,omitempty"`
	ExplnPropTrtdUndPresMthdStmt   []interface{} `xml:"ExplnPropTrtdUndPresMthdStmt,omitempty"`
	IncmRcvdOrRptBeforeEarnedStmt  []interface{} `xml:"IncmRcvdOrRptBeforeEarnedStmt,omitempty"`
	InvntryValuationMthdStatement  []interface{} `xml:"InvntryValuationMthdStatement,omitempty"`
	LegalBasisForChangeStatement   []interface{} `xml:"LegalBasisForChangeStatement,omitempty"`
	LIFOInventoryOtherThanCostStmt []interface{} `xml:"LIFOInventoryOtherThanCostStmt,omitempty"`
	LongTermContractsStatement     []interface{} `xml:"LongTermContractsStatement,omitempty"`
	LTManufacturingContractsStmt   []interface{} `xml:"LTManufacturingContractsStmt,omitempty"`
	ManufacturingProposedPoolStmt  []interface{} `xml:"ManufacturingProposedPoolStmt,omitempty"`
	MfrGoodsSoldOrDistributedStmt  []interface{} `xml:"MfrGoodsSoldOrDistributedStmt,omitempty"`
	MthdAllocnNotSect263Aor460Stmt []interface{} `xml:"MthdAllocnNotSect263Aor460Stmt,omitempty"`
	NonAutomaticChgReqProcStmt     []interface{} `xml:"NonAutomaticChgReqProcStmt,omitempty"`
	OtherAmountsStatement          []interface{} `xml:"OtherAmountsStatement,omitempty"`
	OtherCostsNotReqrToBeAllocAtt  []interface{} `xml:"OtherCostsNotReqrToBeAllocAtt,omitempty"`
	OtherDirectAndIndirectCostsAtt []interface{} `xml:"OtherDirectAndIndirectCostsAtt,omitempty"`
	OtherIdAndValuationMethodsStmt []interface{} `xml:"OtherIdAndValuationMethodsStmt,omitempty"`
	OverallMethodOfAccountingAtt   []interface{} `xml:"OverallMethodOfAccountingAtt,omitempty"`
	ParentCorpInformationStmt      []interface{} `xml:"ParentCorpInformationStmt,omitempty"`
	PresentAndProposedLIFOMthdStmt []interface{} `xml:"PresentAndProposedLIFOMthdStmt,omitempty"`
	PresentHybridMethodOfAcctAtt   []interface{} `xml:"PresentHybridMethodOfAcctAtt,omitempty"`
	PresentMethodDiffExplnStmt     []interface{} `xml:"PresentMethodDiffExplnStmt,omitempty"`
	ProposedHybridMethodOfAcctAtt  []interface{} `xml:"ProposedHybridMethodOfAcctAtt,omitempty"`
	ProposedNaturalBusUnitStmt     []interface{} `xml:"ProposedNaturalBusUnitStmt,omitempty"`
	PrpsdChgNotForLIFOInvntryStmt  []interface{} `xml:"PrpsdChgNotForLIFOInvntryStmt,omitempty"`
	PrpsdChgNotForLIFOPoolsStmt    []interface{} `xml:"PrpsdChgNotForLIFOPoolsStmt,omitempty"`
	PrpsdChgPoolingInventoriesStmt []interface{} `xml:"PrpsdChgPoolingInventoriesStmt,omitempty"`
	PrvtLtrRlngAcctMthdChgTechStmt []interface{} `xml:"PrvtLtrRlngAcctMthdChgTechStmt,omitempty"`
	ReducedUserFeeStatement        []interface{} `xml:"ReducedUserFeeStatement,omitempty"`
	ReqToDeferUndRegSect14515Stmt  []interface{} `xml:"ReqToDeferUndRegSect14515Stmt,omitempty"`
	RequireUseCutOffBasisStatement []interface{} `xml:"RequireUseCutOffBasisStatement,omitempty"`
	Section481aAdjustmentStatement []interface{} `xml:"Section481aAdjustmentStatement,omitempty"`
	TradeOrBusinessStatement       []interface{} `xml:"TradeOrBusinessStatement,omitempty"`
	UnableToFurnishCopyOf970Stmt   []interface{} `xml:"UnableToFurnishCopyOf970Stmt,omitempty"`
	UseOfProposedMethodOfAcctStmt  []interface{} `xml:"UseOfProposedMethodOfAcctStmt,omitempty"`
	WholesaleRetailPrpsdPoolsStmt  []interface{} `xml:"WholesaleRetailPrpsdPoolsStmt,omitempty"`
	MultiLesseePropStmt            []interface{} `xml:"MultiLesseePropStmt,omitempty"`
	Sect14812b2viiiAdjBssBldgStmt  []interface{} `xml:"Sect14812b2viiiAdjBssBldgStmt,omitempty"`
	Pre1936BuildingsSchedule       []interface{} `xml:"Pre1936BuildingsSchedule,omitempty"`
	CertifiedHistoricStructuresSch []interface{} `xml:"CertifiedHistoricStructuresSch,omitempty"`
	OtherCertHistoricStructuresSch interface{}   `xml:"OtherCertHistoricStructuresSch,omitempty"`
	RehabilitationCrExplanation    interface{}   `xml:"RehabilitationCrExplanation,omitempty"`
	QlfyThrputicDiscvProjectCrStmt []interface{} `xml:"QlfyThrputicDiscvProjectCrStmt,omitempty"`
	ADS50YearDeductionStatement    []interface{} `xml:"ADS50YearDeductionStatement,omitempty"`
	AmortizationElectionStatement  []interface{} `xml:"AmortizationElectionStatement,omitempty"`
	GDS50YearDeductionStatement    []interface{} `xml:"GDS50YearDeductionStatement,omitempty"`
	Section168f1PropertyStatement  []interface{} `xml:"Section168f1PropertyStatement,omitempty"`
	DeductibleLossComputationStmt  []interface{} `xml:"DeductibleLossComputationStmt,omitempty"`
	UnexcludedExcessGainStmt       interface{}   `xml:"UnexcludedExcessGainStmt,omitempty"`
	OriginalOrAmendedRtnStmt       []interface{} `xml:"OriginalOrAmendedRtnStmt,omitempty"`
	SecOrCommoditiesHeldByTrader   []interface{} `xml:"SecOrCommoditiesHeldByTrader,omitempty"`
	SmallBusInvstCompanyStockStmt  []interface{} `xml:"SmallBusInvstCompanyStockStmt,omitempty"`
	NoncashDistriTaxBasisAndFMVSch []interface{} `xml:"NoncashDistriTaxBasisAndFMVSch,omitempty"`
	ParentSupportingInfoAttachment []interface{} `xml:"ParentSupportingInfoAttachment,omitempty"`
	ExplnNondivDistriCorpLiqStmt   []interface{} `xml:"ExplnNondivDistriCorpLiqStmt,omitempty"`
	SupportingInfoAttachment       []interface{} `xml:"SupportingInfoAttachment,omitempty"`
	Category3FilerStatement        []interface{} `xml:"Category3FilerStatement,omitempty"`
	CFCQuestionsStatement          []interface{} `xml:"CFCQuestionsStatement,omitempty"`
	CFCAggregateEDBalanceStatement []interface{} `xml:"CFCAggregateEDBalanceStatement,omitempty"`
	EarningsAndProfitsOtherAdjStmt []interface{} `xml:"EarningsAndProfitsOtherAdjStmt,omitempty"`
	ExpatriatedFrgnSubsidiaryStmt  []interface{} `xml:"ExpatriatedFrgnSubsidiaryStmt,omitempty"`
	ExplanationOfBlockedIncomeStmt []interface{} `xml:"ExplanationOfBlockedIncomeStmt,omitempty"`
	IncomeTaxReturnsStatement      []interface{} `xml:"IncomeTaxReturnsStatement,omitempty"`
	InvestmentInSubsidiariesStmt   []interface{} `xml:"InvestmentInSubsidiariesStmt,omitempty"`
	ItemizedOthCurrLiabilitiesSch  []interface{} `xml:"ItemizedOthCurrLiabilitiesSch,omitempty"`
	ItemizedOtherAssetsSchedule    []interface{} `xml:"ItemizedOtherAssetsSchedule,omitempty"`
	ItemizedOtherCurrentAssetsSch  []interface{} `xml:"ItemizedOtherCurrentAssetsSch,omitempty"`
	ItemizedOtherDeductionSch2     []interface{} `xml:"ItemizedOtherDeductionSch2,omitempty"`
	ItemizedOtherInvestmentsSch    []interface{} `xml:"ItemizedOtherInvestmentsSch,omitempty"`
	ItemizedOtherLiabilitiesSch    []interface{} `xml:"ItemizedOtherLiabilitiesSch,omitempty"`
	NameChangeExplanation          []interface{} `xml:"NameChangeExplanation,omitempty"`
	OtherIncomeForm5471Statement   []interface{} `xml:"OtherIncomeForm5471Statement,omitempty"`
	OwnsForeignEntitiesStatement   []interface{} `xml:"OwnsForeignEntitiesStatement,omitempty"`
	OwnsForeignPartnershipStmt     []interface{} `xml:"OwnsForeignPartnershipStmt,omitempty"`
	PaidInOrCapSurplusRecnclStmt   []interface{} `xml:"PaidInOrCapSurplusRecnclStmt,omitempty"`
	PersonMeetingFilingRqrStmt     []interface{} `xml:"PersonMeetingFilingRqrStmt,omitempty"`
	PlatformContributionStatement  []interface{} `xml:"PlatformContributionStatement,omitempty"`
	ShareholderEDBalanceStatement  []interface{} `xml:"ShareholderEDBalanceStatement,omitempty"`
	BalanceAtBOYExplanationStmt    []interface{} `xml:"BalanceAtBOYExplanationStmt,omitempty"`
	EPOtherAdjustmentStatement     []interface{} `xml:"EPOtherAdjustmentStatement,omitempty"`
	OtherAmountsPaidStatement      []interface{} `xml:"OtherAmountsPaidStatement,omitempty"`
	OtherAmountsReceivedStatement  []interface{} `xml:"OtherAmountsReceivedStatement,omitempty"`
	RetFiledForPrior3YearsStmt     []interface{} `xml:"RetFiledForPrior3YearsStmt,omitempty"`
	ShareholdersBecameUSPersonStmt []interface{} `xml:"ShareholdersBecameUSPersonStmt,omitempty"`
	OtherExpensesSchedule2         []interface{} `xml:"OtherExpensesSchedule2,omitempty"`
	BoycottAgreementsStatement     []interface{} `xml:"BoycottAgreementsStatement,omitempty"`
	BoycottRequestsStatement       []interface{} `xml:"BoycottRequestsStatement,omitempty"`
	CommonTaxableYearElectionStmt  []interface{} `xml:"CommonTaxableYearElectionStmt,omitempty"`
	ControlledGroupMemberStatement []interface{} `xml:"ControlledGroupMemberStatement,omitempty"`
	DeductionDifferentiationStmt   []interface{} `xml:"DeductionDifferentiationStmt,omitempty"`
	ExplnDisposNotToAvoidTaxStmt   []interface{} `xml:"ExplnDisposNotToAvoidTaxStmt,omitempty"`
	SmallEthanolProducerCrElection []interface{} `xml:"SmallEthanolProducerCrElection,omitempty"`
	CapExpensesDedAmountsSch       []interface{} `xml:"CapExpensesDedAmountsSch,omitempty"`
	MembersOfControlledGroupStmt   []interface{} `xml:"MembersOfControlledGroupStmt,omitempty"`
	ExplanationOfForm1099BAdjSch   []interface{} `xml:"ExplanationOfForm1099BAdjSch,omitempty"`
	ListOfForeignCurContractsStmt  []interface{} `xml:"ListOfForeignCurContractsStmt,omitempty"`
	MixedStraddleAcctElectionStmt  []interface{} `xml:"MixedStraddleAcctElectionStmt,omitempty"`
	ShortLongTermGainsSchedule     []interface{} `xml:"ShortLongTermGainsSchedule,omitempty"`
	ShortLongTermLossesSchedule    []interface{} `xml:"ShortLongTermLossesSchedule,omitempty"`
	StraddlesAndComponentsSchedule []interface{} `xml:"StraddlesAndComponentsSchedule,omitempty"`
	ContemporaneousWrittenAckStmt  []interface{} `xml:"ContemporaneousWrittenAckStmt,omitempty"`
	ContriVehicleBoatAirplaneStmt  []interface{} `xml:"ContriVehicleBoatAirplaneStmt,omitempty"`
	DeductionsUnderSection170Stmt  []interface{} `xml:"DeductionsUnderSection170Stmt,omitempty"`
	DoneesSignatureUnavailableStmt []interface{} `xml:"DoneesSignatureUnavailableStmt,omitempty"`
	FairMarketValueStatement       []interface{} `xml:"FairMarketValueStatement,omitempty"`
	QlfyConservationContriStmt     []interface{} `xml:"QlfyConservationContriStmt,omitempty"`
	ReasonableCauseStatement       []interface{} `xml:"ReasonableCauseStatement,omitempty"`
	RestrictedUseStatement         []interface{} `xml:"RestrictedUseStatement,omitempty"`
	MultipleBuildingProjectSch     []interface{} `xml:"MultipleBuildingProjectSch,omitempty"`
	PassThroughEntitySchedule      []interface{} `xml:"PassThroughEntitySchedule,omitempty"`
	ConsiderationCmptStatement     []interface{} `xml:"ConsiderationCmptStatement,omitempty"`
	ReasonsIncreaseOrDecreaseStmt  []interface{} `xml:"ReasonsIncreaseOrDecreaseStmt,omitempty"`
	DeemedDivElectFrmrPFICStmt     []interface{} `xml:"DeemedDivElectFrmrPFICStmt,omitempty"`
	DeemedDivElectSec1297ePFICStmt []interface{} `xml:"DeemedDivElectSec1297ePFICStmt,omitempty"`
	DeemedDividendElectionStmt     []interface{} `xml:"DeemedDividendElectionStmt,omitempty"`
	GainOrLossMrktToMrktElectStmt  []interface{} `xml:"GainOrLossMrktToMrktElectStmt,omitempty"`
	QEFDistributionStatement       []interface{} `xml:"QEFDistributionStatement,omitempty"`
	ShareholdersStockOwnershipStmt []interface{} `xml:"ShareholdersStockOwnershipStmt,omitempty"`
	TaxationOfExcessDistriStmt     []interface{} `xml:"TaxationOfExcessDistriStmt,omitempty"`
	AdjLongTermContractsFromK1Sch  []interface{} `xml:"AdjLongTermContractsFromK1Sch,omitempty"`
	AdjLTContractsSimplifiedK1Sch  []interface{} `xml:"AdjLTContractsSimplifiedK1Sch,omitempty"`
	AdjLTContractsSimplifiedSch    []interface{} `xml:"AdjLTContractsSimplifiedSch,omitempty"`
	AdjustmentLongTermContractsSch []interface{} `xml:"AdjustmentLongTermContractsSch,omitempty"`
	AltMethodInterestCmptStmt      []interface{} `xml:"AltMethodInterestCmptStmt,omitempty"`
	AltMinTxblIncmAdjSimplifiedSch []interface{} `xml:"AltMinTxblIncmAdjSimplifiedSch,omitempty"`
	AltMinTxblIncmAdjSmplfdK1Sch   []interface{} `xml:"AltMinTxblIncmAdjSmplfdK1Sch,omitempty"`
	IDOfPassThruEntitiesStmt       []interface{} `xml:"IDOfPassThruEntitiesStmt,omitempty"`
	PrincipalPrpsRltdPartyExchStmt []interface{} `xml:"PrincipalPrpsRltdPartyExchStmt,omitempty"`
	GainInMultiAssetExchangesStmt  []interface{} `xml:"GainInMultiAssetExchangesStmt,omitempty"`
	AllocationToPatronsStatement   interface{}   `xml:"AllocationToPatronsStatement,omitempty"`
	ControlledGroupMembersStmt     interface{}   `xml:"ControlledGroupMembersStmt,omitempty"`
	ControlledGroupOrBusinessStmt  interface{}   `xml:"ControlledGroupOrBusinessStmt,omitempty"`
	ComputationForTippedEmplSch    []interface{} `xml:"ComputationForTippedEmplSch,omitempty"`
	AccountingMethodChangeStmt     []interface{} `xml:"AccountingMethodChangeStmt,omitempty"`
	ElectiveReliefAgrmtOrCertStmt  []interface{} `xml:"ElectiveReliefAgrmtOrCertStmt,omitempty"`
	EPTaxableIncomeAdjustmentSch   []interface{} `xml:"EPTaxableIncomeAdjustmentSch,omitempty"`
	MultRecipientRemittanceStmt    interface{}   `xml:"MultRecipientRemittanceStmt,omitempty"`
	OrganizationChartStatement     []interface{} `xml:"OrganizationChartStatement,omitempty"`
	SchITrnsfrLossAmtAddnlInfoStmt []interface{} `xml:"SchITrnsfrLossAmtAddnlInfoStmt,omitempty"`
	Section987GainLossDeferredStmt []interface{} `xml:"Section987GainLossDeferredStmt,omitempty"`
	Section987GainOrLossStmt       []interface{} `xml:"Section987GainOrLossStmt,omitempty"`
	Owned10PctIntForeignPrtshpStmt []interface{} `xml:"Owned10PctIntForeignPrtshpStmt,omitempty"`
	EvdncofPrevFldClmBiodieselStmt []interface{} `xml:"EvdncofPrevFldClmBiodieselStmt,omitempty"`
	AdjustedGainLossSchedule       []interface{} `xml:"AdjustedGainLossSchedule,omitempty"`
	BadDebtStatement               []interface{} `xml:"BadDebtStatement,omitempty"`
	BalanceSheetsAgreeStatement    []interface{} `xml:"BalanceSheetsAgreeStatement,omitempty"`
	BusStartupOrgnztnlCostStmt     []interface{} `xml:"BusStartupOrgnztnlCostStmt,omitempty"`
	CapitalGainDistributions       []interface{} `xml:"CapitalGainDistributions,omitempty"`
	CharitableContriSchedule       []interface{} `xml:"CharitableContriSchedule,omitempty"`
	ControlledForeignPrtshpStmt    []interface{} `xml:"ControlledForeignPrtshpStmt,omitempty"`
	CostOthThanActualCashCostStmt  []interface{} `xml:"CostOthThanActualCashCostStmt,omitempty"`
	DedDisallowedComputationStmt   []interface{} `xml:"DedDisallowedComputationStmt,omitempty"`
	DedOtherCategoriesSchedule     []interface{} `xml:"DedOtherCategoriesSchedule,omitempty"`
	DistributionsOfMoneyStatement  []interface{} `xml:"DistributionsOfMoneyStatement,omitempty"`
	DistriOfPropOtherThanMoneyStmt []interface{} `xml:"DistriOfPropOtherThanMoneyStmt,omitempty"`
	DomesticProdActyStmt           []interface{} `xml:"DomesticProdActyStmt,omitempty"`
	ExpensesOtherRentalActySch     []interface{} `xml:"ExpensesOtherRentalActySch,omitempty"`
	FrgnGrossAtPrtshpLvlOthCatSch  []interface{} `xml:"FrgnGrossAtPrtshpLvlOthCatSch,omitempty"`
	FuncCurAndExchangeRateQBUStmt  []interface{} `xml:"FuncCurAndExchangeRateQBUStmt,omitempty"`
	GrossIncmOilGasGthrmlPropStmt  []interface{} `xml:"GrossIncmOilGasGthrmlPropStmt,omitempty"`
	GrossIncmSourcedAtPrtnrLvlSch  []interface{} `xml:"GrossIncmSourcedAtPrtnrLvlSch,omitempty"`
	GrossReceiptsInstalSalesSch    []interface{} `xml:"GrossReceiptsInstalSalesSch,omitempty"`
	ItemizedDedNotChargedBooksSch2 []interface{} `xml:"ItemizedDedNotChargedBooksSch2,omitempty"`
	ItemizedExpensesRecOnBooksSch2 []interface{} `xml:"ItemizedExpensesRecOnBooksSch2,omitempty"`
	ItemizedIncmNotRecOnBooksSch2  []interface{} `xml:"ItemizedIncmNotRecOnBooksSch2,omitempty"`
	ItemizedIncomeRecOnBooksSch2   []interface{} `xml:"ItemizedIncomeRecOnBooksSch2,omitempty"`
	ItemizedOtherCatStatement      []interface{} `xml:"ItemizedOtherCatStatement,omitempty"`
	ItemizedOrdinaryIncomeLossStmt []interface{} `xml:"ItemizedOrdinaryIncomeLossStmt,omitempty"`
	ItemizedOtherCreditsSchedule   []interface{} `xml:"ItemizedOtherCreditsSchedule,omitempty"`
	ItemizedOtherDecreasesSch2     []interface{} `xml:"ItemizedOtherDecreasesSch2,omitempty"`
	ItemizedOtherDeductionSch3     []interface{} `xml:"ItemizedOtherDeductionSch3,omitempty"`
	ItemizedOtherIncomeLossSch     []interface{} `xml:"ItemizedOtherIncomeLossSch,omitempty"`
	ItemizedOtherIncreasesSch2     []interface{} `xml:"ItemizedOtherIncreasesSch2,omitempty"`
	ItemizedTotalForeignTaxesSch   []interface{} `xml:"ItemizedTotalForeignTaxesSch,omitempty"`
	LowIncomeHousingCreditStmt     []interface{} `xml:"LowIncomeHousingCreditStmt,omitempty"`
	MultipleCategory1FilersStmt    []interface{} `xml:"MultipleCategory1FilersStmt,omitempty"`
	NonconventionalSourceFuelCrSch []interface{} `xml:"NonconventionalSourceFuelCrSch,omitempty"`
	OtherAdjAndTaxPrefItemsSch     []interface{} `xml:"OtherAdjAndTaxPrefItemsSch,omitempty"`
	OtherItemsAndAmountsSchedule   []interface{} `xml:"OtherItemsAndAmountsSchedule,omitempty"`
	OtherPortfolioIncomeLossStmt   []interface{} `xml:"OtherPortfolioIncomeLossStmt,omitempty"`
	OtherRentalCreditsStatement    []interface{} `xml:"OtherRentalCreditsStatement,omitempty"`
	OtherRentalRealEstateCrStmt    []interface{} `xml:"OtherRentalRealEstateCrStmt,omitempty"`
	QualifiedRehbltExpendStatement []interface{} `xml:"QualifiedRehbltExpendStatement,omitempty"`
	ReconciliationStatement        []interface{} `xml:"ReconciliationStatement,omitempty"`
	ReductionInTaxesSchedule       []interface{} `xml:"ReductionInTaxesSchedule,omitempty"`
	REMICStatement                 []interface{} `xml:"REMICStatement,omitempty"`
	SaleOrExchangeCollectiblesStmt []interface{} `xml:"SaleOrExchangeCollectiblesStmt,omitempty"`
	Sect179ZoneEnterprisePropStmt  []interface{} `xml:"Sect179ZoneEnterprisePropStmt,omitempty"`
	Section59e2ExpenditureStmt     []interface{} `xml:"Section59e2ExpenditureStmt,omitempty"`
	SeparateUnitsSchedule          []interface{} `xml:"SeparateUnitsSchedule,omitempty"`
	SupplementalInfoStatement      []interface{} `xml:"SupplementalInfoStatement,omitempty"`
	TaxReductionExplanation        []interface{} `xml:"TaxReductionExplanation,omitempty"`
	UnrecapturedSection1250GainSch []interface{} `xml:"UnrecapturedSection1250GainSch,omitempty"`
	AdvancedCoalProjectPropStmt    []interface{} `xml:"AdvancedCoalProjectPropStmt,omitempty"`
	AgriBiodieselProducerCrStmt    []interface{} `xml:"AgriBiodieselProducerCrStmt,omitempty"`
	BasisOfEnergyPropertyStatement []interface{} `xml:"BasisOfEnergyPropertyStatement,omitempty"`
	CreditsRltdToRentalREActyStmt  []interface{} `xml:"CreditsRltdToRentalREActyStmt,omitempty"`
	CrRelatedToOtherRentalActyStmt []interface{} `xml:"CrRelatedToOtherRentalActyStmt,omitempty"`
	DefrdSect1045RllvrStmt         []interface{} `xml:"DefrdSect1045RllvrStmt,omitempty"`
	DisposOfPropWithSect179DedStmt []interface{} `xml:"DisposOfPropWithSect179DedStmt,omitempty"`
	DomesticProductionActivityStmt []interface{} `xml:"DomesticProductionActivityStmt,omitempty"`
	ExtraterritorialIncomeExclStmt []interface{} `xml:"ExtraterritorialIncomeExclStmt,omitempty"`
	F8865K1CollGainLossExpln       []interface{} `xml:"F8865K1CollGainLossExpln,omitempty"`
	F8865K1IntIncmExplanation      []interface{} `xml:"F8865K1IntIncmExplanation,omitempty"`
	F8865K1NetLTCapGainLossExpln   []interface{} `xml:"F8865K1NetLTCapGainLossExpln,omitempty"`
	F8865K1PrtflIncmLossRyltyExpln []interface{} `xml:"F8865K1PrtflIncmLossRyltyExpln,omitempty"`
	F8865K1PrtflIncmLsTotOrdnryDiv []interface{} `xml:"F8865K1PrtflIncmLsTotOrdnryDiv,omitempty"`
	F8865K1PrtnrPymtExplanation    []interface{} `xml:"F8865K1PrtnrPymtExplanation,omitempty"`
	F8865K1NetSTCapGainLossExpln   []interface{} `xml:"F8865K1NetSTCapGainLossExpln,omitempty"`
	F8865K1QlfyDivExplanation      []interface{} `xml:"F8865K1QlfyDivExplanation,omitempty"`
	ForeignTaxSchedule             []interface{} `xml:"ForeignTaxSchedule,omitempty"`
	ForeignTransactionStatement    []interface{} `xml:"ForeignTransactionStatement,omitempty"`
	FrgnGroIncmCorpLvlOtherCatSch  []interface{} `xml:"FrgnGroIncmCorpLvlOtherCatSch,omitempty"`
	GainEligibleSect1045RllvrStmt  []interface{} `xml:"GainEligibleSect1045RllvrStmt,omitempty"`
	GrossIncmSourcedAtShrLevelSch  []interface{} `xml:"GrossIncmSourcedAtShrLevelSch,omitempty"`
	IncmExpnssOthPssvRntlActyStmt  []interface{} `xml:"IncmExpnssOthPssvRntlActyStmt,omitempty"`
	ItemizedDedPrtflIncomeLossStmt []interface{} `xml:"ItemizedDedPrtflIncomeLossStmt,omitempty"`
	NetIncomeLossAtRiskREActySch   []interface{} `xml:"NetIncomeLossAtRiskREActySch,omitempty"`
	OilGasAndGthrmlPropertiesStmt  []interface{} `xml:"OilGasAndGthrmlPropertiesStmt,omitempty"`
	OtherRecaptureCreditsSchedule  []interface{} `xml:"OtherRecaptureCreditsSchedule,omitempty"`
	PartnersFilmTVProductionStmt   []interface{} `xml:"PartnersFilmTVProductionStmt,omitempty"`
	PartnersInversionGainStmt      []interface{} `xml:"PartnersInversionGainStmt,omitempty"`
	PssvActyOtherIncmLossSchedule  []interface{} `xml:"PssvActyOtherIncmLossSchedule,omitempty"`
	PssvActySect1231GainLossStmt   []interface{} `xml:"PssvActySect1231GainLossStmt,omitempty"`
	QlfyCnsrvContributionsStmt     []interface{} `xml:"QlfyCnsrvContributionsStmt,omitempty"`
	RecaptureInvestmentCreditStmt  []interface{} `xml:"RecaptureInvestmentCreditStmt,omitempty"`
	RnwblElecRefinedCoalProdCrStmt []interface{} `xml:"RnwblElecRefinedCoalProdCrStmt,omitempty"`
	Section1202ExclusionStatement  []interface{} `xml:"Section1202ExclusionStatement,omitempty"`
	Section42j5Schedule            []interface{} `xml:"Section42j5Schedule,omitempty"`
	SmallEthanolProducerCreditStmt []interface{} `xml:"SmallEthanolProducerCreditStmt,omitempty"`
	AmtOfRecaptureCalculationStmt  []interface{} `xml:"AmtOfRecaptureCalculationStmt,omitempty"`
	ContributedPropertyStatement   []interface{} `xml:"ContributedPropertyStatement,omitempty"`
	DatesOfTransferStatement       []interface{} `xml:"DatesOfTransferStatement,omitempty"`
	TransferStatement              []interface{} `xml:"TransferStatement,omitempty"`
	ContF8886ExpctTaxBnftExpln     []interface{} `xml:"ContF8886ExpctTaxBnftExpln,omitempty"`
	AssigneeRailroadTrackMilesStmt []interface{} `xml:"AssigneeRailroadTrackMilesStmt,omitempty"`
	AssignorRailroadTrackMilesStmt []interface{} `xml:"AssignorRailroadTrackMilesStmt,omitempty"`
	AddnlBondCYCreditStatmnt       interface{}   `xml:"AddnlBondCYCreditStatmnt,omitempty"`
	SpclDeprecAllwncElectOutStmt   []interface{} `xml:"SpclDeprecAllwncElectOutStmt,omitempty"`
	BasisOthThanActlCostPropStmt   []interface{} `xml:"BasisOthThanActlCostPropStmt,omitempty"`
	DedExpendSilviculturalActySch  []interface{} `xml:"DedExpendSilviculturalActySch,omitempty"`
	RequestForCopyAttachment       interface{}   `xml:"RequestForCopyAttachment,omitempty"`
	GeneralDependencySmall         []interface{} `xml:"GeneralDependencySmall,omitempty"`
	GeneralDependencyMedium        []interface{} `xml:"GeneralDependencyMedium,omitempty"`
	GeneralDependency              []interface{} `xml:"GeneralDependency,omitempty"`
	BinaryAttachment               []interface{} `xml:"BinaryAttachment,omitempty"`
}
