// Code generated by xgen. DO NOT EDIT.

package irsform

// SalesOfInventoryList is Common return document attributes
type SalesOfInventoryList struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*SalesOfInventoryListType
}

// SalesOfInventoryListType is Content model for sales of inventory list
type SalesOfInventoryListType struct {
	InventorySaleGrp []*InventorySaleGrpType `xml:"InventorySaleGrp,omitempty"`
}

// InventorySaleGrpType is Net (gross sales minus cost of goods sold)
type InventorySaleGrpType struct {
	CategoryTxt        string `xml:"CategoryTxt,omitempty"`
	GrossSalesAmt      int    `xml:"GrossSalesAmt,omitempty"`
	CostOfGoodsSoldAmt int    `xml:"CostOfGoodsSoldAmt,omitempty"`
	NetAmt             int    `xml:"NetAmt,omitempty"`
}
