// Code generated by xgen. DO NOT EDIT.

package irsform

// Sect4942a2ExplanationStatement is Common return document attributes
type Sect4942a2ExplanationStatement struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*Sect4942a2ExplanationStatementType
}

// Sect4942a2ExplanationStatementType is Content model for Section 4942(a)(2) Explanation Statement
type Sect4942a2ExplanationStatementType struct {
	ShortExplanationTxt string `xml:"ShortExplanationTxt,omitempty"`
}
