// Code generated by xgen. DO NOT EDIT.

package irsform

// Organization501cInd is shared across multiple IRS forms
type Organization501cInd struct {
	Organization501cTypeTxtAttr string `xml:"organization501cTypeTxt,attr,omitempty"`
	Value                       string `xml:",chardata"`
}

// SubjectToProxyTaxInd is shared across multiple IRS forms
type SubjectToProxyTaxInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// EngagedInExcessBenefitTransInd is shared across multiple IRS forms
type EngagedInExcessBenefitTransInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// BooksInCareOfDetail is shared across multiple IRS forms
type BooksInCareOfDetail struct {
	PersonNm       string              `xml:"PersonNm"`
	BusinessName   *BusinessNameType   `xml:"BusinessName"`
	PhoneNum       string              `xml:"PhoneNum"`
	USAddress      *USAddressType      `xml:"USAddress"`
	ForeignAddress *ForeignAddressType `xml:"ForeignAddress"`
}

// PoliticalCampaignActyInd is shared across multiple IRS forms
type PoliticalCampaignActyInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// LobbyingActivitiesInd is shared across multiple IRS forms
type LobbyingActivitiesInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// SchoolOperatingInd is shared across multiple IRS forms
type SchoolOperatingInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// MethodOfAccountingOtherInd is shared across multiple IRS forms
type MethodOfAccountingOtherInd struct {
	MethodOfAccountingOtherDescAttr string `xml:"methodOfAccountingOtherDesc,attr,omitempty"`
	Value                           string `xml:",chardata"`
}

// OrganizationDissolvedEtcInd is shared across multiple IRS forms
type OrganizationDissolvedEtcInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// DonorAdvisedFundInd is shared across multiple IRS forms
type DonorAdvisedFundInd struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     bool        `xml:",chardata"`
}

// PersonNm is shared across multiple IRS forms
type PersonNm struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	Value                     string      `xml:",chardata"`
}

// BusinessName is shared across multiple IRS forms
type BusinessName struct {
	ReferenceDocumentIdAttr   *IdListType `xml:"referenceDocumentId,attr,omitempty"`
	ReferenceDocumentNameAttr string      `xml:"referenceDocumentName,attr,omitempty"`
	*BusinessNameType
}

// SupplementalInformationDetail is shared across multiple IRS forms
type SupplementalInformationDetail struct {
	FormAndLineReferenceDesc string `xml:"FormAndLineReferenceDesc,omitempty"`
	ExplanationTxt           string `xml:"ExplanationTxt,omitempty"`
}