// Code generated by xgen. DO NOT EDIT.

package irsform

import (
	"encoding/xml"
)

// Envelope ...
type Envelope *Envelope

// Header ...
type Header *Header

// Body ...
type Body *Body

// MustUnderstand ...
type MustUnderstand bool

// Actor ...
type Actor string

// EncodingStyle is 'encodingStyle' indicates any canonicalization conventions followed in the contents of the containing element.  For example, the value 'http://schemas.xmlsoap.org/soap/encoding/' indicates the pattern described in SOAP specification
type EncodingStyle []string

// Fault is Fault reporting structure
type Fault struct {
	Faultcode   xml.Name `xml:"faultcode"`
	Faultstring string   `xml:"faultstring"`
	Faultactor  string   `xml:"faultactor,omitempty"`
	Detail      *Detail  `xml:"detail,omitempty"`
}

// Detail ...
type Detail struct {
	XMLName xml.Name `xml:"detail"`
}
