// Code generated by xgen. DO NOT EDIT.

package irsform

// SubstantialContributorsSch is Common return document attributes
type SubstantialContributorsSch struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*SubstantialContributorsSchType
}

// SubstantialContributorDetail is Contributor's Foreign Address
type SubstantialContributorDetail struct {
	BusinessName   *BusinessNameType   `xml:"BusinessName"`
	PersonNm       string              `xml:"PersonNm"`
	USAddress      *USAddressType      `xml:"USAddress"`
	ForeignAddress *ForeignAddressType `xml:"ForeignAddress"`
}

// SubstantialContributorsSchType is Content model for Substantial Contributors Schedule
type SubstantialContributorsSchType struct {
	SubstantialContributorDetail []*SubstantialContributorDetail `xml:"SubstantialContributorDetail,omitempty"`
}
