// Code generated by xgen. DO NOT EDIT.

package irsform

// TaxesSchedule is Common return document attributes
type TaxesSchedule struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*TaxesScheduleType
}

// TaxesDetail is Disbursements for Charitable Purposes
type TaxesDetail struct {
	CategoryTxt                    string `xml:"CategoryTxt,omitempty"`
	Amt                            int    `xml:"Amt,omitempty"`
	NetInvestmentIncomeAmt         int    `xml:"NetInvestmentIncomeAmt,omitempty"`
	AdjustedNetIncomeAmt           int    `xml:"AdjustedNetIncomeAmt,omitempty"`
	DisbursementsCharitablePrpsAmt int    `xml:"DisbursementsCharitablePrpsAmt,omitempty"`
}

// TaxesScheduleType is Content model for Taxes Schedule
type TaxesScheduleType struct {
	TaxesDetail []*TaxesDetail `xml:"TaxesDetail,omitempty"`
}
