// Code generated by xgen. DO NOT EDIT.

package irsform

// TaxUnderSection511Statement is Common return document attributes
type TaxUnderSection511Statement struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*TaxUnderSection511StatementType
}

// TaxUnderSection511StatementType is Content model for Tax Under Section 511 Statement
type TaxUnderSection511StatementType struct {
	ExplanationTxt string `xml:"ExplanationTxt,omitempty"`
}
