// Code generated by xgen. DO NOT EDIT.

package irsform

// TransfersFrmControlledEntities is Common return document attributes
type TransfersFrmControlledEntities struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*TransfersFromControlledEntitiesScheduleType
}

// TransfersFromControlledEntGrp is Amount of transfer
type TransfersFromControlledEntGrp struct {
	BusinessName   *BusinessNameType   `xml:"BusinessName"`
	USAddress      *USAddressType      `xml:"USAddress"`
	ForeignAddress *ForeignAddressType `xml:"ForeignAddress"`
	EIN            string              `xml:"EIN"`
	Desc           string              `xml:"Desc"`
	Amt            int                 `xml:"Amt"`
}

// TransfersFromControlledEntitiesScheduleType is Content model for Transfers From Controlled Entities Schedule
type TransfersFromControlledEntitiesScheduleType struct {
	TransfersFromControlledEntGrp []*TransfersFromControlledEntGrp `xml:"TransfersFromControlledEntGrp,omitempty"`
	TotalAmt                      int                              `xml:"TotalAmt,omitempty"`
}
