// Code generated by xgen. DO NOT EDIT.

package irsform

// TransfersToControlledEntities is Common return document attributes
type TransfersToControlledEntities struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*TransfersToControlledEntitiesScheduleType
}

// TransfersToControlledEntGrp is Amount of transfer
type TransfersToControlledEntGrp struct {
	BusinessName   *BusinessNameType   `xml:"BusinessName"`
	USAddress      *USAddressType      `xml:"USAddress"`
	ForeignAddress *ForeignAddressType `xml:"ForeignAddress"`
	EIN            string              `xml:"EIN"`
	Desc           string              `xml:"Desc"`
	Amt            int                 `xml:"Amt"`
}

// TransfersToControlledEntitiesScheduleType is Content model for Transfers To Controlled Entities Schedule
type TransfersToControlledEntitiesScheduleType struct {
	TransfersToControlledEntGrp []*TransfersToControlledEntGrp `xml:"TransfersToControlledEntGrp,omitempty"`
	TotalAmt                    int                            `xml:"TotalAmt,omitempty"`
}
