// Code generated by xgen. DO NOT EDIT.

package irsform

// TransferPrsnlBnftContractsDecl is Common return document attributes
type TransferPrsnlBnftContractsDecl struct {
	DocumentAttributes *DocumentAttributes
	DocumentNameAttr   string `xml:"documentName,attr,omitempty"`
	*TrnsfrPrsnlBnftCntrctDeclTyp
}

// TrnsfrPrsnlBnftCntrctDeclTyp is Declaration
type TrnsfrPrsnlBnftCntrctDeclTyp struct {
	DeclarationDesc string `xml:"DeclarationDesc,omitempty"`
}
